/**
 * DI tokens for Communication repositories.
 */
export const NOTIFICATION_REPOSITORY = Symbol('NOTIFICATION_REPOSITORY');
export const ANNOUNCEMENT_REPOSITORY = Symbol('ANNOUNCEMENT_REPOSITORY');
export const CONVERSATION_REPOSITORY = Symbol('CONVERSATION_REPOSITORY');
export const MESSAGE_REPOSITORY = Symbol('MESSAGE_REPOSITORY');
export const COMMUNICATION_TEMPLATE_REPOSITORY = Symbol('COMMUNICATION_TEMPLATE_REPOSITORY');
