-- PreOne Wave 23.03 — Platform management tables
-- =====================================================================
-- Migration ID: 20260717000003_wave_23_03_platform_tables
-- Wave: 23
-- Idempotent: YES (uses CREATE TYPE/TABLE IF NOT EXISTS, DROP IF EXISTS)
--
-- Creates 8 platform-level tables (no school_id for some — they are
platform-scoped, protected by role grants rather than RLS):
  storage_usage, feature_usage, platform_api_key, platform_backup,
  platform_audit_log, platform_feature_flag, platform_metric,
  platform_integration_config.

These tables back the platform/admin UI (Wave 17.1 tenant config,
Wave 19 file storage accounting, Wave 22 BRC traceability matrix).
--
-- Conventions (per ERD v3.0 §3 + BTD §16):
--   - Tables: snake_case plural
--   - Columns: snake_case
--   - PKs: UUID v7 (time-sortable)
--   - Timestamps: timestamptz
--   - Money: integer cents (amount_cents) — never float
--   - Soft delete: deleted_at timestamptz NULL
--   - Optimistic concurrency: version INTEGER DEFAULT 1
--   - Tenant isolation: school_id discriminator + RLS policy
--   - Audit columns: created_at, created_by, updated_at, updated_by,
--                    deleted_at, deleted_by
--
-- This migration is auto-generated by scripts/wave23_migrations_gen.py.
-- Do not edit by hand — re-run the script instead.

-- ───────────────────────────────────────────────────────────────────────
-- 1. storage_usage — per-school per-month storage consumption
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS storage_usage (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    period_month    DATE NOT NULL,  -- first day of month
    bytes_used      BIGINT NOT NULL DEFAULT 0,
    bytes_limit     BIGINT NOT NULL DEFAULT 5368709120,  -- 5 GiB default
    file_count      INTEGER NOT NULL DEFAULT 0,
    archived_bytes  BIGINT NOT NULL DEFAULT 0,
    metadata        JSONB,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (school_id, period_month)
);
CREATE INDEX IF NOT EXISTS storage_usage_school_month_idx
    ON storage_usage(school_id, period_month DESC);

-- ───────────────────────────────────────────────────────────────────────
-- 2. feature_usage — per-school per-day feature consumption counters
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS feature_usage (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    feature_key     VARCHAR(64) NOT NULL,
    period_day      DATE NOT NULL,
    count           BIGINT NOT NULL DEFAULT 0,
    metadata        JSONB,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (school_id, feature_key, period_day)
);

-- ───────────────────────────────────────────────────────────────────────
-- 3. platform_api_key — platform-level API keys for integrations
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS platform_api_key (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    name            VARCHAR(120) NOT NULL,
    key_prefix      VARCHAR(16) NOT NULL,
    key_hash        VARCHAR(255) NOT NULL,
    scopes          TEXT[],
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    expires_at      TIMESTAMPTZ,
    last_used_at    TIMESTAMPTZ,
    created_by      UUID,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS platform_api_key_hash_uq
    ON platform_api_key(key_hash);

-- ───────────────────────────────────────────────────────────────────────
-- 4. platform_backup — platform-level backup metadata
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS platform_backup (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    backup_type     VARCHAR(32) NOT NULL CHECK (backup_type IN ('AUTOMATED','MANUAL','PRE_DEPLOY')),
    status          VARCHAR(20) NOT NULL CHECK (status IN ('STARTED','COMPLETED','FAILED','VERIFIED','EXPIRED')),
    started_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at    TIMESTAMPTZ,
    size_bytes      BIGINT,
    location        VARCHAR(512),
    checksum        VARCHAR(64),
    retention_until TIMESTAMPTZ,
    metadata        JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ───────────────────────────────────────────────────────────────────────
-- 5. platform_audit_log — platform-level audit log (cross-school)
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS platform_audit_log (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    actor_id        UUID,
    actor_email     VARCHAR(255),
    action          VARCHAR(64) NOT NULL,
    resource_type   VARCHAR(64) NOT NULL,
    resource_id     VARCHAR(64),
    before_state    JSONB,
    after_state     JSONB,
    ip_address      INET,
    user_agent      TEXT,
    occurred_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS platform_audit_log_action_time_idx
    ON platform_audit_log(action, occurred_at DESC);
CREATE INDEX IF NOT EXISTS platform_audit_log_resource_idx
    ON platform_audit_log(resource_type, resource_id);

-- ───────────────────────────────────────────────────────────────────────
-- 6. platform_feature_flag — platform-level feature flags
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS platform_feature_flag (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    key             VARCHAR(64) NOT NULL UNIQUE,
    description     TEXT,
    is_enabled      BOOLEAN NOT NULL DEFAULT FALSE,
    rollout_percent SMALLINT NOT NULL DEFAULT 0 CHECK (rollout_percent BETWEEN 0 AND 100),
    school_ids      UUID[],
    metadata        JSONB,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ───────────────────────────────────────────────────────────────────────
-- 7. platform_metric — daily platform KPI snapshots
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS platform_metric (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    metric_key      VARCHAR(64) NOT NULL,
    period_day      DATE NOT NULL,
    value_numeric   DOUBLE PRECISION,
    value_text      TEXT,
    metadata        JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (metric_key, period_day)
);

-- ───────────────────────────────────────────────────────────────────────
-- 8. platform_integration_config — per-school integration overrides
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS platform_integration_config (
    id                  UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id           UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    integration_key     VARCHAR(64) NOT NULL,  -- 'sendgrid' | 'twilio' | 'razorpay' | 'openai'
    is_enabled          BOOLEAN NOT NULL DEFAULT FALSE,
    config_encrypted    BYTEA,                  -- pgcrypto-encrypted
    priority            SMALLINT NOT NULL DEFAULT 0,
    version             INTEGER NOT NULL DEFAULT 1,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at          TIMESTAMPTZ,
    UNIQUE (school_id, integration_key)
);

-- ───────────────────────────────────────────────────────────────────────
-- RLS + triggers
-- ───────────────────────────────────────────────────────────────────────
ALTER TABLE storage_usage                ENABLE ROW LEVEL SECURITY;
ALTER TABLE feature_usage                ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_integration_config  ENABLE ROW LEVEL SECURITY;

CREATE POLICY storage_usage_tenant               ON storage_usage               USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY feature_usage_tenant               ON feature_usage               USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY platform_integration_config_tenant ON platform_integration_config USING (school_id = current_setting('app.current_school_id', true)::uuid);

-- platform_api_key, platform_backup, platform_audit_log, platform_feature_flag,
-- platform_metric are platform-level (no school_id) — protected by role grants.

