export const ATTENDANCE_REPOSITORY = Symbol('ATTENDANCE_REPOSITORY');
export const DAILY_LOG_REPOSITORY = Symbol('DAILY_LOG_REPOSITORY');
export const INCIDENT_REPORT_REPOSITORY = Symbol('INCIDENT_REPORT_REPOSITORY');
export const DAILY_REPORT_REPOSITORY = Symbol('DAILY_REPORT_REPOSITORY');
export const MEDICINE_AUTHORIZATION_REPOSITORY = Symbol('MEDICINE_AUTHORIZATION_REPOSITORY');
