-- PreOne Wave 23.04 — Settings tables
-- =====================================================================
-- Migration ID: 20260717000004_wave_23_04_settings_tables
-- Wave: 23
-- Idempotent: YES (uses CREATE TYPE/TABLE IF NOT EXISTS, DROP IF EXISTS)
--
-- Creates 12 settings tables:
  academic_calendar, room, room_booking, event, system_setting,
  user_preference, notification_preference, locale_setting,
  branding_setting, integration_setting, audit_retention_setting,
  email_template.
--
-- Conventions (per ERD v3.0 §3 + BTD §16):
--   - Tables: snake_case plural
--   - Columns: snake_case
--   - PKs: UUID v7 (time-sortable)
--   - Timestamps: timestamptz
--   - Money: integer cents (amount_cents) — never float
--   - Soft delete: deleted_at timestamptz NULL
--   - Optimistic concurrency: version INTEGER DEFAULT 1
--   - Tenant isolation: school_id discriminator + RLS policy
--   - Audit columns: created_at, created_by, updated_at, updated_by,
--                    deleted_at, deleted_by
--
-- This migration is auto-generated by scripts/wave23_migrations_gen.py.
-- Do not edit by hand — re-run the script instead.

-- ───────────────────────────────────────────────────────────────────────
-- 1. academic_calendar — school calendar events (holidays, exams, etc.)
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS academic_calendar (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID REFERENCES branches(id) ON DELETE CASCADE,
    title           VARCHAR(255) NOT NULL,
    event_type      VARCHAR(40) NOT NULL CHECK (event_type IN (
                    'HOLIDAY','EXAM','PTM','SPORTS_DAY','CULTURAL','FIELD_TRIP',
                    'PROFESSIONAL_DAY','OTHER')),
    start_date      DATE NOT NULL,
    end_date        DATE NOT NULL,
    is_full_day     BOOLEAN NOT NULL DEFAULT TRUE,
    start_time      TIME,
    end_time        TIME,
    description     TEXT,
    affects_attendance BOOLEAN NOT NULL DEFAULT TRUE,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    deleted_at      TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS academic_calendar_school_date_idx
    ON academic_calendar(school_id, start_date, end_date);

-- ───────────────────────────────────────────────────────────────────────
-- 2. room — physical rooms in branches
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS room (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    name            VARCHAR(120) NOT NULL,
    code            VARCHAR(32) NOT NULL,
    room_type       VARCHAR(32) NOT NULL CHECK (room_type IN (
                    'CLASSROOM','LAB','LIBRARY','PLAY_AREA','STAFF_ROOM',
                    'OFFICE','STORAGE','KITCHEN','WASHROOM','OTHER')),
    capacity        INTEGER CHECK (capacity >= 0),
    floor_number    SMALLINT,
    metadata        JSONB,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    deleted_at      TIMESTAMPTZ,
    UNIQUE (branch_id, code)
);

-- ───────────────────────────────────────────────────────────────────────
-- 3. room_booking — room reservation slots
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS room_booking (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    room_id         UUID NOT NULL REFERENCES room(id) ON DELETE CASCADE,
    booked_by       UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    title           VARCHAR(255) NOT NULL,
    starts_at       TIMESTAMPTZ NOT NULL,
    ends_at         TIMESTAMPTZ NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED'
                    CHECK (status IN ('PENDING','CONFIRMED','CANCELLED','COMPLETED','NO_SHOW')),
    notes           TEXT,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS room_booking_room_time_idx
    ON room_booking(room_id, starts_at, ends_at);

-- ───────────────────────────────────────────────────────────────────────
-- 4. event — calendar events at school/branch level
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS event (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID REFERENCES branches(id) ON DELETE CASCADE,
    title           VARCHAR(255) NOT NULL,
    event_type      VARCHAR(40) NOT NULL,
    starts_at       TIMESTAMPTZ NOT NULL,
    ends_at         TIMESTAMPTZ,
    location        VARCHAR(255),
    description     TEXT,
    status          VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED'
                    CHECK (status IN ('SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED','POSTPONED')),
    organiser_id    UUID REFERENCES users(id) ON DELETE SET NULL,
    metadata        JSONB,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    deleted_at      TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS event_school_start_idx
    ON event(school_id, starts_at);

-- ───────────────────────────────────────────────────────────────────────
-- 5. system_setting — school-level config key/value store
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS system_setting (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    setting_key     VARCHAR(96) NOT NULL,
    setting_value   JSONB NOT NULL,
    is_sensitive    BOOLEAN NOT NULL DEFAULT FALSE,
    description     TEXT,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    UNIQUE (school_id, setting_key)
);

-- ───────────────────────────────────────────────────────────────────────
-- 6. user_preference — per-user UI preferences
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_preference (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    preference_key  VARCHAR(96) NOT NULL,
    preference_value JSONB NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, preference_key)
);

-- ───────────────────────────────────────────────────────────────────────
-- 7. notification_preference — per-user notification channel opt-ins
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS notification_preference (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    notification_type VARCHAR(64) NOT NULL,
    email_enabled   BOOLEAN NOT NULL DEFAULT TRUE,
    sms_enabled     BOOLEAN NOT NULL DEFAULT FALSE,
    whatsapp_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    push_enabled    BOOLEAN NOT NULL DEFAULT TRUE,
    in_app_enabled  BOOLEAN NOT NULL DEFAULT TRUE,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, school_id, notification_type)
);

-- ───────────────────────────────────────────────────────────────────────
-- 8. locale_setting — per-school locale config
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS locale_setting (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    locale          VARCHAR(8) NOT NULL DEFAULT 'en-IN',
    timezone        VARCHAR(64) NOT NULL DEFAULT 'Asia/Kolkata',
    currency_code   VARCHAR(3) NOT NULL DEFAULT 'INR',
    date_format     VARCHAR(32) NOT NULL DEFAULT 'DD-MM-YYYY',
    first_day_of_week SMALLINT NOT NULL DEFAULT 1 CHECK (first_day_of_week BETWEEN 0 AND 6),
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (school_id)
);

-- ───────────────────────────────────────────────────────────────────────
-- 9. branding_setting — per-school white-label branding
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS branding_setting (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    logo_url        VARCHAR(512),
    primary_color   VARCHAR(7),
    secondary_color VARCHAR(7),
    custom_css      TEXT,
    display_name    VARCHAR(120),
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (school_id)
);

-- ───────────────────────────────────────────────────────────────────────
-- 10. integration_setting — per-school third-party integration config
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS integration_setting (
    id                  UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id           UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    integration_key     VARCHAR(64) NOT NULL,
    is_enabled          BOOLEAN NOT NULL DEFAULT FALSE,
    credentials_encrypted BYTEA,
    settings            JSONB,
    version             INTEGER NOT NULL DEFAULT 1,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (school_id, integration_key)
);

-- ───────────────────────────────────────────────────────────────────────
-- 11. audit_retention_setting — per-school audit log retention (R-CMP-006)
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_retention_setting (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    audit_category  VARCHAR(64) NOT NULL,
    retention_days  INTEGER NOT NULL DEFAULT 365 CHECK (retention_days >= 30),
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (school_id, audit_category)
);

-- ───────────────────────────────────────────────────────────────────────
-- 12. email_template — per-school email templates
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS email_template (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    template_key    VARCHAR(96) NOT NULL,
    subject         VARCHAR(255) NOT NULL,
    body_html       TEXT,
    body_text       TEXT,
    locale          VARCHAR(8) NOT NULL DEFAULT 'en-IN',
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    deleted_at      TIMESTAMPTZ,
    UNIQUE (school_id, template_key, locale)
);

-- ───────────────────────────────────────────────────────────────────────
-- RLS + triggers
-- ───────────────────────────────────────────────────────────────────────
ALTER TABLE academic_calendar         ENABLE ROW LEVEL SECURITY;
ALTER TABLE room                      ENABLE ROW LEVEL SECURITY;
ALTER TABLE room_booking              ENABLE ROW LEVEL SECURITY;
ALTER TABLE event                     ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_setting            ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_preference           ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_preference   ENABLE ROW LEVEL SECURITY;
ALTER TABLE locale_setting            ENABLE ROW LEVEL SECURITY;
ALTER TABLE branding_setting          ENABLE ROW LEVEL SECURITY;
ALTER TABLE integration_setting       ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_retention_setting   ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_template            ENABLE ROW LEVEL SECURITY;

CREATE POLICY academic_calendar_tenant        ON academic_calendar       USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY room_tenant                     ON room                    USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY room_booking_tenant             ON room_booking            USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY event_tenant                    ON event                   USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY system_setting_tenant           ON system_setting          USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY notification_preference_tenant  ON notification_preference USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY locale_setting_tenant           ON locale_setting          USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY branding_setting_tenant         ON branding_setting        USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY integration_setting_tenant      ON integration_setting     USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY audit_retention_setting_tenant  ON audit_retention_setting USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY email_template_tenant           ON email_template          USING (school_id = current_setting('app.current_school_id', true)::uuid);

DO $$
DECLARE t TEXT;
BEGIN
    FOR t IN SELECT unnest(ARRAY[
        'academic_calendar','room','room_booking','event','system_setting',
        'user_preference','notification_preference','locale_setting',
        'branding_setting','integration_setting','audit_retention_setting',
        'email_template'
    ])
    LOOP
        EXECUTE format(
            'DROP TRIGGER IF EXISTS trg_%I_updated_at ON %I; '
            'CREATE TRIGGER trg_%I_updated_at BEFORE UPDATE ON %I '
            'FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();',
            t, t, t, t
        );
    END LOOP;
END $$;

