/**
 * DI tokens for Reports repositories.
 */
export const REPORT_DEFINITION_REPOSITORY = Symbol('REPORT_DEFINITION_REPOSITORY');
export const REPORT_EXECUTION_REPOSITORY = Symbol('REPORT_EXECUTION_REPOSITORY');
export const SAVED_REPORT_REPOSITORY = Symbol('SAVED_REPORT_REPOSITORY');
export const REPORT_SUBSCRIPTION_REPOSITORY = Symbol('REPORT_SUBSCRIPTION_REPOSITORY');
