/**
 * DI tokens for Platform repositories.
 */
export const TENANT_PROVISIONING_REPOSITORY = Symbol('TENANT_PROVISIONING_REPOSITORY');
export const FEATURE_FLAG_REPOSITORY = Symbol('FEATURE_FLAG_REPOSITORY');
export const SUPPORT_TICKET_REPOSITORY = Symbol('SUPPORT_TICKET_REPOSITORY');
export const SUPPORT_TICKET_COMMENT_REPOSITORY = Symbol('SUPPORT_TICKET_COMMENT_REPOSITORY');
