/**
 * DI tokens for Inventory repositories.
 */
export const INVENTORY_ITEM_REPOSITORY = Symbol('INVENTORY_ITEM_REPOSITORY');
export const SUPPLIER_REPOSITORY = Symbol('SUPPLIER_REPOSITORY');
export const PURCHASE_ORDER_REPOSITORY = Symbol('PURCHASE_ORDER_REPOSITORY');
export const GOODS_RECEIPT_NOTE_REPOSITORY = Symbol('GOODS_RECEIPT_NOTE_REPOSITORY');
export const GOODS_ISSUE_REPOSITORY = Symbol('GOODS_ISSUE_REPOSITORY');
