/**
 * DI tokens for Academics module repositories (BTD §6.1 — Port/Adapter pattern).
 */
export const ACADEMIC_SESSION_REPOSITORY = Symbol('ACADEMIC_SESSION_REPOSITORY');
export const CURRICULUM_REPOSITORY = Symbol('CURRICULUM_REPOSITORY');
export const SECTION_REPOSITORY = Symbol('SECTION_REPOSITORY');
export const ENROLLMENT_REPOSITORY = Symbol('ENROLLMENT_REPOSITORY');
export const OBSERVATION_REPOSITORY = Symbol('OBSERVATION_REPOSITORY');
export const ASSESSMENT_REPOSITORY = Symbol('ASSESSMENT_REPOSITORY');
export const REPORT_CARD_REPOSITORY = Symbol('REPORT_CARD_REPOSITORY');
export const PORTFOLIO_REPOSITORY = Symbol('PORTFOLIO_REPOSITORY');
