/**
 * DI tokens for Transport repositories.
 */
export const VEHICLE_REPOSITORY = Symbol('VEHICLE_REPOSITORY');
export const ROUTE_REPOSITORY = Symbol('ROUTE_REPOSITORY');
export const TRIP_REPOSITORY = Symbol('TRIP_REPOSITORY');
export const STUDENT_ROUTE_ASSIGNMENT_REPOSITORY = Symbol('STUDENT_ROUTE_ASSIGNMENT_REPOSITORY');
export const TRANSPORT_ATTENDANCE_REPOSITORY = Symbol('TRANSPORT_ATTENDANCE_REPOSITORY');
