-- PreOne Wave 23.08 — Acceptance test ID registry + migration audit
-- =====================================================================
-- Migration ID: 20260717000008_wave_23_08_acceptance_seed
-- Wave: 23
-- Idempotent: YES (uses CREATE TYPE/TABLE IF NOT EXISTS, DROP IF EXISTS)
--
-- Creates 2 observability tables:
  acceptance_test_registry — registry of 75 stable acceptance test IDs
    (A-001..A-087, ranges reserved by category).
  migration_audit — per-migration audit log with checksum + duration.

Seeds 87 acceptance test IDs covering migrations 01..08 plus 6
cross-cutting convention checks (A-082..A-087).
--
-- Conventions (per ERD v3.0 §3 + BTD §16):
--   - Tables: snake_case plural
--   - Columns: snake_case
--   - PKs: UUID v7 (time-sortable)
--   - Timestamps: timestamptz
--   - Money: integer cents (amount_cents) — never float
--   - Soft delete: deleted_at timestamptz NULL
--   - Optimistic concurrency: version INTEGER DEFAULT 1
--   - Tenant isolation: school_id discriminator + RLS policy
--   - Audit columns: created_at, created_by, updated_at, updated_by,
--                    deleted_at, deleted_by
--
-- This migration is auto-generated by scripts/wave23_migrations_gen.py.
-- Do not edit by hand — re-run the script instead.

-- ───────────────────────────────────────────────────────────────────────
-- 1. acceptance_test_registry — registry of all acceptance test IDs
--
-- Used by the Wave 23 acceptance test suite (test/unit/migrations/
-- wave-23-acceptance.spec.ts) to assert that every stable test ID has a
-- corresponding migration step that it exercises.
--
-- Format: A-XXX (zero-padded 3-digit), e.g. A-001, A-017, A-099.
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS acceptance_test_registry (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    test_id         VARCHAR(16) NOT NULL UNIQUE,  -- e.g. 'A-001'
    test_category   VARCHAR(64) NOT NULL,
    test_title      VARCHAR(255) NOT NULL,
    migration_id    VARCHAR(120) NOT NULL,  -- references migration directory name
    target_table    VARCHAR(64),
    target_enum     VARCHAR(64),
    expected_statement VARCHAR(32) NOT NULL DEFAULT 'CREATE',  -- CREATE/ALTER/DROP
    description     TEXT,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS acceptance_test_registry_migration_idx
    ON acceptance_test_registry(migration_id);
CREATE INDEX IF NOT EXISTS acceptance_test_registry_category_idx
    ON acceptance_test_registry(test_category);

-- ───────────────────────────────────────────────────────────────────────
-- 2. migration_audit — tracks every applied migration with timestamp,
--    checksum, and outcome. Replaces _prisma_migrations for app-level
--    observability (Prisma's own table remains the source of truth).
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS migration_audit (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    migration_id    VARCHAR(120) NOT NULL UNIQUE,
    applied_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    checksum_sha256 VARCHAR(64) NOT NULL,
    duration_ms     INTEGER,
    outcome         VARCHAR(20) NOT NULL CHECK (outcome IN ('SUCCESS','FAILED','ROLLED_BACK')),
    error_message   TEXT,
    applied_by      VARCHAR(120),
    metadata        JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ───────────────────────────────────────────────────────────────────────
-- Seed the 5 most critical acceptance test IDs (full registry is in the
-- spec file test/unit/migrations/wave-23-acceptance.spec.ts which contains
-- the authoritative list of A-001 through A-087).
-- ───────────────────────────────────────────────────────────────────────
INSERT INTO acceptance_test_registry (test_id, test_category, test_title, migration_id, target_table, expected_statement, description) VALUES
  ('A-001','cross-cutting','event_store table created','20260717000001_wave_23_01_cross_cutting_tables','event_store','CREATE','EventStore append-only log table exists with school_id RLS policy'),
  ('A-002','cross-cutting','file_storage table created','20260717000001_wave_23_01_cross_cutting_tables','file_storage','CREATE','FileStorage table with bucket+object_key unique constraint'),
  ('A-003','cross-cutting','job_queue table created','20260717000001_wave_23_01_cross_cutting_tables','job_queue','CREATE','JobQueue with status+available_at polling index'),
  ('A-004','cross-cutting','webhook_outbox table created','20260717000001_wave_23_01_cross_cutting_tables','webhook_outbox','CREATE','WebhookOutbox with partial index on PENDING status'),
  ('A-005','cross-cutting','email_queue table created','20260717000001_wave_23_01_cross_cutting_tables','email_queue','CREATE','EmailQueue with provider+provider_id columns'),
  ('A-006','cross-cutting','sms_queue table created','20260717000001_wave_23_01_cross_cutting_tables','sms_queue','CREATE','SMSQueue with DLT entity/template columns'),
  ('A-007','cross-cutting','whatsapp_queue table created','20260717000001_wave_23_01_cross_cutting_tables','whatsapp_queue','CREATE','WhatsAppQueue with template_name/language columns'),
  ('A-008','cross-cutting','food_sample_retention table created','20260717000001_wave_23_01_cross_cutting_tables','food_sample_retention','CREATE','FSSAI §15 sample retention tracker (R-CMP-018)'),
  ('A-009','cross-cutting','cctv_coverage table created','20260717000001_wave_23_01_cross_cutting_tables','cctv_coverage','CREATE','CCTV coverage map with retention_days CHECK constraint (R-CMP-005)'),
  ('A-010','cross-cutting','compliance_item table created','20260717000001_wave_23_01_cross_cutting_tables','compliance_item','CREATE','Compliance tracker with category CHECK (R-CMP-007/013/014/017/018)'),
  ('A-011','cross-cutting','lock table created','20260717000001_wave_23_01_cross_cutting_tables','lock','CREATE','Advisory lock table with unique lock_key'),
  ('A-012','cross-cutting','sequence_counter table created','20260717000001_wave_23_01_cross_cutting_tables','sequence_counter','CREATE','Monotonic counter with school_id+counter_key unique'),
  ('A-013','cross-cutting','snapshot table created','20260717000001_wave_23_01_cross_cutting_tables','snapshot','CREATE','Aggregate state snapshots for replay optimization'),
  ('A-014','cross-cutting','system_health_check table created','20260717000001_wave_23_01_cross_cutting_tables','system_health_check','CREATE','Probe result log with component+checked_at index'),
  ('A-015','cross-cutting','event_store RLS policy enabled','20260717000001_wave_23_01_cross_cutting_tables','event_store','CREATE','RLS policy enforces tenant isolation'),
  ('A-016','cross-cutting','file_upload table created','20260717000001_wave_23_01_cross_cutting_tables','file_upload','CREATE','Upload session tracking with scan_state column'),
  ('A-017','enums','placeholder enums replaced with real values','20260717000002_wave_23_02_cross_cutting_enums',NULL,'CREATE','All 50 Wave 13 PLACEHOLDER enums replaced with real values from schema.prisma'),
  ('A-018','platform','storage_usage table created','20260717000003_wave_23_03_platform_tables','storage_usage','CREATE','Per-school per-month storage consumption tracker'),
  ('A-019','platform','feature_usage table created','20260717000003_wave_23_03_platform_tables','feature_usage','CREATE','Per-school per-day feature consumption counters'),
  ('A-020','platform','platform_api_key table created','20260717000003_wave_23_03_platform_tables','platform_api_key','CREATE','Platform-level API keys with key_hash unique'),
  ('A-021','platform','platform_backup table created','20260717000003_wave_23_03_platform_tables','platform_backup','CREATE','Platform backup metadata with retention_until'),
  ('A-022','platform','platform_audit_log table created','20260717000003_wave_23_03_platform_tables','platform_audit_log','CREATE','Cross-school platform audit log'),
  ('A-023','platform','platform_feature_flag table created','20260717000003_wave_23_03_platform_tables','platform_feature_flag','CREATE','Platform-level feature flags with rollout_percent'),
  ('A-024','platform','platform_metric table created','20260717000003_wave_23_03_platform_tables','platform_metric','CREATE','Daily platform KPI snapshots'),
  ('A-025','platform','platform_integration_config table created','20260717000003_wave_23_03_platform_tables','platform_integration_config','CREATE','Per-school integration overrides with encrypted config'),
  ('A-026','settings','academic_calendar table created','20260717000004_wave_23_04_settings_tables','academic_calendar','CREATE','School calendar events with affects_attendance flag'),
  ('A-027','settings','room table created','20260717000004_wave_23_04_settings_tables','room','CREATE','Physical rooms with capacity+room_type'),
  ('A-028','settings','room_booking table created','20260717000004_wave_23_04_settings_tables','room_booking','CREATE','Room reservation slots with status workflow'),
  ('A-029','settings','event table created','20260717000004_wave_23_04_settings_tables','event','CREATE','Calendar events with status workflow'),
  ('A-030','settings','system_setting table created','20260717000004_wave_23_04_settings_tables','system_setting','CREATE','School-level key/value config with is_sensitive flag'),
  ('A-031','settings','user_preference table created','20260717000004_wave_23_04_settings_tables','user_preference','CREATE','Per-user UI preferences'),
  ('A-032','settings','notification_preference table created','20260717000004_wave_23_04_settings_tables','notification_preference','CREATE','Per-user per-notification-type channel opt-ins'),
  ('A-033','settings','locale_setting table created','20260717000004_wave_23_04_settings_tables','locale_setting','CREATE','Per-school locale/timezone/currency config'),
  ('A-034','settings','branding_setting table created','20260717000004_wave_23_04_settings_tables','branding_setting','CREATE','Per-school white-label branding'),
  ('A-035','settings','integration_setting table created','20260717000004_wave_23_04_settings_tables','integration_setting','CREATE','Per-school third-party integration config'),
  ('A-036','settings','audit_retention_setting table created','20260717000004_wave_23_04_settings_tables','audit_retention_setting','CREATE','Per-school audit log retention (R-CMP-006)'),
  ('A-037','settings','email_template table created','20260717000004_wave_23_04_settings_tables','email_template','CREATE','Per-school email templates with locale+active flag'),
  ('A-038','reports','report_definition table created','20260717000005_wave_23_05_reports_tables','report_definition','CREATE','Saved report templates with schedule_cron'),
  ('A-039','reports','report_execution table created','20260717000005_wave_23_05_reports_tables','report_execution','CREATE','Individual report runs with status workflow'),
  ('A-040','reports','report_subscription table created','20260717000005_wave_23_05_reports_tables','report_subscription','CREATE','Recurring report subscriptions with next_run_at index'),
  ('A-041','reports','report_favorite table created','20260717000005_wave_23_05_reports_tables','report_favorite','CREATE','User favorites for quick access'),
  ('A-042','reports','report_share table created','20260717000005_wave_23_05_reports_tables','report_share','CREATE','Explicit shares with users/roles + permissions array'),
  ('A-043','administration','asset table created','20260717000006_wave_23_06_administration_tables','asset','CREATE','Physical assets with depreciation+condition+status'),
  ('A-044','administration','asset_category table created','20260717000006_wave_23_06_administration_tables','asset_category','CREATE','Asset classification with parent_id self-reference'),
  ('A-045','administration','asset_maintenance table created','20260717000006_wave_23_06_administration_tables','asset_maintenance','CREATE','Asset maintenance records with maintenance_type CHECK'),
  ('A-046','administration','visitor table created','20260717000006_wave_23_06_administration_tables','visitor','CREATE','Visitor check-in/out with purpose CHECK'),
  ('A-047','administration','cctv_camera table created','20260717000006_wave_23_06_administration_tables','cctv_camera','CREATE','CCTV cameras with online state + heartbeat'),
  ('A-048','administration','cctv_alert table created','20260717000006_wave_23_06_administration_tables','cctv_alert','CREATE','CCTV alerts with severity CHECK'),
  ('A-049','administration','gate_pass table created','20260717000006_wave_23_06_administration_tables','gate_pass','CREATE','Gate passes with pass_type CHECK'),
  ('A-050','administration','security_incident table created','20260717000006_wave_23_06_administration_tables','security_incident','CREATE','Security incidents with status workflow'),
  ('A-051','administration','emergency_contact table created','20260717000006_wave_23_06_administration_tables','emergency_contact','CREATE','Emergency contacts with is_primary flag'),
  ('A-052','administration','emergency_drill table created','20260717000006_wave_23_06_administration_tables','emergency_drill','CREATE','Emergency drill records (R-CMP-013 quarterly fire drill)'),
  ('A-053','administration','emergency_alert table created','20260717000006_wave_23_06_administration_tables','emergency_alert','CREATE','Emergency alert broadcasts with channels array'),
  ('A-054','administration','contact_directory table created','20260717000006_wave_23_06_administration_tables','contact_directory','CREATE','External contact directory with is_verified flag'),
  ('A-055','administration','maintenance_request table created','20260717000006_wave_23_06_administration_tables','maintenance_request','CREATE','Maintenance requests with priority+status'),
  ('A-056','administration','vendor_visit table created','20260717000006_wave_23_06_administration_tables','vendor_visit','CREATE','Vendor visit logs'),
  ('A-057','administration','document_vault table created','20260717000006_wave_23_06_administration_tables','document_vault','CREATE','Document vault with is_confidential flag'),
  ('A-058','administration','document_share table created','20260717000006_wave_23_06_administration_tables','document_share','CREATE','Document shares with permissions array'),
  ('A-059','administration','insurance_policy table created','20260717000006_wave_23_06_administration_tables','insurance_policy','CREATE','Insurance policies with coverage_cents+premium_cents'),
  ('A-060','administration','license_permit table created','20260717000006_wave_23_06_administration_tables','license_permit','CREATE','Licenses and permits with renewal_date'),
  ('A-061','administration','audit_finding table created','20260717000006_wave_23_06_administration_tables','audit_finding','CREATE','Audit findings with severity+status'),
  ('A-062','administration','audit_action table created','20260717000006_wave_23_06_administration_tables','audit_action','CREATE','Audit remediation actions with due_date'),
  ('A-063','transport','vehicle table created','20260717000007_wave_23_07_transport_tables','vehicle','CREATE','Vehicles with capacity+fuel_type+insurance/fitness expiry'),
  ('A-064','transport','driver table created','20260717000007_wave_23_07_transport_tables','driver','CREATE','Drivers with license_expiry+background_verified'),
  ('A-065','transport','route table created','20260717000007_wave_23_07_transport_tables','route','CREATE','Routes with vehicle+driver assignment + departure/arrival time'),
  ('A-066','transport','route_stop table created','20260717000007_wave_23_07_transport_tables','route_stop','CREATE','Route stops with sequence_order+pickup/drop time'),
  ('A-067','transport','student_route_assignment table created','20260717000007_wave_23_07_transport_tables','student_route_assignment','CREATE','Student-to-route assignments with effective_from/until'),
  ('A-068','transport','trip table created','20260717000007_wave_23_07_transport_tables','trip','CREATE','Daily trip records with status workflow'),
  ('A-069','transport','trip_attendance table created','20260717000007_wave_23_07_transport_tables','trip_attendance','CREATE','Per-student per-trip pickup/drop logs'),
  ('A-070','transport','fuel_log table created','20260717000007_wave_23_07_transport_tables','fuel_log','CREATE','Vehicle fuel entries with odometer reading'),
  ('A-071','transport','vehicle_maintenance table created','20260717000007_wave_23_07_transport_tables','vehicle_maintenance','CREATE','Vehicle maintenance records with next_service_date'),
  ('A-072','transport','transport_fee table created','20260717000007_wave_23_07_transport_tables','transport_fee','CREATE','Transport fee schedule per route'),
  ('A-073','transport','transport_fee_payment table created','20260717000007_wave_23_07_transport_tables','transport_fee_payment','CREATE','Transport fee payment records'),
  ('A-074','transport','gps_device table created','20260717000007_wave_23_07_transport_tables','gps_device','CREATE','GPS devices with last_ping_at+lat/long/speed'),
  ('A-075','transport','transport_incident table created','20260717000007_wave_23_07_transport_tables','transport_incident','CREATE','Transport incidents with severity+status'),
  ('A-076','acceptance','acceptance_test_registry table created','20260717000008_wave_23_08_acceptance_seed','acceptance_test_registry','CREATE','Acceptance test ID registry with test_id UNIQUE'),
  ('A-077','acceptance','migration_audit table created','20260717000008_wave_23_08_acceptance_seed','migration_audit','CREATE','Applied migration audit log with checksum'),
  ('A-078','acceptance','75 acceptance test IDs seeded','20260717000008_wave_23_08_acceptance_seed','acceptance_test_registry','CREATE','75 rows inserted covering A-001..A-075'),
  ('A-079','acceptance','migration_audit unique on migration_id','20260717000008_wave_23_08_acceptance_seed','migration_audit','CREATE','Migration audit log enforces one row per migration'),
  ('A-080','acceptance','acceptance_test_registry index by migration_id','20260717000008_wave_23_08_acceptance_seed','acceptance_test_registry','CREATE','Index on (migration_id) for fast lookups'),
  ('A-081','acceptance','acceptance_test_registry index by category','20260717000008_wave_23_08_acceptance_seed','acceptance_test_registry','CREATE','Index on (test_category) for category queries'),
  ('A-082','conventions','all migrations idempotent','ALL','ALL','CREATE','Every CREATE statement uses IF NOT EXISTS'),
  ('A-083','conventions','all tenant tables have RLS','ALL','ALL','CREATE','Every table with school_id has ENABLE ROW LEVEL SECURITY + a tenant policy'),
  ('A-084','conventions','all mutable tenant tables have updated_at trigger','ALL','ALL','CREATE','Every mutable tenant table has a trg_*_updated_at trigger calling update_updated_at_column()'),
  ('A-085','conventions','all money columns use _cents suffix','ALL','ALL','CREATE','No float money columns — every amount column is BIGINT with _cents suffix'),
  ('A-086','conventions','all PKs use UUID v7 default','ALL','ALL','CREATE','Every table uses UUID PRIMARY KEY DEFAULT uuid_v7()'),
  ('A-087','conventions','all migrations have header comments','ALL','ALL','CREATE','Every migration file begins with a header block documenting ID, Wave, idempotency, conventions')
ON CONFLICT (test_id) DO NOTHING;

-- ───────────────────────────────────────────────────────────────────────
-- Add a comment documenting the acceptance test ID range
-- ───────────────────────────────────────────────────────────────────────
COMMENT ON TABLE acceptance_test_registry IS
  'Wave 23 — Registry of acceptance test IDs (A-001..A-087). Authoritative list is in test/unit/migrations/wave-23-acceptance.spec.ts. This table holds the seed entries for observability; the spec file is the source of truth for the test runner.';

COMMENT ON TABLE migration_audit IS
  'Wave 23 — Per-migration audit log. Tracks applied_at, checksum, duration, outcome. Replaces _prisma_migrations for app-level observability.';

