-- PreOne Wave 23.07 — Transport tables
-- =====================================================================
-- Migration ID: 20260717000007_wave_23_07_transport_tables
-- Wave: 23
-- Idempotent: YES (uses CREATE TYPE/TABLE IF NOT EXISTS, DROP IF EXISTS)
--
-- Creates 13 transport tables:
  vehicle, driver, route, route_stop, student_route_assignment,
  trip, trip_attendance, fuel_log, vehicle_maintenance,
  transport_fee, transport_fee_payment, gps_device,
  transport_incident.
--
-- Conventions (per ERD v3.0 §3 + BTD §16):
--   - Tables: snake_case plural
--   - Columns: snake_case
--   - PKs: UUID v7 (time-sortable)
--   - Timestamps: timestamptz
--   - Money: integer cents (amount_cents) — never float
--   - Soft delete: deleted_at timestamptz NULL
--   - Optimistic concurrency: version INTEGER DEFAULT 1
--   - Tenant isolation: school_id discriminator + RLS policy
--   - Audit columns: created_at, created_by, updated_at, updated_by,
--                    deleted_at, deleted_by
--
-- This migration is auto-generated by scripts/wave23_migrations_gen.py.
-- Do not edit by hand — re-run the script instead.

-- ───────────────────────────────────────────────────────────────────────
-- 1. vehicle — school transport vehicles
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS vehicle (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    registration_number VARCHAR(32) NOT NULL,
    vehicle_type    VARCHAR(40) NOT NULL CHECK (vehicle_type IN ('BUS','VAN','CAR','AUTO')),
    capacity        INTEGER NOT NULL CHECK (capacity > 0),
    make            VARCHAR(64),
    model           VARCHAR(64),
    year_of_manufacture SMALLINT,
    fuel_type       VARCHAR(20) DEFAULT 'DIESEL'
                    CHECK (fuel_type IN ('PETROL','DIESEL','CNG','ELECTRIC','HYBRID')),
    insurance_number VARCHAR(120),
    insurance_expiry DATE,
    fitness_certificate_expiry DATE,
    pollution_certificate_expiry DATE,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    metadata        JSONB,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    deleted_at      TIMESTAMPTZ,
    UNIQUE (branch_id, registration_number)
);

-- ───────────────────────────────────────────────────────────────────────
-- 2. driver — transport drivers
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS driver (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    employee_id     UUID,
    full_name       VARCHAR(255) NOT NULL,
    license_number  VARCHAR(64) NOT NULL,
    license_expiry  DATE NOT NULL,
    phone           VARCHAR(20) NOT NULL,
    address         TEXT,
    date_of_birth   DATE,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    background_verified BOOLEAN NOT NULL DEFAULT FALSE,
    background_verified_at DATE,
    photo_url       VARCHAR(512),
    metadata        JSONB,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    deleted_at      TIMESTAMPTZ,
    UNIQUE (branch_id, license_number)
);

-- ───────────────────────────────────────────────────────────────────────
-- 3. route — transport routes
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS route (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    route_code      VARCHAR(32) NOT NULL,
    route_name      VARCHAR(255) NOT NULL,
    route_type      VARCHAR(20) DEFAULT 'MORNING'
                    CHECK (route_type IN ('MORNING','AFTERNOON','EVENING','BOTH')),
    vehicle_id      UUID NOT NULL REFERENCES vehicle(id) ON DELETE RESTRICT,
    driver_id       UUID NOT NULL REFERENCES driver(id) ON DELETE RESTRICT,
    attendant_id    UUID REFERENCES users(id) ON DELETE SET NULL,
    start_location  VARCHAR(255) NOT NULL,
    end_location    VARCHAR(255) NOT NULL,
    departure_time  TIME NOT NULL,
    arrival_time    TIME NOT NULL,
    distance_km     NUMERIC(8, 2),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    metadata        JSONB,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    deleted_at      TIMESTAMPTZ,
    UNIQUE (branch_id, route_code)
);

-- ───────────────────────────────────────────────────────────────────────
-- 4. route_stop — pickup/drop points on a route
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS route_stop (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    route_id        UUID NOT NULL REFERENCES route(id) ON DELETE CASCADE,
    stop_name       VARCHAR(255) NOT NULL,
    stop_code       VARCHAR(32),
    address         TEXT NOT NULL,
    latitude        DOUBLE PRECISION,
    longitude       DOUBLE PRECISION,
    pickup_time     TIME,
    drop_time       TIME,
    sequence_order  SMALLINT NOT NULL,
    distance_from_school_km NUMERIC(8, 2),
    fare_cents      BIGINT DEFAULT 0,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ,
    UNIQUE (route_id, sequence_order)
);

-- ───────────────────────────────────────────────────────────────────────
-- 5. student_route_assignment — students assigned to routes/stops
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS student_route_assignment (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    student_id      UUID NOT NULL,
    route_id        UUID NOT NULL REFERENCES route(id) ON DELETE CASCADE,
    route_stop_id   UUID NOT NULL REFERENCES route_stop(id) ON DELETE CASCADE,
    assignment_type VARCHAR(20) DEFAULT 'BOTH'
                    CHECK (assignment_type IN ('PICKUP','DROP','BOTH')),
    effective_from  DATE NOT NULL,
    effective_until DATE,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS student_route_assignment_student_idx
    ON student_route_assignment(student_id, is_active);

-- ───────────────────────────────────────────────────────────────────────
-- 6. trip — individual daily trip records
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS trip (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    route_id        UUID NOT NULL REFERENCES route(id) ON DELETE RESTRICT,
    vehicle_id      UUID NOT NULL REFERENCES vehicle(id) ON DELETE RESTRICT,
    driver_id       UUID NOT NULL REFERENCES driver(id) ON DELETE RESTRICT,
    trip_date       DATE NOT NULL,
    trip_type       VARCHAR(20) NOT NULL CHECK (trip_type IN ('MORNING','AFTERNOON','EVENING')),
    scheduled_departure TIMESTAMPTZ NOT NULL,
    actual_departure    TIMESTAMPTZ,
    scheduled_arrival   TIMESTAMPTZ NOT NULL,
    actual_arrival      TIMESTAMPTZ,
    students_onboard    INTEGER DEFAULT 0,
    odometer_start      INTEGER,
    odometer_end        INTEGER,
    status          VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED'
                    CHECK (status IN ('SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED','DELAYED')),
    notes           TEXT,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS trip_route_date_idx
    ON trip(route_id, trip_date DESC);

-- ───────────────────────────────────────────────────────────────────────
-- 7. trip_attendance — student pickup/drop logs per trip
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS trip_attendance (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    trip_id         UUID NOT NULL REFERENCES trip(id) ON DELETE CASCADE,
    student_id      UUID NOT NULL,
    route_stop_id   UUID REFERENCES route_stop(id) ON DELETE SET NULL,
    pickup_status   VARCHAR(20) CHECK (pickup_status IN ('PICKED_UP','MISSED','ABSENT')),
    pickup_time     TIMESTAMPTZ,
    drop_status     VARCHAR(20) CHECK (drop_status IN ('DROPPED','MISSED','HANDED_TO_GUARDIAN')),
    drop_time       TIMESTAMPTZ,
    notes           TEXT,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (trip_id, student_id)
);

-- ───────────────────────────────────────────────────────────────────────
-- 8. fuel_log — vehicle fuel entries
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS fuel_log (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    vehicle_id      UUID NOT NULL REFERENCES vehicle(id) ON DELETE CASCADE,
    fuel_date       DATE NOT NULL,
    fuel_type       VARCHAR(20) NOT NULL,
    quantity_litres NUMERIC(8, 2) NOT NULL CHECK (quantity_litres > 0),
    amount_cents    BIGINT NOT NULL CHECK (amount_cents >= 0),
    odometer_reading INTEGER NOT NULL,
    fuel_station    VARCHAR(255),
    filled_by       UUID REFERENCES users(id) ON DELETE SET NULL,
    receipt_url     VARCHAR(512),
    notes           TEXT,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS fuel_log_vehicle_date_idx
    ON fuel_log(vehicle_id, fuel_date DESC);

-- ───────────────────────────────────────────────────────────────────────
-- 9. vehicle_maintenance — vehicle service records
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS vehicle_maintenance (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    vehicle_id      UUID NOT NULL REFERENCES vehicle(id) ON DELETE CASCADE,
    maintenance_type VARCHAR(32) NOT NULL CHECK (maintenance_type IN (
                    'SERVICE','REPAIR','INSPECTION','TYRE_REPLACEMENT','OTHER')),
    service_date    DATE NOT NULL,
    odometer_reading INTEGER,
    description     TEXT,
    cost_cents      BIGINT DEFAULT 0,
    vendor          VARCHAR(255),
    invoice_number  VARCHAR(120),
    next_service_date DATE,
    next_service_odometer INTEGER,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    deleted_at      TIMESTAMPTZ
);

-- ───────────────────────────────────────────────────────────────────────
-- 10-13: transport_fee, transport_fee_payment, gps_device, transport_incident
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS transport_fee (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    route_id        UUID NOT NULL REFERENCES route(id) ON DELETE CASCADE,
    fee_term        VARCHAR(20) NOT NULL,  -- 'QUARTERLY', 'YEARLY', 'MONTHLY'
    amount_cents    BIGINT NOT NULL CHECK (amount_cents >= 0),
    effective_from  DATE NOT NULL,
    effective_until DATE,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS transport_fee_payment (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    student_id      UUID NOT NULL,
    transport_fee_id UUID NOT NULL REFERENCES transport_fee(id) ON DELETE RESTRICT,
    amount_cents    BIGINT NOT NULL CHECK (amount_cents >= 0),
    payment_date    DATE NOT NULL,
    payment_mode    VARCHAR(20) NOT NULL,
    transaction_ref VARCHAR(120),
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                    CHECK (status IN ('PENDING','COMPLETED','FAILED','REFUNDED')),
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS gps_device (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    device_id       VARCHAR(64) NOT NULL,
    vehicle_id      UUID REFERENCES vehicle(id) ON DELETE SET NULL,
    sim_number      VARCHAR(20),
    is_online       BOOLEAN NOT NULL DEFAULT FALSE,
    last_ping_at    TIMESTAMPTZ,
    last_latitude   DOUBLE PRECISION,
    last_longitude  DOUBLE PRECISION,
    last_speed_kmph NUMERIC(6, 2),
    metadata        JSONB,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ,
    UNIQUE (branch_id, device_id)
);

CREATE TABLE IF NOT EXISTS transport_incident (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    trip_id         UUID REFERENCES trip(id) ON DELETE SET NULL,
    vehicle_id      UUID REFERENCES vehicle(id) ON DELETE SET NULL,
    driver_id       UUID REFERENCES driver(id) ON DELETE SET NULL,
    incident_type   VARCHAR(40) NOT NULL,
    severity        VARCHAR(10) NOT NULL CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    occurred_at     TIMESTAMPTZ NOT NULL,
    reported_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reported_by     UUID REFERENCES users(id) ON DELETE SET NULL,
    description     TEXT NOT NULL,
    location        VARCHAR(255),
    latitude        DOUBLE PRECISION,
    longitude       DOUBLE PRECISION,
    status          VARCHAR(20) NOT NULL DEFAULT 'OPEN'
                    CHECK (status IN ('OPEN','INVESTIGATING','RESOLVED','CLOSED')),
    resolution      TEXT,
    resolved_at     TIMESTAMPTZ,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ───────────────────────────────────────────────────────────────────────
-- RLS + triggers
-- ───────────────────────────────────────────────────────────────────────
ALTER TABLE vehicle                    ENABLE ROW LEVEL SECURITY;
ALTER TABLE driver                     ENABLE ROW LEVEL SECURITY;
ALTER TABLE route                      ENABLE ROW LEVEL SECURITY;
ALTER TABLE route_stop                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_route_assignment   ENABLE ROW LEVEL SECURITY;
ALTER TABLE trip                       ENABLE ROW LEVEL SECURITY;
ALTER TABLE trip_attendance            ENABLE ROW LEVEL SECURITY;
ALTER TABLE fuel_log                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicle_maintenance        ENABLE ROW LEVEL SECURITY;
ALTER TABLE transport_fee              ENABLE ROW LEVEL SECURITY;
ALTER TABLE transport_fee_payment      ENABLE ROW LEVEL SECURITY;
ALTER TABLE gps_device                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE transport_incident         ENABLE ROW LEVEL SECURITY;

CREATE POLICY vehicle_tenant                  ON vehicle                  USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY driver_tenant                   ON driver                   USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY route_tenant                    ON route                    USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY route_stop_tenant               ON route_stop               USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY student_route_assignment_tenant ON student_route_assignment USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY trip_tenant                     ON trip                     USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY trip_attendance_tenant          ON trip_attendance          USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY fuel_log_tenant                 ON fuel_log                 USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY vehicle_maintenance_tenant      ON vehicle_maintenance      USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY transport_fee_tenant            ON transport_fee            USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY transport_fee_payment_tenant    ON transport_fee_payment    USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY gps_device_tenant               ON gps_device               USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY transport_incident_tenant       ON transport_incident       USING (school_id = current_setting('app.current_school_id', true)::uuid);

DO $$
DECLARE t TEXT;
BEGIN
    FOR t IN SELECT unnest(ARRAY[
        'vehicle','driver','route','route_stop','student_route_assignment',
        'trip','trip_attendance','fuel_log','vehicle_maintenance',
        'transport_fee','transport_fee_payment','gps_device','transport_incident'
    ])
    LOOP
        EXECUTE format(
            'DROP TRIGGER IF EXISTS trg_%I_updated_at ON %I; '
            'CREATE TRIGGER trg_%I_updated_at BEFORE UPDATE ON %I '
            'FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();',
            t, t, t, t
        );
    END LOOP;
END $$;

