-- PreOne Wave 23.05 — Reports tables
-- =====================================================================
-- Migration ID: 20260717000005_wave_23_05_reports_tables
-- Wave: 23
-- Idempotent: YES (uses CREATE TYPE/TABLE IF NOT EXISTS, DROP IF EXISTS)
--
-- Creates 5 reports tables:
  report_definition, report_execution, report_subscription,
  report_favorite, report_share.
--
-- Conventions (per ERD v3.0 §3 + BTD §16):
--   - Tables: snake_case plural
--   - Columns: snake_case
--   - PKs: UUID v7 (time-sortable)
--   - Timestamps: timestamptz
--   - Money: integer cents (amount_cents) — never float
--   - Soft delete: deleted_at timestamptz NULL
--   - Optimistic concurrency: version INTEGER DEFAULT 1
--   - Tenant isolation: school_id discriminator + RLS policy
--   - Audit columns: created_at, created_by, updated_at, updated_by,
--                    deleted_at, deleted_by
--
-- This migration is auto-generated by scripts/wave23_migrations_gen.py.
-- Do not edit by hand — re-run the script instead.

-- ───────────────────────────────────────────────────────────────────────
-- 1. report_definition — saved report templates
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS report_definition (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    report_key      VARCHAR(96) NOT NULL,
    title           VARCHAR(255) NOT NULL,
    description     TEXT,
    category        VARCHAR(64) NOT NULL,
    data_source     VARCHAR(64) NOT NULL,
    query_template  TEXT NOT NULL,
    parameters_schema JSONB,
    schedule_cron   VARCHAR(64),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    deleted_at      TIMESTAMPTZ,
    UNIQUE (school_id, report_key)
);

-- ───────────────────────────────────────────────────────────────────────
-- 2. report_execution — individual report runs
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS report_execution (
    id                  UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id           UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    report_definition_id UUID NOT NULL REFERENCES report_definition(id) ON DELETE CASCADE,
    triggered_by        UUID REFERENCES users(id) ON DELETE SET NULL,
    parameters          JSONB NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                        CHECK (status IN ('PENDING','RUNNING','COMPLETED','FAILED','CANCELLED')),
    result_url          VARCHAR(512),
    result_summary      JSONB,
    row_count           INTEGER,
    bytes               BIGINT,
    started_at          TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    duration_ms         INTEGER,
    error_message       TEXT,
    version             INTEGER NOT NULL DEFAULT 1,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS report_execution_def_status_idx
    ON report_execution(report_definition_id, status, created_at DESC);

-- ───────────────────────────────────────────────────────────────────────
-- 3. report_subscription — recurring report subscriptions for users
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS report_subscription (
    id                  UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id           UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    report_definition_id UUID NOT NULL REFERENCES report_definition(id) ON DELETE CASCADE,
    user_id             UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    schedule_cron       VARCHAR(64) NOT NULL,
    parameters          JSONB,
    delivery_channels   TEXT[] NOT NULL DEFAULT ARRAY['EMAIL'],
    next_run_at         TIMESTAMPTZ NOT NULL,
    last_run_at         TIMESTAMPTZ,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    version             INTEGER NOT NULL DEFAULT 1,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at          TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS report_subscription_next_run_idx
    ON report_subscription(next_run_at) WHERE is_active = TRUE;

-- ───────────────────────────────────────────────────────────────────────
-- 4. report_favorite — user favorites for quick access
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS report_favorite (
    id                  UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id           UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    user_id             UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    report_definition_id UUID NOT NULL REFERENCES report_definition(id) ON DELETE CASCADE,
    display_order       SMALLINT NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, report_definition_id)
);

-- ───────────────────────────────────────────────────────────────────────
-- 5. report_share — explicit shares with users/roles
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS report_share (
    id                  UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id           UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    report_definition_id UUID NOT NULL REFERENCES report_definition(id) ON DELETE CASCADE,
    shared_by           UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    shared_with_user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    shared_with_role_id UUID,
    permissions         TEXT[] NOT NULL DEFAULT ARRAY['VIEW'],
    message             TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (shared_with_user_id IS NOT NULL OR shared_with_role_id IS NOT NULL)
);

-- ───────────────────────────────────────────────────────────────────────
-- RLS + triggers
-- ───────────────────────────────────────────────────────────────────────
ALTER TABLE report_definition  ENABLE ROW LEVEL SECURITY;
ALTER TABLE report_execution   ENABLE ROW LEVEL SECURITY;
ALTER TABLE report_subscription ENABLE ROW LEVEL SECURITY;
ALTER TABLE report_favorite    ENABLE ROW LEVEL SECURITY;
ALTER TABLE report_share       ENABLE ROW LEVEL SECURITY;

CREATE POLICY report_definition_tenant   ON report_definition   USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY report_execution_tenant    ON report_execution    USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY report_subscription_tenant ON report_subscription USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY report_favorite_tenant     ON report_favorite     USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY report_share_tenant        ON report_share        USING (school_id = current_setting('app.current_school_id', true)::uuid);

DO $$
DECLARE t TEXT;
BEGIN
    FOR t IN SELECT unnest(ARRAY[
        'report_definition','report_execution','report_subscription'
    ])
    LOOP
        EXECUTE format(
            'DROP TRIGGER IF EXISTS trg_%I_updated_at ON %I; '
            'CREATE TRIGGER trg_%I_updated_at BEFORE UPDATE ON %I '
            'FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();',
            t, t, t, t
        );
    END LOOP;
END $$;

