/**
 * BRC v1.0 traceability declarations — Wave 22.
 *
 * This file is the single source of truth for "which catalog rule is enforced
 * where" across the codebase. It is imported by brc-traceability.spec.ts so
 * the registry is populated before assertions run.
 *
 * Adding a new rule enforcement is a one-line change here.
 *
 * Format: each call registers one (ruleId -> file/target) trace entry.
 * The test asserts:
 *   - every referenced ruleId exists in the catalog
 *   - >= 126 distinct ruleIds are referenced
 *   - every catalog rule is either referenced here OR explicitly deferred in
 *     the spec
 */

import { enforceRuleInTest } from '../../../src/common/brc/brc-trace.decorator';

// Anchor each declaration to its enforcing source file so reviewers can
// cross-reference quickly. `kind` mirrors the BrcTraceKind union.
const DECLARATIONS: ReadonlyArray<{ ruleId: string; file: string; target: string; kind: string }> = [
  { ruleId: 'R-ELG-001', file: 'admissions/domain/aggregates/application.aggregate.ts', target: 'ApplicationAggregate.assertAgeEligibility', kind: 'aggregate' },
  { ruleId: 'R-ELG-002', file: 'admissions/domain/aggregates/application.aggregate.ts', target: 'ApplicationAggregate.assertAgeEligibility', kind: 'aggregate' },
  { ruleId: 'R-ELG-003', file: 'admissions/domain/aggregates/application.aggregate.ts', target: 'ApplicationAggregate.assertAgeEligibility', kind: 'aggregate' },
  { ruleId: 'R-ELG-004', file: 'admissions/domain/aggregates/application.aggregate.ts', target: 'ApplicationAggregate.assertAgeEligibility', kind: 'aggregate' },
  { ruleId: 'R-ELG-005', file: 'admissions/domain/aggregates/application.aggregate.ts', target: 'ApplicationAggregate.assertAgeEligibility', kind: 'aggregate' },
  { ruleId: 'R-ELG-006', file: 'admissions/domain/aggregates/application.aggregate.ts', target: 'ApplicationAggregate.assertDocumentsComplete', kind: 'aggregate' },
  { ruleId: 'R-ELG-007', file: 'admissions/domain/aggregates/application.aggregate.ts', target: 'ApplicationAggregate.assertMedicalFitness', kind: 'aggregate' },
  { ruleId: 'R-ELG-008', file: 'admissions/domain/aggregates/application.aggregate.ts', target: 'ApplicationAggregate.assertDocumentsComplete', kind: 'aggregate' },
  { ruleId: 'R-ELG-009', file: 'admissions/domain/aggregates/application.aggregate.ts', target: 'ApplicationAggregate.assertDocumentsComplete', kind: 'aggregate' },
  { ruleId: 'R-ELG-010', file: 'admissions/domain/aggregates/application.aggregate.ts', target: 'ApplicationAggregate.assertPrimaryContact', kind: 'aggregate' },
  { ruleId: 'R-ELG-011', file: 'admissions/domain/aggregates/admission.aggregate.ts', target: 'AdmissionAggregate.applySiblingPriority', kind: 'aggregate' },
  { ruleId: 'R-ELG-012', file: 'admissions/domain/aggregates/admission.aggregate.ts', target: 'AdmissionAggregate.applyStaffWardQuota', kind: 'aggregate' },
  { ruleId: 'R-ELG-013', file: 'admissions/domain/aggregates/application.aggregate.ts', target: 'ApplicationAggregate.assertTransferEligibility', kind: 'aggregate' },
  { ruleId: 'R-ELG-014', file: 'admissions/domain/aggregates/admission.aggregate.ts', target: 'AdmissionAggregate.applyRteQuota', kind: 'aggregate' },
  { ruleId: 'R-ELG-015', file: 'admissions/domain/aggregates/application.aggregate.ts', target: 'ApplicationAggregate.assertSpecialNeedsSupport', kind: 'aggregate' },
  { ruleId: 'R-FIN-001', file: 'finance/domain/aggregates/invoice.aggregate.ts', target: 'InvoiceAggregate.markOverdue/applyLateFee', kind: 'aggregate' },
  { ruleId: 'R-FIN-002', file: 'finance/domain/aggregates/invoice.aggregate.ts', target: 'InvoiceAggregate.markOverdue/applyLateFee', kind: 'aggregate' },
  { ruleId: 'R-FIN-003', file: 'finance/domain/aggregates/refund.aggregate.ts', target: 'RefundAggregate.processRefund', kind: 'aggregate' },
  { ruleId: 'R-FIN-004', file: 'finance/domain/aggregates/refund.aggregate.ts', target: 'RefundAggregate.processRefund', kind: 'aggregate' },
  { ruleId: 'R-FIN-005', file: 'finance/domain/aggregates/invoice.aggregate.ts', target: 'InvoiceAggregate.applyDiscount', kind: 'aggregate' },
  { ruleId: 'R-FIN-006', file: 'finance/domain/aggregates/invoice.aggregate.ts', target: 'InvoiceAggregate.applyDiscount', kind: 'aggregate' },
  { ruleId: 'R-FIN-007', file: 'finance/domain/aggregates/invoice.aggregate.ts', target: 'InvoiceAggregate.computeGst', kind: 'aggregate' },
  { ruleId: 'R-FIN-008', file: 'finance/domain/aggregates/invoice.aggregate.ts', target: 'InvoiceAggregate.generateInvoiceNumber', kind: 'aggregate' },
  { ruleId: 'R-FIN-009', file: 'finance/domain/aggregates/payment.aggregate.ts', target: 'PaymentAggregate.generateReceipt', kind: 'aggregate' },
  { ruleId: 'R-FIN-010', file: 'finance/domain/aggregates/payment.aggregate.ts', target: 'PaymentAggregate.validatePaymentMode', kind: 'aggregate' },
  { ruleId: 'R-FIN-011', file: 'finance/domain/aggregates/payment.aggregate.ts', target: 'PaymentAggregate.validatePaymentMode', kind: 'aggregate' },
  { ruleId: 'R-FIN-012', file: 'finance/domain/aggregates/fee-plan.aggregate.ts', target: 'FeePlanAggregate.approveInstallmentPlan', kind: 'aggregate' },
  { ruleId: 'R-FIN-013', file: 'finance/domain/aggregates/fee-plan.aggregate.ts', target: 'FeePlanAggregate.applyScholarship', kind: 'aggregate' },
  { ruleId: 'R-FIN-014', file: 'finance/domain/aggregates/invoice.aggregate.ts', target: 'InvoiceAggregate.writeOffBadDebt', kind: 'aggregate' },
  { ruleId: 'R-FIN-015', file: 'finance/application/services/finance.service.ts', target: 'FinanceService.approveExpense', kind: 'service' },
  { ruleId: 'R-FIN-016', file: 'finance/domain/aggregates/payment.aggregate.ts', target: 'PaymentAggregate.processVendorPayment', kind: 'aggregate' },
  { ruleId: 'R-FIN-017', file: 'finance/domain/aggregates/payment.aggregate.ts', target: 'PaymentAggregate.processVendorPayment', kind: 'aggregate' },
  { ruleId: 'R-FIN-018', file: 'finance/domain/aggregates/fee-plan.aggregate.ts', target: 'FeePlanAggregate.applyHardshipWaiver', kind: 'aggregate' },
  { ruleId: 'R-FIN-019', file: 'finance/domain/aggregates/refund.aggregate.ts', target: 'RefundAggregate.claimRteReimbursement', kind: 'aggregate' },
  { ruleId: 'R-FIN-020', file: 'finance/domain/aggregates/invoice.aggregate.ts', target: 'InvoiceAggregate', kind: 'aggregate' },
  { ruleId: 'R-OPS-001', file: 'attendance/domain/aggregates/daily-log.aggregate.ts', target: 'DailyLogAggregate.assertAuthorizedPickup', kind: 'aggregate' },
  { ruleId: 'R-OPS-002', file: 'attendance/domain/aggregates/daily-log.aggregate.ts', target: 'DailyLogAggregate.assertAuthorizedPickup', kind: 'aggregate' },
  { ruleId: 'R-OPS-003', file: 'attendance/domain/aggregates/daily-log.aggregate.ts', target: 'DailyLogAggregate.assertAuthorizedPickup', kind: 'aggregate' },
  { ruleId: 'R-OPS-004', file: 'attendance/domain/aggregates/attendance.aggregate.ts', target: 'AttendanceAggregate.markAttendance', kind: 'aggregate' },
  { ruleId: 'R-OPS-005', file: 'attendance/domain/aggregates/attendance.aggregate.ts', target: 'AttendanceAggregate.markAttendance', kind: 'aggregate' },
  { ruleId: 'R-OPS-006', file: 'attendance/domain/aggregates/attendance.aggregate.ts', target: 'AttendanceAggregate.markAttendance', kind: 'aggregate' },
  { ruleId: 'R-OPS-007', file: 'attendance/domain/aggregates/daily-log.aggregate.ts', target: 'DailyLogAggregate.issueGatePass', kind: 'aggregate' },
  { ruleId: 'R-OPS-008', file: 'administration/domain/aggregates/visitor-log.aggregate.ts', target: 'VisitorLogAggregate.logVisitor', kind: 'aggregate' },
  { ruleId: 'R-OPS-009', file: 'transport/domain/aggregates/trip.aggregate.ts', target: 'TripAggregate.trackBus', kind: 'aggregate' },
  { ruleId: 'R-OPS-010', file: 'transport/domain/aggregates/trip.aggregate.ts', target: 'TripAggregate.trackBus', kind: 'aggregate' },
  { ruleId: 'R-OPS-011', file: 'transport/domain/aggregates/trip.aggregate.ts', target: 'TripAggregate.trackBus', kind: 'aggregate' },
  { ruleId: 'R-OPS-012', file: 'attendance/domain/aggregates/daily-log.aggregate.ts', target: 'DailyLogAggregate.performHealthCheck', kind: 'aggregate' },
  { ruleId: 'R-OPS-013', file: 'attendance/domain/aggregates/daily-log.aggregate.ts', target: 'DailyLogAggregate.performHealthCheck', kind: 'aggregate' },
  { ruleId: 'R-OPS-014', file: 'attendance/domain/aggregates/daily-log.aggregate.ts', target: 'DailyLogAggregate.recordNapTime', kind: 'aggregate' },
  { ruleId: 'R-OPS-015', file: 'attendance/domain/aggregates/incident-report.aggregate.ts', target: 'IncidentReportAggregate.escalateIncident', kind: 'aggregate' },
  { ruleId: 'R-OPS-016', file: 'communication/domain/aggregates/announcement.aggregate.ts', target: 'AnnouncementAggregate.assertPhotoConsent', kind: 'aggregate' },
  { ruleId: 'R-OPS-017', file: 'attendance/domain/aggregates/daily-report.aggregate.ts', target: 'DailyReportAggregate.pushTimeline', kind: 'aggregate' },
  { ruleId: 'R-OPS-018', file: 'administration/domain/aggregates/food-sample-retention.aggregate.ts', target: 'FoodSampleRetentionAggregate.retainSample', kind: 'aggregate' },
  { ruleId: 'R-OPS-019', file: 'attendance/domain/aggregates/daily-log.aggregate.ts', target: 'DailyLogAggregate.recordNapTime', kind: 'aggregate' },
  { ruleId: 'R-OPS-020', file: 'administration/domain/aggregates/cctv-coverage.aggregate.ts', target: 'CctvCoverageAggregate.assertRetention', kind: 'aggregate' },
  { ruleId: 'R-ACD-001', file: 'academics/domain/aggregates/curriculum.aggregate.ts', target: 'CurriculumAggregate.rotateTheme', kind: 'aggregate' },
  { ruleId: 'R-ACD-002', file: 'academics/domain/aggregates/curriculum.aggregate.ts', target: 'CurriculumAggregate.submitLessonPlan', kind: 'aggregate' },
  { ruleId: 'R-ACD-003', file: 'academics/domain/aggregates/observation.aggregate.ts', target: 'ObservationAggregate.recordActivity', kind: 'aggregate' },
  { ruleId: 'R-ACD-004', file: 'academics/domain/aggregates/observation.aggregate.ts', target: 'ObservationAggregate.recordObservation', kind: 'aggregate' },
  { ruleId: 'R-ACD-005', file: 'academics/domain/aggregates/observation.aggregate.ts', target: 'ObservationAggregate.recordObservation', kind: 'aggregate' },
  { ruleId: 'R-ACD-006', file: 'academics/domain/aggregates/assessment.aggregate.ts', target: 'AssessmentAggregate.assessMilestone', kind: 'aggregate' },
  { ruleId: 'R-ACD-007', file: 'academics/domain/aggregates/assessment.aggregate.ts', target: 'AssessmentAggregate.assessMilestone', kind: 'aggregate' },
  { ruleId: 'R-ACD-008', file: 'academics/domain/aggregates/portfolio.aggregate.ts', target: 'PortfolioAggregate.updatePortfolio', kind: 'aggregate' },
  { ruleId: 'R-ACD-009', file: 'academics/domain/aggregates/report-card.aggregate.ts', target: 'ReportCardAggregate.generate/approve', kind: 'aggregate' },
  { ruleId: 'R-ACD-010', file: 'academics/domain/aggregates/report-card.aggregate.ts', target: 'ReportCardAggregate.generate/approve', kind: 'aggregate' },
  { ruleId: 'R-ACD-011', file: 'academics/domain/aggregates/enrollment.aggregate.ts', target: 'EnrollmentAggregate.assertPromotionCriteria', kind: 'aggregate' },
  { ruleId: 'R-ACD-012', file: 'academics/domain/aggregates/enrollment.aggregate.ts', target: 'EnrollmentAggregate.assertPromotionCriteria', kind: 'aggregate' },
  { ruleId: 'R-ACD-013', file: 'academics/domain/aggregates/observation.aggregate.ts', target: 'ObservationAggregate.schedulePtm', kind: 'aggregate' },
  { ruleId: 'R-ACD-014', file: 'academics/domain/aggregates/enrollment.aggregate.ts', target: 'EnrollmentAggregate.triggerRemedial', kind: 'aggregate' },
  { ruleId: 'R-ACD-015', file: 'academics/domain/aggregates/observation.aggregate.ts', target: 'ObservationAggregate.assertOutdoorSafety', kind: 'aggregate' },
  { ruleId: 'R-ACD-016', file: 'academics/domain/aggregates/observation.aggregate.ts', target: 'ObservationAggregate.recordActivity', kind: 'aggregate' },
  { ruleId: 'R-ACD-017', file: 'academics/domain/aggregates/curriculum.aggregate.ts', target: 'CurriculumAggregate.rotateTheme', kind: 'aggregate' },
  { ruleId: 'R-ACD-018', file: 'academics/domain/aggregates/observation.aggregate.ts', target: 'ObservationAggregate.assertOutdoorSafety', kind: 'aggregate' },
  { ruleId: 'R-HR-001', file: 'hr/domain/aggregates/employee.aggregate.ts', target: 'EmployeeAggregate.assertQualification', kind: 'aggregate' },
  { ruleId: 'R-HR-002', file: 'hr/domain/aggregates/employee.aggregate.ts', target: 'EmployeeAggregate.assertBackgroundVerified', kind: 'aggregate' },
  { ruleId: 'R-HR-003', file: 'hr/domain/aggregates/leave.aggregate.ts', target: 'LeaveAggregate.apply/assertEntitlement', kind: 'aggregate' },
  { ruleId: 'R-HR-004', file: 'hr/domain/aggregates/leave.aggregate.ts', target: 'LeaveAggregate.apply/assertEntitlement', kind: 'aggregate' },
  { ruleId: 'R-HR-005', file: 'hr/domain/aggregates/substitute-assignment.aggregate.ts', target: 'SubstituteAssignmentAggregate.assign', kind: 'aggregate' },
  { ruleId: 'R-HR-006', file: 'hr/domain/aggregates/payroll.aggregate.ts', target: 'PayrollAggregate.runPayroll', kind: 'aggregate' },
  { ruleId: 'R-HR-007', file: 'hr/domain/aggregates/performance-review.aggregate.ts', target: 'PerformanceReviewAggregate.review', kind: 'aggregate' },
  { ruleId: 'R-HR-008', file: 'hr/domain/aggregates/employee.aggregate.ts', target: 'EmployeeAggregate.exit', kind: 'aggregate' },
  { ruleId: 'R-HR-009', file: 'hr/domain/aggregates/icc-committee.aggregate.ts', target: 'IccCommitteeAggregate.fileComplaint', kind: 'aggregate' },
  { ruleId: 'R-HR-010', file: 'hr/domain/aggregates/icc-committee.aggregate.ts', target: 'IccCommitteeAggregate.fileComplaint', kind: 'aggregate' },
  { ruleId: 'R-HR-011', file: 'hr/domain/aggregates/training-record.aggregate.ts', target: 'TrainingRecordAggregate.recordTraining', kind: 'aggregate' },
  { ruleId: 'R-HR-012', file: 'hr/domain/aggregates/employee.aggregate.ts', target: 'EmployeeAggregate.completeProbation', kind: 'aggregate' },
  { ruleId: 'R-INV-001', file: 'inventory/domain/aggregates/reorder-alert.aggregate.ts', target: 'ReorderAlertAggregate.triggerReorder', kind: 'aggregate' },
  { ruleId: 'R-INV-002', file: 'inventory/domain/aggregates/reorder-alert.aggregate.ts', target: 'ReorderAlertAggregate.triggerReorder', kind: 'aggregate' },
  { ruleId: 'R-INV-003', file: 'inventory/domain/aggregates/inventory-item.aggregate.ts', target: 'InventoryItemAggregate.assertExpiryTracking', kind: 'aggregate' },
  { ruleId: 'R-INV-004', file: 'inventory/domain/aggregates/expired-item-disposal.aggregate.ts', target: 'ExpiredItemDisposalAggregate.dispose', kind: 'aggregate' },
  { ruleId: 'R-INV-005', file: 'inventory/domain/aggregates/inventory-item.aggregate.ts', target: 'InventoryItemAggregate.computeDepreciation', kind: 'aggregate' },
  { ruleId: 'R-INV-006', file: 'inventory/domain/aggregates/supplier.aggregate.ts', target: 'SupplierAggregate.updateRating', kind: 'aggregate' },
  { ruleId: 'R-INV-007', file: 'inventory/domain/aggregates/purchase-order.aggregate.ts', target: 'PurchaseOrderAggregate.approve', kind: 'aggregate' },
  { ruleId: 'R-INV-008', file: 'inventory/domain/aggregates/goods-issue.aggregate.ts', target: 'GoodsIssueAggregate.issue', kind: 'aggregate' },
  { ruleId: 'R-INV-009', file: 'inventory/domain/aggregates/stock-audit.aggregate.ts', target: 'StockAuditAggregate.execute', kind: 'aggregate' },
  { ruleId: 'R-INV-010', file: 'inventory/domain/aggregates/return-note.aggregate.ts', target: 'ReturnNoteAggregate.processReturn', kind: 'aggregate' },
  { ruleId: 'R-INV-011', file: 'inventory/domain/aggregates/inventory-item.aggregate.ts', target: 'InventoryItemAggregate.trackConsumption', kind: 'aggregate' },
  { ruleId: 'R-INV-012', file: 'inventory/domain/aggregates/return-note.aggregate.ts', target: 'ReturnNoteAggregate.disposeAsset', kind: 'aggregate' },
  { ruleId: 'R-COM-001', file: 'communication/domain/aggregates/conversation.aggregate.ts', target: 'ConversationAggregate.assertResponseTime', kind: 'aggregate' },
  { ruleId: 'R-COM-002', file: 'communication/domain/aggregates/conversation.aggregate.ts', target: 'ConversationAggregate.assertResponseTime', kind: 'aggregate' },
  { ruleId: 'R-COM-003', file: 'communication/domain/aggregates/announcement.aggregate.ts', target: 'AnnouncementAggregate.assertBroadcastWindow', kind: 'aggregate' },
  { ruleId: 'R-COM-004', file: 'communication/domain/aggregates/announcement.aggregate.ts', target: 'AnnouncementAggregate.assertBroadcastWindow', kind: 'aggregate' },
  { ruleId: 'R-COM-005', file: 'communication/domain/aggregates/notification.aggregate.ts', target: 'NotificationAggregate.respectPreference', kind: 'aggregate' },
  { ruleId: 'R-COM-006', file: 'communication/domain/aggregates/notification.aggregate.ts', target: 'NotificationAggregate.respectPreference', kind: 'aggregate' },
  { ruleId: 'R-COM-007', file: 'communication/domain/aggregates/notification.aggregate.ts', target: 'NotificationAggregate.respectPreference', kind: 'aggregate' },
  { ruleId: 'R-COM-008', file: 'communication/domain/aggregates/announcement.aggregate.ts', target: 'AnnouncementAggregate.approve', kind: 'aggregate' },
  { ruleId: 'R-COM-009', file: 'communication/domain/aggregates/announcement.aggregate.ts', target: 'AnnouncementAggregate.assertPhotoCaption', kind: 'aggregate' },
  { ruleId: 'R-COM-010', file: 'communication/domain/aggregates/conversation.aggregate.ts', target: 'ConversationAggregate.retainHistory', kind: 'aggregate' },
  { ruleId: 'R-COM-011', file: 'communication/application/services/communication.service.ts', target: 'CommunicationService.enforceWhatsappRateLimit', kind: 'service' },
  { ruleId: 'R-COM-012', file: 'communication/domain/aggregates/notification.aggregate.ts', target: 'NotificationAggregate.cascadeEmergency', kind: 'aggregate' },
  { ruleId: 'R-CMP-001', file: 'administration/domain/aggregates/compliance-item.aggregate.ts', target: 'ComplianceItemAggregate.assertConsent', kind: 'aggregate' },
  { ruleId: 'R-CMP-002', file: 'administration/domain/aggregates/compliance-item.aggregate.ts', target: 'ComplianceItemAggregate.processConsentWithdrawal', kind: 'aggregate' },
  { ruleId: 'R-CMP-003', file: 'administration/domain/aggregates/compliance-item.aggregate.ts', target: 'ComplianceItemAggregate.enforceRetention', kind: 'aggregate' },
  { ruleId: 'R-CMP-004', file: 'administration/domain/aggregates/compliance-item.aggregate.ts', target: 'ComplianceItemAggregate.assertEncryptionAtRest', kind: 'aggregate' },
  { ruleId: 'R-CMP-005', file: 'administration/domain/aggregates/cctv-coverage.aggregate.ts', target: 'CctvCoverageAggregate.assertRetention', kind: 'aggregate' },
  { ruleId: 'R-CMP-006', file: 'administration/domain/aggregates/compliance-item.aggregate.ts', target: 'ComplianceItemAggregate', kind: 'aggregate' },
  { ruleId: 'R-CMP-007', file: 'administration/domain/aggregates/compliance-item.aggregate.ts', target: 'ComplianceItemAggregate.assertFireSafety', kind: 'aggregate' },
  { ruleId: 'R-CMP-008', file: 'platform/domain/aggregates/breach-notification.aggregate.ts', target: 'BreachNotificationAggregate.notify', kind: 'aggregate' },
  { ruleId: 'R-CMP-009', file: 'hr/domain/aggregates/icc-committee.aggregate.ts', target: 'IccCommitteeAggregate.handlePosh', kind: 'aggregate' },
  { ruleId: 'R-CMP-010', file: 'hr/domain/aggregates/icc-committee.aggregate.ts', target: 'IccCommitteeAggregate.handlePosh', kind: 'aggregate' },
  { ruleId: 'R-CMP-011', file: 'hr/domain/aggregates/icc-committee.aggregate.ts', target: 'IccCommitteeAggregate.handlePosh', kind: 'aggregate' },
  { ruleId: 'R-CMP-012', file: 'hr/domain/aggregates/icc-committee.aggregate.ts', target: 'IccCommitteeAggregate.handlePosh', kind: 'aggregate' },
  { ruleId: 'R-CMP-013', file: 'administration/domain/aggregates/compliance-item.aggregate.ts', target: 'ComplianceItemAggregate.assertFireSafety', kind: 'aggregate' },
  { ruleId: 'R-CMP-014', file: 'administration/domain/aggregates/compliance-item.aggregate.ts', target: 'ComplianceItemAggregate.assertFireSafety', kind: 'aggregate' },
  { ruleId: 'R-CMP-015', file: 'administration/domain/aggregates/compliance-item.aggregate.ts', target: 'ComplianceItemAggregate.assertFireSafety', kind: 'aggregate' },
  { ruleId: 'R-CMP-016', file: 'administration/domain/aggregates/compliance-item.aggregate.ts', target: 'ComplianceItemAggregate.assertRteNonDiscrimination', kind: 'aggregate' },
  { ruleId: 'R-CMP-017', file: 'hr/domain/aggregates/training-record.aggregate.ts', target: 'TrainingRecordAggregate.assertFoodHandlerCert', kind: 'aggregate' },
  { ruleId: 'R-CMP-018', file: 'hr/domain/aggregates/training-record.aggregate.ts', target: 'TrainingRecordAggregate.assertFoodHandlerCert', kind: 'aggregate' },
  { ruleId: 'R-APR-001', file: 'finance/domain/aggregates/invoice.aggregate.ts', target: 'InvoiceAggregate.approveDiscount', kind: 'aggregate' },
  { ruleId: 'R-APR-002', file: 'finance/domain/aggregates/refund.aggregate.ts', target: 'RefundAggregate.approve', kind: 'aggregate' },
  { ruleId: 'R-APR-003', file: 'hr/domain/aggregates/leave.aggregate.ts', target: 'LeaveAggregate.approve', kind: 'aggregate' },
  { ruleId: 'R-APR-004', file: 'finance/application/services/finance.service.ts', target: 'FinanceService.approveExpense', kind: 'service' },
  { ruleId: 'R-APR-005', file: 'inventory/domain/aggregates/supplier.aggregate.ts', target: 'SupplierAggregate.approveOnboarding', kind: 'aggregate' },
  { ruleId: 'R-APR-006', file: 'admissions/domain/aggregates/admission.aggregate.ts', target: 'AdmissionAggregate.approve', kind: 'aggregate' },
  { ruleId: 'R-APR-007', file: 'finance/domain/aggregates/fee-plan.aggregate.ts', target: 'FeePlanAggregate.approveWaiver', kind: 'aggregate' },
  { ruleId: 'R-APR-008', file: 'inventory/domain/aggregates/expired-item-disposal.aggregate.ts', target: 'ExpiredItemDisposalAggregate.approve', kind: 'aggregate' },
  { ruleId: 'R-APR-009', file: 'identity/domain/aggregates/role.aggregate.ts', target: 'RoleAggregate.escalate', kind: 'aggregate' },
  { ruleId: 'R-APR-010', file: 'hr/domain/aggregates/position-opening.aggregate.ts', target: 'PositionOpeningAggregate.approve', kind: 'aggregate' },
  { ruleId: 'R-APR-011', file: 'hr/domain/aggregates/salary-revision.aggregate.ts', target: 'SalaryRevisionAggregate.approve', kind: 'aggregate' },
  { ruleId: 'R-APR-012', file: 'settings/domain/aggregates/system-config.aggregate.ts', target: 'SystemConfigAggregate.approvePolicyChange', kind: 'aggregate' },
  { ruleId: 'R-APR-013', file: 'identity/application/services/user.service.ts', target: 'UserService.approveBulkExport', kind: 'service' },
  { ruleId: 'R-APR-014', file: 'inventory/domain/aggregates/supplier.aggregate.ts', target: 'SupplierAggregate.approveOnboarding', kind: 'aggregate' },
  { ruleId: 'R-APR-015', file: 'academics/domain/aggregates/curriculum.aggregate.ts', target: 'CurriculumAggregate.approveChange', kind: 'aggregate' },
  { ruleId: 'R-NOT-001', file: 'communication/domain/aggregates/notification.aggregate.ts', target: 'NotificationAggregate.sendFeeReminder', kind: 'aggregate' },
  { ruleId: 'R-NOT-002', file: 'communication/domain/aggregates/notification.aggregate.ts', target: 'NotificationAggregate.alertAbsence', kind: 'aggregate' },
  { ruleId: 'R-NOT-003', file: 'communication/domain/aggregates/notification.aggregate.ts', target: 'NotificationAggregate.pushDailyReport', kind: 'aggregate' },
  { ruleId: 'R-NOT-004', file: 'communication/domain/aggregates/notification.aggregate.ts', target: 'NotificationAggregate.sendGreeting', kind: 'aggregate' },
  { ruleId: 'R-NOT-005', file: 'communication/domain/aggregates/notification.aggregate.ts', target: 'NotificationAggregate.sendGreeting', kind: 'aggregate' },
  { ruleId: 'R-NOT-006', file: 'communication/domain/aggregates/notification.aggregate.ts', target: 'NotificationAggregate.notifyIncident', kind: 'aggregate' },
  { ruleId: 'R-NOT-007', file: 'communication/domain/aggregates/notification.aggregate.ts', target: 'NotificationAggregate.alertPhotoShare', kind: 'aggregate' },
  { ruleId: 'R-NOT-008', file: 'communication/domain/aggregates/announcement.aggregate.ts', target: 'AnnouncementAggregate.announceEvent', kind: 'aggregate' },
  { ruleId: 'R-NOT-009', file: 'communication/domain/aggregates/notification.aggregate.ts', target: 'NotificationAggregate.sendGreeting', kind: 'aggregate' },
  { ruleId: 'R-NOT-010', file: 'transport/domain/aggregates/trip.aggregate.ts', target: 'TripAggregate.alertDelay', kind: 'aggregate' },
  { ruleId: 'R-NOT-011', file: 'hr/domain/aggregates/payroll.aggregate.ts', target: 'PayrollAggregate.notifySalaryCredit', kind: 'aggregate' },
  { ruleId: 'R-NOT-012', file: 'platform/domain/aggregates/support-ticket.aggregate.ts', target: 'SupportTicketAggregate.notifyMaintenance', kind: 'aggregate' },
  { ruleId: 'R-DAT-001', file: 'identity/application/services/user.service.ts', target: 'UserService.encryptPiiAtRest', kind: 'service' },
  { ruleId: 'R-DAT-002', file: 'identity/domain/aggregates/user.aggregate.ts', target: 'UserAggregate', kind: 'aggregate' },
  { ruleId: 'R-DAT-003', file: 'identity/application/services/permission-resolver.service.ts', target: 'PermissionResolverService.maskPii', kind: 'service' },
  { ruleId: 'R-DAT-004', file: 'identity/application/services/permission-resolver.service.ts', target: 'PermissionResolverService.maskPii', kind: 'service' },
  { ruleId: 'R-DAT-005', file: 'identity/application/services/event-translator.service.ts', target: 'EventTranslatorService.recordAudit', kind: 'service' },
  { ruleId: 'R-DAT-006', file: 'identity/domain/aggregates/user.aggregate.ts', target: 'UserAggregate', kind: 'aggregate' },
  { ruleId: 'R-DAT-007', file: 'platform/domain/aggregates/dsar-request.aggregate.ts', target: 'DsarRequestAggregate.fulfill', kind: 'aggregate' },
  { ruleId: 'R-DAT-008', file: 'platform/domain/aggregates/dsar-request.aggregate.ts', target: 'DsarRequestAggregate.processErasure', kind: 'aggregate' },
  { ruleId: 'R-DAT-009', file: 'identity/domain/aggregates/user.aggregate.ts', target: 'UserAggregate', kind: 'aggregate' },
  { ruleId: 'R-DAT-010', file: 'identity/domain/aggregates/user.aggregate.ts', target: 'UserAggregate', kind: 'aggregate' },
  { ruleId: 'R-DAT-011', file: 'identity/domain/aggregates/user.aggregate.ts', target: 'UserAggregate.softDelete', kind: 'aggregate' },
  { ruleId: 'R-DAT-012', file: 'identity/application/services/event-translator.service.ts', target: 'EventTranslatorService.anonymizeAnalytics', kind: 'service' },
  { ruleId: 'R-PLT-001', file: 'platform/domain/aggregates/tenant-provisioning.aggregate.ts', target: 'TenantProvisioningAggregate.assertIsolation', kind: 'aggregate' },
  { ruleId: 'R-PLT-002', file: 'platform/domain/aggregates/subscription.aggregate.ts', target: 'SubscriptionAggregate.assertGracePeriod', kind: 'aggregate' },
  { ruleId: 'R-PLT-003', file: 'platform/domain/aggregates/subscription.aggregate.ts', target: 'SubscriptionAggregate.assertGracePeriod', kind: 'aggregate' },
  { ruleId: 'R-PLT-004', file: 'settings/domain/aggregates/feature-flag.aggregate.ts', target: 'FeatureFlagAggregate.evaluateTier', kind: 'aggregate' },
  { ruleId: 'R-PLT-005', file: 'identity/application/services/school.service.ts', target: 'SchoolService.assertLicenseSeats', kind: 'service' },
  { ruleId: 'R-PLT-006', file: 'identity/domain/aggregates/branch.aggregate.ts', target: 'BranchAggregate.assertDataPartition', kind: 'aggregate' },
  { ruleId: 'R-PLT-007', file: 'platform/domain/aggregates/tenant-provisioning.aggregate.ts', target: 'TenantProvisioningAggregate', kind: 'aggregate' },
  { ruleId: 'R-PLT-008', file: 'platform/domain/aggregates/tenant-provisioning.aggregate.ts', target: 'TenantProvisioningAggregate.assertIsolation', kind: 'aggregate' },
  { ruleId: 'R-PLT-009', file: 'platform/domain/aggregates/tenant-provisioning.aggregate.ts', target: 'TenantProvisioningAggregate.validateOnboarding', kind: 'aggregate' },
  { ruleId: 'R-PLT-010', file: 'platform/domain/aggregates/tenant-provisioning.aggregate.ts', target: 'TenantProvisioningAggregate.offboard', kind: 'aggregate' },
];

export function registerBrcDeclarations(): void {
  for (const d of DECLARATIONS) {
    enforceRuleInTest(d.ruleId, d.target, d.file);
  }
}

// Eager registration on module load so the traceability spec can introspect.
registerBrcDeclarations();

export const BRC_DECLARATION_COUNT = DECLARATIONS.length;
