/**
 * BRC v1.0 - Business Rules Catalog (176 rules across 12 domains).
 *
 * Source: BRC v1.0 (Business Review Draft, 2026-07-12).
 * Each rule is uniquely identified by R-<DOMAIN>-<NNN> and is stable across releases.
 *
 * Traceability:
 *   - Every domain aggregate / service / controller that enforces a rule should be
 *     annotated with @EnforcesRule('R-XXX-NNN') from ./brc-trace.decorator
 *   - The brc-traceability.spec.ts test asserts that every catalog rule has >=1
 *     enforcement reference (or is explicitly marked as deferred).
 */

export type BrcDomain =
  | 'ELG'
  | 'FIN'
  | 'OPS'
  | 'ACD'
  | 'HR'
  | 'INV'
  | 'COM'
  | 'CMP'
  | 'APR'
  | 'NOT'
  | 'DAT'
  | 'PLT'
  ;

export interface BrcRule {
  ruleId: string;
  domain: BrcDomain;
  domainName: string;
  subDomain: string;
  title: string;
  trigger: string;
  action: string;
  owner: string;
}

export const BRC_DOMAINS: Record<BrcDomain, { name: string; subDomain: string }> = {
  ELG: { name: 'Admissions', subDomain: 'Eligibility & Enrollment' },
  FIN: { name: 'Finance', subDomain: 'Fee, Invoice, Refund, Vendor Payment' },
  OPS: { name: 'Operations', subDomain: 'Daily Operations & Safety' },
  ACD: { name: 'Academics', subDomain: 'Curriculum, Assessment, Portfolio' },
  HR: { name: 'HR', subDomain: 'Staff Lifecycle & Compliance' },
  INV: { name: 'Inventory', subDomain: 'Stock, PO, Asset, Disposal' },
  COM: { name: 'Communication', subDomain: 'Messaging, Announcement, Chat' },
  CMP: { name: 'Compliance', subDomain: 'Consent, PII, POSH, Fire, FSSAI' },
  APR: { name: 'Approvals', subDomain: 'Approval Matrices & Escalations' },
  NOT: { name: 'Notifications', subDomain: 'Reminder & Alert Cadence' },
  DAT: { name: 'Data', subDomain: 'PII, Encryption, Retention, DSAR' },
  PLT: { name: 'Platform', subDomain: 'Tenant, Subscription, License, Onboarding' },
};

/**
 * Catalog of all 176 BRC v1.0 rules, ordered by domain then numeric ID.
 * Generated from extracted/brc_tables.json - DO NOT EDIT BY HAND.
 */
export const BRC_RULES: readonly BrcRule[] = [
  {
    ruleId: 'R-ELG-001',
    domain: 'ELG',
    domainName: 'Admissions',
    subDomain: 'Eligibility & Enrollment',
    title: 'Playgroup Age Eligibility',
    trigger: 'Application Form submission for Playgroup class',
    action: 'Block application; show age-appropriate class suggestion (Nursery if >2.5)',
    owner: 'Admission Counsellor',
  },
  {
    ruleId: 'R-ELG-002',
    domain: 'ELG',
    domainName: 'Admissions',
    subDomain: 'Eligibility & Enrollment',
    title: 'Nursery Age Eligibility',
    trigger: 'Application Form submission for Nursery class',
    action: 'Block application; suggest Playgroup (if <2.5) or Jr.KG (if >3.5)',
    owner: 'Admission Counsellor',
  },
  {
    ruleId: 'R-ELG-003',
    domain: 'ELG',
    domainName: 'Admissions',
    subDomain: 'Eligibility & Enrollment',
    title: 'Jr.KG Age Eligibility',
    trigger: 'Application Form submission for Jr.KG class',
    action: 'Block application; suggest Nursery (if <3.5) or Sr.KG (if >4.5)',
    owner: 'Admission Counsellor',
  },
  {
    ruleId: 'R-ELG-004',
    domain: 'ELG',
    domainName: 'Admissions',
    subDomain: 'Eligibility & Enrollment',
    title: 'Sr.KG Age Eligibility',
    trigger: 'Application Form submission for Sr.KG class',
    action: 'Block application; suggest Jr.KG (if <4.5) or Grade 1 (if >5.5)',
    owner: 'Admission Counsellor',
  },
  {
    ruleId: 'R-ELG-005',
    domain: 'ELG',
    domainName: 'Admissions',
    subDomain: 'Eligibility & Enrollment',
    title: 'Age Proof Document Mandatory',
    trigger: 'Application Form submission',
    action: 'Block submission; request acceptable age proof document',
    owner: 'Admission Counsellor',
  },
  {
    ruleId: 'R-ELG-006',
    domain: 'ELG',
    domainName: 'Admissions',
    subDomain: 'Eligibility & Enrollment',
    title: 'Birth Certificate Mandatory',
    trigger: 'Application Form submission',
    action: 'Mark application \'Pending Documents\'; send automated reminder to parent (D+3, D+7, D+14)',
    owner: 'Admission Counsellor',
  },
  {
    ruleId: 'R-ELG-007',
    domain: 'ELG',
    domainName: 'Admissions',
    subDomain: 'Eligibility & Enrollment',
    title: 'Medical Fitness Declaration',
    trigger: 'Application Form submission (post-document upload)',
    action: 'Mark \'Pending Medical\'; require signed medical declaration by parent + pediatrician certificate',
    owner: 'Admission Counsellor',
  },
  {
    ruleId: 'R-ELG-008',
    domain: 'ELG',
    domainName: 'Admissions',
    subDomain: 'Eligibility & Enrollment',
    title: 'Photograph Mandatory',
    trigger: 'Application Form submission',
    action: 'Send automated reminder; allow admission approval conditional on photo within 7 days',
    owner: 'Admission Counsellor',
  },
  {
    ruleId: 'R-ELG-009',
    domain: 'ELG',
    domainName: 'Admissions',
    subDomain: 'Eligibility & Enrollment',
    title: 'Parent/Guardian Identity Proof',
    trigger: 'Application Form submission',
    action: 'Require acceptable parent ID proof upload',
    owner: 'Admission Counsellor',
  },
  {
    ruleId: 'R-ELG-010',
    domain: 'ELG',
    domainName: 'Admissions',
    subDomain: 'Eligibility & Enrollment',
    title: 'Primary Contact Mandatory',
    trigger: 'Application Form submission',
    action: 'Require valid Indian mobile number (+91 format) for primary contact',
    owner: 'Admission Counsellor',
  },
  {
    ruleId: 'R-ELG-011',
    domain: 'ELG',
    domainName: 'Admissions',
    subDomain: 'Eligibility & Enrollment',
    title: 'Sibling Admission Priority',
    trigger: 'Application Form submission with sibling_already_enrolled = TRUE',
    action: 'Auto-flag application as \'Sibling Priority\'; fast-track counselling slot within 48 hours',
    owner: 'Admission Counsellor',
  },
  {
    ruleId: 'R-ELG-012',
    domain: 'ELG',
    domainName: 'Admissions',
    subDomain: 'Eligibility & Enrollment',
    title: 'Staff Ward Admission Quota',
    trigger: 'Application Form submission with staff_ward = TRUE',
    action: 'Apply staff ward discount; route to HR validation for staff tenure confirmation',
    owner: 'HR + Admission Counsellor',
  },
  {
    ruleId: 'R-ELG-013',
    domain: 'ELG',
    domainName: 'Admissions',
    subDomain: 'Eligibility & Enrollment',
    title: 'Transfer Student Eligibility',
    trigger: 'Mid-year application from student transferring from another school',
    action: 'Allow admission; carry forward previous attendance records',
    owner: 'Admission Counsellor + Principal',
  },
  {
    ruleId: 'R-ELG-014',
    domain: 'ELG',
    domainName: 'Admissions',
    subDomain: 'Eligibility & Enrollment',
    title: 'RTE Section 12 (25% EWS Reservation)',
    trigger: 'Annual admission cycle planning (Jan-March)',
    action: 'Reserve 25% seats for EWS category; integrate with state RTE portal for reimbursement claims',
    owner: 'Principal + Management',
  },
  {
    ruleId: 'R-ELG-015',
    domain: 'ELG',
    domainName: 'Admissions',
    subDomain: 'Eligibility & Enrollment',
    title: 'Special Needs Child Admission',
    trigger: 'Application Form with special_needs_flag = TRUE',
    action: 'Admission conditional on assessment; if severity > moderate, recommend shadow teacher requirement',
    owner: 'Principal + Special Educator',
  },
  {
    ruleId: 'R-FIN-001',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'Fee Due Date Enforcement',
    trigger: 'Invoice generated with due_date',
    action: 'Mark invoice overdue; trigger R-FIN-002 (late fee calculation); trigger R-NOT-001 (reminder)',
    owner: 'Accounts Team',
  },
  {
    ruleId: 'R-FIN-002',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'Late Fee Calculation',
    trigger: 'Invoice overdue (post R-FIN-001)',
    action: 'Add late fee line item to invoice; send notification; if >60 days, block attendance marking + ID card',
    owner: 'Accounts Team',
  },
  {
    ruleId: 'R-FIN-003',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'Refund Policy — Withdrawal Before Term Start',
    trigger: 'Parent submits withdrawal request before term start date',
    action: 'Process refund within 14 working days to original payment method',
    owner: 'Accounts Team + Branch Head',
  },
  {
    ruleId: 'R-FIN-004',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'Refund — Mid-Term Withdrawal',
    trigger: 'Parent submits withdrawal request after term start',
    action: 'Generate refund invoice; route to Branch Head approval; process within 14 days',
    owner: 'Accounts Team + Branch Head',
  },
  {
    ruleId: 'R-FIN-005',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'Sibling Discount',
    trigger: 'Second+ child admission in same school',
    action: 'Auto-apply discount on invoice generation; visible as separate line item',
    owner: 'Accounts Team',
  },
  {
    ruleId: 'R-FIN-006',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'Early Bird Discount',
    trigger: 'Admission confirmed before April 30th for next academic year',
    action: 'Auto-apply discount at invoice generation',
    owner: 'Accounts Team',
  },
  {
    ruleId: 'R-FIN-007',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'GST on Educational Services',
    trigger: 'Invoice generation',
    action: 'Apply correct GST rate; generate GST-compliant invoice with HSN code, GSTIN, place of supply',
    owner: 'Accounts Team + Finance Head',
  },
  {
    ruleId: 'R-FIN-008',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'Invoice Number Generation',
    trigger: 'New invoice created',
    action: 'Generate sequential invoice number; GST invoice series registered with GST portal',
    owner: 'Accounts Team',
  },
  {
    ruleId: 'R-FIN-009',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'Payment Receipt Generation',
    trigger: 'Payment confirmed (post-payment-success webhook)',
    action: 'Auto-generate PDF receipt; email to parent; sync to parent app; archive in document store',
    owner: 'Accounts Team',
  },
  {
    ruleId: 'R-FIN-010',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'Digital Payment Mandate',
    trigger: 'Fee payment attempt',
    action: 'Disable cash payment option above ₹50,000; show digital payment methods only',
    owner: 'Accounts Team',
  },
  {
    ruleId: 'R-FIN-011',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'Cheque Bounce Handling (NSF)',
    trigger: 'Bank webhook: cheque_returned NSF',
    action: 'Reverse receipt; mark invoice unpaid; send demand notice (legal format) within 3 days; block future cheque payments for parent',
    owner: 'Accounts Team + Finance Head',
  },
  {
    ruleId: 'R-FIN-012',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'Installment Plan Approval',
    trigger: 'Parent requests installment plan for annual fee',
    action: 'Create installment schedule; generate separate invoices per installment with respective due dates',
    owner: 'Accounts Team + Branch Head',
  },
  {
    ruleId: 'R-FIN-013',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'Merit Scholarship Eligibility',
    trigger: 'Annual scholarship cycle (April)',
    action: 'Auto-flag eligible students; route to scholarship committee for final selection',
    owner: 'Principal + Scholarship Committee',
  },
  {
    ruleId: 'R-FIN-014',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'Bad Debt Write-off',
    trigger: 'Invoice overdue > 365 days',
    action: 'Route to Finance Head + Director approval; if approved, write-off in books; retain recovery rights for 3 years',
    owner: 'Finance Head + Director',
  },
  {
    ruleId: 'R-FIN-015',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'Expense Approval Matrix',
    trigger: 'Expense claim submitted',
    action: 'Route to appropriate approver based on amount; multi-level approval workflow',
    owner: 'Accounts Team + Multi-level Approvers',
  },
  {
    ruleId: 'R-FIN-016',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'Vendor Payment Terms',
    trigger: 'Vendor invoice received + GRN verified',
    action: 'Schedule payment; auto-pay on due date via NEFT/RTGS',
    owner: 'Accounts Team + Branch Head',
  },
  {
    ruleId: 'R-FIN-017',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'TDS Deduction on Vendor Payments',
    trigger: 'Vendor payment > ₹30,000 (single) or > ₹1,00,000 (annual aggregate)',
    action: 'Deduct TDS; generate Form 16A quarterly; file TDS return; issue TDS certificate to vendor',
    owner: 'Accounts Team + Finance Head',
  },
  {
    ruleId: 'R-FIN-018',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'Financial Hardship Waiver',
    trigger: 'Parent submits fee waiver request with documentation',
    action: 'Route to Branch Head + Director joint approval; waiver valid for current term only (renewal required)',
    owner: 'Branch Head + Director',
  },
  {
    ruleId: 'R-FIN-019',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'RTE Section 12 Reimbursement Claim',
    trigger: 'Quarterly RTE reimbursement cycle',
    action: 'Generate claim file; upload to state RTE portal; track reimbursement status; reconcile on receipt',
    owner: 'Principal + Accounts Team',
  },
  {
    ruleId: 'R-FIN-020',
    domain: 'FIN',
    domainName: 'Finance',
    subDomain: 'Fee, Invoice, Refund, Vendor Payment',
    title: 'Annual Financial Audit',
    trigger: 'End of financial year (March 31)',
    action: 'Engage CA firm; provide books, invoices, receipts, bank statements; receive audit report; file ITR',
    owner: 'Finance Head + CA',
  },
  {
    ruleId: 'R-OPS-001',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'Authorized Pickup Person List',
    trigger: 'Child enrollment / Parent app onboarding',
    action: 'Enforce max 4 authorized pickups per child; store photos + ID proof in encrypted form',
    owner: 'Branch Admin + Parent',
  },
  {
    ruleId: 'R-OPS-002',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'Unauthorized Pickup Block',
    trigger: 'Person arrives for child pickup not in authorized list',
    action: 'Hold child in supervision area; call parent for authorization; if confirmed via parent app OTP, allow pickup with photo capture',
    owner: 'Teacher + Branch Admin',
  },
  {
    ruleId: 'R-OPS-003',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'Late Pickup Fee',
    trigger: 'Child picked up after school closing time',
    action: 'Auto-generate late pickup invoice; notify parent; recurring late (>3 times/quarter) triggers meeting with Branch Head',
    owner: 'Branch Admin',
  },
  {
    ruleId: 'R-OPS-004',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'Arrival Cutoff Time',
    trigger: 'Child arrival at school gate',
    action: 'Allow entry with late pass; log reason (parent input); recurring late (>3/week) triggers parent meeting',
    owner: 'Branch Admin + Teacher',
  },
  {
    ruleId: 'R-OPS-005',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'Attendance Threshold for Promotion',
    trigger: 'Annual promotion cycle (March-April)',
    action: 'Flag for review; require parent meeting + remedial plan; conditional promotion with attendance improvement plan',
    owner: 'Principal + Teacher',
  },
  {
    ruleId: 'R-OPS-006',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'Attendance Marking Window',
    trigger: 'Daily school session start',
    action: 'Send reminder to teacher; after 60 min, escalate to Branch Admin to mark attendance',
    owner: 'Teacher + Branch Admin',
  },
  {
    ruleId: 'R-OPS-007',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'Mid-Day Exit Gate Pass',
    trigger: 'Parent requests mid-day child pickup',
    action: 'Generate digital gate pass; teacher releases child; security logs exit time',
    owner: 'Branch Admin + Security',
  },
  {
    ruleId: 'R-OPS-008',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'Visitor Logging',
    trigger: 'Visitor arrives at school gate',
    action: 'Capture visitor details; issue visitor badge; host notified via app; badge returned on exit',
    owner: 'Security + Reception',
  },
  {
    ruleId: 'R-OPS-009',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'Bus Route Assignment',
    trigger: 'Transport opt-in during admission / annual renewal',
    action: 'Assign child to nearest pickup point; notify parent + driver; generate route card',
    owner: 'Transport In-charge',
  },
  {
    ruleId: 'R-OPS-010',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'Bus Tracking — Real-time GPS',
    trigger: 'Bus trip start (morning pickup / evening drop)',
    action: 'Auto-notify parents of expected delay; Transport In-charge calls driver; if unreachable >15 min, escalate to Branch Head',
    owner: 'Transport In-charge',
  },
  {
    ruleId: 'R-OPS-011',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'Bus Missing Child Alert',
    trigger: 'Bus arrives at school / drop point',
    action: 'Trigger P0 alert: Branch Head + Transport In-charge + Parent + Driver; halt bus; conduct physical search',
    owner: 'Transport In-charge + Branch Head',
  },
  {
    ruleId: 'R-OPS-012',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'Morning Health Check',
    trigger: 'Child arrival at classroom',
    action: 'Move child to health room; notify parent within 5 min; record observation in health log',
    owner: 'Teacher + Health Attendant',
  },
  {
    ruleId: 'R-OPS-013',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'Meal Allergy Check',
    trigger: 'Daily meal preparation / serving',
    action: 'Generate allergen-safe meal list per class; kitchen gets allergy-aware menu; serve alternative',
    owner: 'Kitchen In-charge + Teacher',
  },
  {
    ruleId: 'R-OPS-014',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'Nap Time Supervision',
    trigger: 'Daily nap time slot (post-lunch)',
    action: 'Assign supervisor; conduct visual check every 10 min; record nap quality in daily sheet',
    owner: 'Teacher + Nap Supervisor',
  },
  {
    ruleId: 'R-OPS-015',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'Incident Escalation Matrix',
    trigger: 'Any incident reported (injury, illness, behavioral, safety)',
    action: 'Auto-route to appropriate escalation level; incident report generated; mandatory follow-up within 24 hours',
    owner: 'Teacher + Branch Head',
  },
  {
    ruleId: 'R-OPS-016',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'Photo Consent for Marketing',
    trigger: 'Child photo captured for marketing/social media',
    action: 'Flag photos with consent status; AI face-blur applied for non-consenting children in batch photos',
    owner: 'Teacher + Marketing Team',
  },
  {
    ruleId: 'R-OPS-017',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'Daily Timeline Push to Parent',
    trigger: 'Each major daily activity completion (arrival, meal, activity, nap, pickup)',
    action: 'Auto-push timeline entry to parent app with timestamp, photo (if consent), activity description',
    owner: 'System (Automated)',
  },
  {
    ruleId: 'R-OPS-018',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'Food Sample Retention',
    trigger: 'Each meal served (breakfast, lunch, snack)',
    action: 'Auto-label sample with date/meal/quantity; dispose after 48 hours; log retention + disposal',
    owner: 'Kitchen In-charge',
  },
  {
    ruleId: 'R-OPS-019',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'Washroom Assistance',
    trigger: 'Child requests washroom break',
    action: 'Assign staff per age group; log washroom visits in daily sheet; monitor frequency for health issues',
    owner: 'Teacher + Care Staff',
  },
  {
    ruleId: 'R-OPS-020',
    domain: 'OPS',
    domainName: 'Operations',
    subDomain: 'Daily Operations & Safety',
    title: 'CCTV Coverage and Retention',
    trigger: 'Daily school operations',
    action: 'Continuous recording; motion-detection alerts in restricted areas; auto-overwrite after 90 days',
    owner: 'Branch Admin + IT',
  },
  {
    ruleId: 'R-ACD-001',
    domain: 'ACD',
    domainName: 'Academics',
    subDomain: 'Curriculum, Assessment, Portfolio',
    title: 'Curriculum Theme Rotation',
    trigger: 'Academic year planning (April)',
    action: 'Auto-create theme calendar; each theme duration 3-4 weeks; activities linked to theme',
    owner: 'Academic Coordinator + Principal',
  },
  {
    ruleId: 'R-ACD-002',
    domain: 'ACD',
    domainName: 'Academics',
    subDomain: 'Curriculum, Assessment, Portfolio',
    title: 'Weekly Lesson Plan Submission',
    trigger: 'Friday end-of-day',
    action: 'Send reminder Friday 5 PM; escalate to Coordinator Saturday 10 AM; Coordinator prepares default plan if not received by Saturday 5 PM',
    owner: 'Teacher + Coordinator',
  },
  {
    ruleId: 'R-ACD-003',
    domain: 'ACD',
    domainName: 'Academics',
    subDomain: 'Curriculum, Assessment, Portfolio',
    title: 'Daily Activity Slots',
    trigger: 'Daily school day start',
    action: 'Enforce minimum activities per day; system warns if teacher marks fewer activities',
    owner: 'Teacher + Coordinator',
  },
  {
    ruleId: 'R-ACD-004',
    domain: 'ACD',
    domainName: 'Academics',
    subDomain: 'Curriculum, Assessment, Portfolio',
    title: 'Observation Recording Frequency',
    trigger: 'Daily observation window',
    action: 'Friday summary: list of children with missing observations; teacher must complete by Saturday EOD',
    owner: 'Teacher + Coordinator',
  },
  {
    ruleId: 'R-ACD-005',
    domain: 'ACD',
    domainName: 'Academics',
    subDomain: 'Curriculum, Assessment, Portfolio',
    title: 'Observation Quality Check',
    trigger: 'Observation saved by teacher',
    action: 'Prompt teacher to expand observation; weekly review by Coordinator; recurring low-quality triggers coaching',
    owner: 'Teacher + Coordinator',
  },
  {
    ruleId: 'R-ACD-006',
    domain: 'ACD',
    domainName: 'Academics',
    subDomain: 'Curriculum, Assessment, Portfolio',
    title: 'Milestone Assessment Frequency',
    trigger: 'Quarterly milestone cycle',
    action: 'Generate assessment templates per age group; teachers complete within 2 weeks; parents get milestone report',
    owner: 'Teacher + Coordinator',
  },
  {
    ruleId: 'R-ACD-007',
    domain: 'ACD',
    domainName: 'Academics',
    subDomain: 'Curriculum, Assessment, Portfolio',
    title: 'Milestone Delay Alert',
    trigger: 'Milestone assessment completion',
    action: 'Auto-flag; parent-teacher meeting scheduled within 14 days; if developmental concern, recommend specialist assessment',
    owner: 'Teacher + Principal + Parent',
  },
  {
    ruleId: 'R-ACD-008',
    domain: 'ACD',
    domainName: 'Academics',
    subDomain: 'Curriculum, Assessment, Portfolio',
    title: 'Portfolio Update Cadence',
    trigger: 'Monthly portfolio cycle',
    action: 'Auto-compile portfolio entries (observations, photos, artwork, milestone progress); share with parent via app',
    owner: 'Teacher + System (Automated)',
  },
  {
    ruleId: 'R-ACD-009',
    domain: 'ACD',
    domainName: 'Academics',
    subDomain: 'Curriculum, Assessment, Portfolio',
    title: 'Report Card Generation Cycle',
    trigger: 'Term end (October + April)',
    action: 'AI-assisted draft (combines observations, milestones, activities); teacher review + edit; parent notification + app push',
    owner: 'Teacher + Principal',
  },
  {
    ruleId: 'R-ACD-010',
    domain: 'ACD',
    domainName: 'Academics',
    subDomain: 'Curriculum, Assessment, Portfolio',
    title: 'Report Card Approval Workflow',
    trigger: 'Teacher submits report card',
    action: 'Multi-level approval workflow; locked once approved; parent release after final approval',
    owner: 'Teacher + Coordinator + Principal',
  },
  {
    ruleId: 'R-ACD-011',
    domain: 'ACD',
    domainName: 'Academics',
    subDomain: 'Curriculum, Assessment, Portfolio',
    title: 'Promotion Criteria',
    trigger: 'Annual promotion cycle (March-April)',
    action: 'Auto-promote; update student record; notify parent; assign to next class section',
    owner: 'Principal + Teacher',
  },
  {
    ruleId: 'R-ACD-012',
    domain: 'ACD',
    domainName: 'Academics',
    subDomain: 'Curriculum, Assessment, Portfolio',
    title: 'Age-Based Class Cap',
    trigger: 'Promotion cycle',
    action: 'Flag for Principal review; parent meeting; may recommend transition to mainstream school (Sr.KG → Grade 1)',
    owner: 'Principal + Parent',
  },
  {
    ruleId: 'R-ACD-013',
    domain: 'ACD',
    domainName: 'Academics',
    subDomain: 'Curriculum, Assessment, Portfolio',
    title: 'PTM Frequency',
    trigger: 'Quarterly PTM cycle',
    action: 'Auto-schedule PTM; parent invites via app + SMS; teacher prepares child progress summary; PTM attendance logged',
    owner: 'Teacher + Coordinator',
  },
  {
    ruleId: 'R-ACD-014',
    domain: 'ACD',
    domainName: 'Academics',
    subDomain: 'Curriculum, Assessment, Portfolio',
    title: 'Remedial Program Trigger',
    trigger: 'Milestone assessment OR teacher observation',
    action: 'Auto-enroll in 4-week remedial track; weekly progress monitoring; specialist consultation if no improvement',
    owner: 'Teacher + Special Educator + Parent',
  },
  {
    ruleId: 'R-ACD-015',
    domain: 'ACD',
    domainName: 'Academics',
    subDomain: 'Curriculum, Assessment, Portfolio',
    title: 'Outdoor Play Duration',
    trigger: 'Daily schedule',
    action: 'Enforce minimum outdoor time in daily schedule; if weather prevents, indoor gross-motor activities substitute',
    owner: 'Teacher + Coordinator',
  },
  {
    ruleId: 'R-ACD-016',
    domain: 'ACD',
    domainName: 'Academics',
    subDomain: 'Curriculum, Assessment, Portfolio',
    title: 'Activity Participation Tracking',
    trigger: 'Each activity completion',
    action: 'Prompt teacher to log reason (mood, health, social); if pattern persists, parent notification',
    owner: 'Teacher',
  },
  {
    ruleId: 'R-ACD-017',
    domain: 'ACD',
    domainName: 'Academics',
    subDomain: 'Curriculum, Assessment, Portfolio',
    title: 'Annual Curriculum Audit',
    trigger: 'End of academic year (April)',
    action: 'Committee meeting in May; revised curriculum approved by June; new theme calendar published',
    owner: 'Principal + Academic Committee',
  },
  {
    ruleId: 'R-ACD-018',
    domain: 'ACD',
    domainName: 'Academics',
    subDomain: 'Curriculum, Assessment, Portfolio',
    title: 'Field Trip Safety Protocol',
    trigger: 'Field trip planned',
    action: 'Block trip if any criterion fails; generate permission slips; pre-trip safety briefing; post-trip report',
    owner: 'Coordinator + Branch Head',
  },
  {
    ruleId: 'R-HR-001',
    domain: 'HR',
    domainName: 'HR',
    subDomain: 'Staff Lifecycle & Compliance',
    title: 'Staff Qualification Minimum',
    trigger: 'New staff onboarding',
    action: 'Mandatory qualification verification; reject if not met; document reason',
    owner: 'HR + Principal',
  },
  {
    ruleId: 'R-HR-002',
    domain: 'HR',
    domainName: 'HR',
    subDomain: 'Staff Lifecycle & Compliance',
    title: 'Staff Background Verification',
    trigger: 'New staff onboarding (post-offer, pre-joining)',
    action: 'Mandatory: police verification (within 30 days), 2 reference checks, previous employer verification, address proof',
    owner: 'HR + Branch Head',
  },
  {
    ruleId: 'R-HR-003',
    domain: 'HR',
    domainName: 'HR',
    subDomain: 'Staff Lifecycle & Compliance',
    title: 'Leave Entitlement Annual',
    trigger: 'Annual leave cycle (April-March)',
    action: 'Auto-credit leave balance on April 1; carry forward max 5 earned leaves',
    owner: 'HR + Staff',
  },
  {
    ruleId: 'R-HR-004',
    domain: 'HR',
    domainName: 'HR',
    subDomain: 'Staff Lifecycle & Compliance',
    title: 'Max Consecutive Leave',
    trigger: 'Leave application submitted',
    action: 'Route to appropriate approver; ensure substitute teacher arrangement for teaching staff',
    owner: 'HR + Branch Head',
  },
  {
    ruleId: 'R-HR-005',
    domain: 'HR',
    domainName: 'HR',
    subDomain: 'Staff Lifecycle & Compliance',
    title: 'Substitute Teacher Assignment',
    trigger: 'Teacher absence (approved leave or unplanned)',
    action: 'Auto-assign from substitute pool; if unavailable, Coordinator covers; parent notification if delay >30 min',
    owner: 'Coordinator + HR',
  },
  {
    ruleId: 'R-HR-006',
    domain: 'HR',
    domainName: 'HR',
    subDomain: 'Staff Lifecycle & Compliance',
    title: 'Payroll Cutoff Date',
    trigger: 'Monthly payroll cycle',
    action: 'Lock attendance on 25th EOD; process payroll 26-28; final review 29th; disbursement 30th',
    owner: 'HR + Accounts',
  },
  {
    ruleId: 'R-HR-007',
    domain: 'HR',
    domainName: 'HR',
    subDomain: 'Staff Lifecycle & Compliance',
    title: 'Performance Review Cycle',
    trigger: 'Annual performance cycle (March-April)',
    action: 'Self-appraisal (March 1-15); reviewer appraisal (March 16-31); calibration (April 1-7); feedback (April 8-15)',
    owner: 'HR + Reporting Manager',
  },
  {
    ruleId: 'R-HR-008',
    domain: 'HR',
    domainName: 'HR',
    subDomain: 'Staff Lifecycle & Compliance',
    title: 'Exit Process',
    trigger: 'Staff submits resignation',
    action: 'Mandatory: notice period (60 days full-time, 30 days part-time); handover document; exit interview; final settlement within 30 days',
    owner: 'HR + Branch Head',
  },
  {
    ruleId: 'R-HR-009',
    domain: 'HR',
    domainName: 'HR',
    subDomain: 'Staff Lifecycle & Compliance',
    title: 'Internal Complaints Committee (ICC)',
    trigger: 'Annual ICC constitution (April)',
    action: 'Constitute ICC; publish committee details on notice board + employee handbook; annual training',
    owner: 'HR + Director',
  },
  {
    ruleId: 'R-HR-010',
    domain: 'HR',
    domainName: 'HR',
    subDomain: 'Staff Lifecycle & Compliance',
    title: 'Annual POSH Training',
    trigger: 'Annual training cycle (April-May)',
    action: 'Online POSH module; quiz with 80% pass mark; certificate valid 1 year; non-completion blocks payroll',
    owner: 'HR + Compliance Officer',
  },
  {
    ruleId: 'R-HR-011',
    domain: 'HR',
    domainName: 'HR',
    subDomain: 'Staff Lifecycle & Compliance',
    title: 'Food Handler Medical Certificate',
    trigger: 'Kitchen staff onboarding + annual renewal',
    action: 'Annual medical checkup; certificate on file; non-completion blocks kitchen duties',
    owner: 'HR + Kitchen In-charge',
  },
  {
    ruleId: 'R-HR-012',
    domain: 'HR',
    domainName: 'HR',
    subDomain: 'Staff Lifecycle & Compliance',
    title: 'Probation Period',
    trigger: 'New staff joining',
    action: 'Probation review at end of period; confirmation OR extension (max 6 months) OR termination',
    owner: 'HR + Reporting Manager',
  },
  {
    ruleId: 'R-INV-001',
    domain: 'INV',
    domainName: 'Inventory',
    subDomain: 'Stock, PO, Asset, Disposal',
    title: 'Auto Reorder Trigger',
    trigger: 'Stock level update (post-issue / post-GRN)',
    action: 'Create PR with vendor suggestion; route to Branch Admin approval; auto-set expected delivery date',
    owner: 'Inventory Manager + Branch Admin',
  },
  {
    ruleId: 'R-INV-002',
    domain: 'INV',
    domainName: 'Inventory',
    subDomain: 'Stock, PO, Asset, Disposal',
    title: 'Minimum Stock Threshold',
    trigger: 'Daily stock reconciliation',
    action: 'Send P0 alert to Inventory Manager + Branch Admin; emergency procurement process',
    owner: 'Inventory Manager',
  },
  {
    ruleId: 'R-INV-003',
    domain: 'INV',
    domainName: 'Inventory',
    subDomain: 'Stock, PO, Asset, Disposal',
    title: 'Perishable Item Expiry Tracking',
    trigger: 'GRN for perishable item (food, paint, glue)',
    action: 'FIFO issuance: oldest stock issued first; expiring items flagged in kitchen / classroom dashboard',
    owner: 'Inventory Manager + Kitchen In-charge',
  },
  {
    ruleId: 'R-INV-004',
    domain: 'INV',
    domainName: 'Inventory',
    subDomain: 'Stock, PO, Asset, Disposal',
    title: 'Expired Item Disposal',
    trigger: 'Item crosses expiry date',
    action: 'Mark item as \'Expired - Dispose\'; generate disposal log; Inventory Manager + Branch Head joint approval for write-off',
    owner: 'Inventory Manager + Branch Head',
  },
  {
    ruleId: 'R-INV-005',
    domain: 'INV',
    domainName: 'Inventory',
    subDomain: 'Stock, PO, Asset, Disposal',
    title: 'Asset Depreciation',
    trigger: 'Annual financial closure (March)',
    action: 'Auto-calculate depreciation; update asset register; reflect in balance sheet',
    owner: 'Accounts + Inventory Manager',
  },
  {
    ruleId: 'R-INV-006',
    domain: 'INV',
    domainName: 'Inventory',
    subDomain: 'Stock, PO, Asset, Disposal',
    title: 'Vendor Rating Threshold',
    trigger: 'Quarterly vendor review',
    action: 'Notify vendor; 90-day improvement period; if no improvement, black-list + remove from preferred list',
    owner: 'Inventory Manager + Branch Head',
  },
  {
    ruleId: 'R-INV-007',
    domain: 'INV',
    domainName: 'Inventory',
    subDomain: 'Stock, PO, Asset, Disposal',
    title: 'PO Approval Threshold',
    trigger: 'Purchase Order creation',
    action: 'Multi-level approval workflow; auto-route based on amount; locked after final approval',
    owner: 'Inventory Manager + Multi-level Approvers',
  },
  {
    ruleId: 'R-INV-008',
    domain: 'INV',
    domainName: 'Inventory',
    subDomain: 'Stock, PO, Asset, Disposal',
    title: 'Issue Slip Mandatory',
    trigger: 'Inventory item issued to classroom / kitchen / admin',
    action: 'Mandatory digital issue slip with: item, qty, recipient, date, purpose; recipient acknowledges via app',
    owner: 'Inventory Manager + Recipient',
  },
  {
    ruleId: 'R-INV-009',
    domain: 'INV',
    domainName: 'Inventory',
    subDomain: 'Stock, PO, Asset, Disposal',
    title: 'Stock Audit Frequency',
    trigger: 'Quarterly audit cycle',
    action: 'Physical count; reconcile with system; variance >5% triggers investigation; Branch Head approval for adjustments',
    owner: 'Inventory Manager + Branch Head',
  },
  {
    ruleId: 'R-INV-010',
    domain: 'INV',
    domainName: 'Inventory',
    subDomain: 'Stock, PO, Asset, Disposal',
    title: 'Return Window',
    trigger: 'Item return request',
    action: 'Generate return note; vendor pickup arranged; credit note raised',
    owner: 'Inventory Manager',
  },
  {
    ruleId: 'R-INV-011',
    domain: 'INV',
    domainName: 'Inventory',
    subDomain: 'Stock, PO, Asset, Disposal',
    title: 'Consumption Tracking',
    trigger: 'Daily issue / use',
    action: 'Auto-aggregate monthly consumption; variance >20% from average triggers review',
    owner: 'Inventory Manager + Coordinator',
  },
  {
    ruleId: 'R-INV-012',
    domain: 'INV',
    domainName: 'Inventory',
    subDomain: 'Stock, PO, Asset, Disposal',
    title: 'Asset Disposal Approval',
    trigger: 'Asset disposal request',
    action: 'Disposal: sale / scrap / donation; document disposal method; remove from asset register; adjust books',
    owner: 'Inventory Manager + Director',
  },
  {
    ruleId: 'R-COM-001',
    domain: 'COM',
    domainName: 'Communication',
    subDomain: 'Messaging, Announcement, Chat',
    title: 'Parent Message Response Time',
    trigger: 'Parent sends message via app',
    action: 'Auto-acknowledge receipt; assign to class teacher; escalate to Coordinator if no response within SLA',
    owner: 'Teacher + Coordinator',
  },
  {
    ruleId: 'R-COM-002',
    domain: 'COM',
    domainName: 'Communication',
    subDomain: 'Messaging, Announcement, Chat',
    title: 'Unacknowledged Message Escalation',
    trigger: 'Message unacknowledged beyond SLA',
    action: 'Auto-escalate; notify next-level via app + SMS; log escalation chain',
    owner: 'System (Automated) + Coordinator',
  },
  {
    ruleId: 'R-COM-003',
    domain: 'COM',
    domainName: 'Communication',
    subDomain: 'Messaging, Announcement, Chat',
    title: 'Non-Academic Hour Messaging Restriction',
    trigger: 'Teacher attempts to send parent message outside school hours',
    action: 'Show warning; teacher confirms urgent OR defers to next working day',
    owner: 'Teacher + System (Automated)',
  },
  {
    ruleId: 'R-COM-004',
    domain: 'COM',
    domainName: 'Communication',
    subDomain: 'Messaging, Announcement, Chat',
    title: 'Broadcast Restriction',
    trigger: 'User attempts broadcast message',
    action: 'Block broadcast; route to authorized role for approval; pre-approved templates only',
    owner: 'Branch Head + IT',
  },
  {
    ruleId: 'R-COM-005',
    domain: 'COM',
    domainName: 'Communication',
    subDomain: 'Messaging, Announcement, Chat',
    title: 'Language Preference',
    trigger: 'Parent onboarding / message send',
    action: 'AI translation applied; teacher reviews before send; parent reads in preferred language',
    owner: 'Teacher + System (AI)',
  },
  {
    ruleId: 'R-COM-006',
    domain: 'COM',
    domainName: 'Communication',
    subDomain: 'Messaging, Announcement, Chat',
    title: 'Marketing Communication Opt-in',
    trigger: 'Marketing message send',
    action: 'Filter marketing audience; send only to opted-in parents; honor opt-out within 24 hours',
    owner: 'Marketing + Compliance',
  },
  {
    ruleId: 'R-COM-007',
    domain: 'COM',
    domainName: 'Communication',
    subDomain: 'Messaging, Announcement, Chat',
    title: 'Communication Channel Opt-out',
    trigger: 'Parent updates communication preferences',
    action: 'Update preferences within 24 hours; route via remaining channels; confirmation to parent',
    owner: 'System (Automated) + Parent',
  },
  {
    ruleId: 'R-COM-008',
    domain: 'COM',
    domainName: 'Communication',
    subDomain: 'Messaging, Announcement, Chat',
    title: 'Announcement Approval Workflow',
    trigger: 'Branch-wide announcement creation',
    action: 'Route to approver; preview + edit; scheduled send after approval',
    owner: 'Branch Head + Coordinator',
  },
  {
    ruleId: 'R-COM-009',
    domain: 'COM',
    domainName: 'Communication',
    subDomain: 'Messaging, Announcement, Chat',
    title: 'Photo Caption Mandatory',
    trigger: 'Photo uploaded to parent app',
    action: 'Require caption (min 5 chars) describing context; AI suggests auto-caption; teacher edits',
    owner: 'Teacher + System (AI)',
  },
  {
    ruleId: 'R-COM-010',
    domain: 'COM',
    domainName: 'Communication',
    subDomain: 'Messaging, Announcement, Chat',
    title: 'Two-way Chat History Retention',
    trigger: 'Chat message sent / received',
    action: 'Auto-archive; encrypted storage; parent can access own chat history; audit access for staff',
    owner: 'System (Automated) + Compliance',
  },
  {
    ruleId: 'R-COM-011',
    domain: 'COM',
    domainName: 'Communication',
    subDomain: 'Messaging, Announcement, Chat',
    title: 'WhatsApp Business API Rate Limit',
    trigger: 'WhatsApp message send',
    action: 'Enforce rate limit; queue non-urgent messages for next day; urgent overrides allowed',
    owner: 'System (Automated)',
  },
  {
    ruleId: 'R-COM-012',
    domain: 'COM',
    domainName: 'Communication',
    subDomain: 'Messaging, Announcement, Chat',
    title: 'Emergency Notification Cascade',
    trigger: 'Emergency declared (fire, medical, security)',
    action: 'Trigger cascade within 60 seconds; confirm receipt per parent; escalate non-acknowledged to phone call',
    owner: 'Branch Head + System (Automated)',
  },
  {
    ruleId: 'R-CMP-001',
    domain: 'CMP',
    domainName: 'Compliance',
    subDomain: 'Consent, PII, POSH, Fire, FSSAI',
    title: 'Parent Consent for Child Data',
    trigger: 'Admission confirmation',
    action: 'Capture digital consent with timestamp + IP + device; store in immutable consent ledger; parent can view consents in app',
    owner: 'Admission Counsellor + Compliance Officer',
  },
  {
    ruleId: 'R-CMP-002',
    domain: 'CMP',
    domainName: 'Compliance',
    subDomain: 'Consent, PII, POSH, Fire, FSSAI',
    title: 'Consent Withdrawal',
    trigger: 'Parent withdraws consent via app',
    action: 'Honor withdrawal within 24 hours; stop data collection for withdrawn purpose; retain data already collected per retention policy; notify child of withdrawal (if age-appropriate)',
    owner: 'Compliance Officer + System (Automated)',
  },
  {
    ruleId: 'R-CMP-003',
    domain: 'CMP',
    domainName: 'Compliance',
    subDomain: 'Consent, PII, POSH, Fire, FSSAI',
    title: 'Child Data Retention Policy',
    trigger: 'Student exits school (graduation/withdrawal)',
    action: 'Auto-archive student record; apply retention schedule; auto-delete past retention period; parent notified pre-deletion',
    owner: 'Compliance Officer + IT',
  },
  {
    ruleId: 'R-CMP-004',
    domain: 'CMP',
    domainName: 'Compliance',
    subDomain: 'Consent, PII, POSH, Fire, FSSAI',
    title: 'Child Photo Storage Encryption',
    trigger: 'Photo captured / uploaded',
    action: 'Encrypt on upload; CDN delivery with signed URLs; auto-expire access URLs; log all access',
    owner: 'IT + Compliance',
  },
  {
    ruleId: 'R-CMP-005',
    domain: 'CMP',
    domainName: 'Compliance',
    subDomain: 'Consent, PII, POSH, Fire, FSSAI',
    title: 'CCTV Retention Period',
    trigger: 'CCTV recording in progress',
    action: 'Continuous loop recording; motion-detected incidents flagged; flagged footage moved to long-term encrypted archive',
    owner: 'IT + Branch Admin',
  },
  {
    ruleId: 'R-CMP-006',
    domain: 'CMP',
    domainName: 'Compliance',
    subDomain: 'Consent, PII, POSH, Fire, FSSAI',
    title: 'Quarterly PII Audit',
    trigger: 'Quarterly audit cycle',
    action: 'Generate PII access logs; compliance officer reviews anomalies; report to management; corrective actions',
    owner: 'Compliance Officer + IT',
  },
  {
    ruleId: 'R-CMP-007',
    domain: 'CMP',
    domainName: 'Compliance',
    subDomain: 'Consent, PII, POSH, Fire, FSSAI',
    title: 'Fire NOC Renewal',
    trigger: 'Annual fire NOC expiry (November)',
    action: 'Apply to local fire department; schedule inspection; receive renewed NOC; upload to compliance store',
    owner: 'Branch Admin + Compliance',
  },
  {
    ruleId: 'R-CMP-008',
    domain: 'CMP',
    domainName: 'Compliance',
    subDomain: 'Consent, PII, POSH, Fire, FSSAI',
    title: 'Data Breach Notification',
    trigger: 'Data breach detected (anomaly / unauthorized access)',
    action: 'Trigger breach response plan; forensic investigation; notification template; remediation tracking',
    owner: 'Compliance Officer + IT + Director',
  },
  {
    ruleId: 'R-CMP-009',
    domain: 'CMP',
    domainName: 'Compliance',
    subDomain: 'Consent, PII, POSH, Fire, FSSAI',
    title: 'POSH Complaint Filing',
    trigger: 'Staff files POSH complaint (via app / email / in-person)',
    action: 'Confidential intake; ICC constituted; inquiry process; written report; action within 60 days of report',
    owner: 'ICC + HR',
  },
  {
    ruleId: 'R-CMP-010',
    domain: 'CMP',
    domainName: 'Compliance',
    subDomain: 'Consent, PII, POSH, Fire, FSSAI',
    title: 'POSH Confidentiality',
    trigger: 'POSH complaint in process',
    action: 'Access control list enforced; audit log of all access; breach of confidentiality = separate offense',
    owner: 'ICC + IT',
  },
  {
    ruleId: 'R-CMP-011',
    domain: 'CMP',
    domainName: 'Compliance',
    subDomain: 'Consent, PII, POSH, Fire, FSSAI',
    title: 'POSH Training for All Staff',
    trigger: 'Annual POSH training cycle (April-May)',
    action: 'Online module; quiz; certificate; non-completion blocks payroll (R-HR-010)',
    owner: 'HR + Compliance',
  },
  {
    ruleId: 'R-CMP-012',
    domain: 'CMP',
    domainName: 'Compliance',
    subDomain: 'Consent, PII, POSH, Fire, FSSAI',
    title: 'POSH Complaint Timeline',
    trigger: 'POSH complaint filed',
    action: 'Auto-track timeline; alerts at 60 days (inquiry half-way), 80 days (inquiry near-due), 90 days (final)',
    owner: 'ICC',
  },
  {
    ruleId: 'R-CMP-013',
    domain: 'CMP',
    domainName: 'Compliance',
    subDomain: 'Consent, PII, POSH, Fire, FSSAI',
    title: 'Quarterly Fire Drill',
    trigger: 'Quarterly fire drill cycle',
    action: 'Schedule drill; conduct with timing; document attendance; report to local fire dept (annual submission)',
    owner: 'Branch Admin + Compliance',
  },
  {
    ruleId: 'R-CMP-014',
    domain: 'CMP',
    domainName: 'Compliance',
    subDomain: 'Consent, PII, POSH, Fire, FSSAI',
    title: 'Fire Extinguisher Inspection',
    trigger: 'Monthly fire safety inspection',
    action: 'Monthly visual inspection; annual third-party inspection; refill/replacement tracking',
    owner: 'Branch Admin + Inventory',
  },
  {
    ruleId: 'R-CMP-015',
    domain: 'CMP',
    domainName: 'Compliance',
    subDomain: 'Consent, PII, POSH, Fire, FSSAI',
    title: 'Evacuation Plan Display',
    trigger: 'Annual evacuation plan update',
    action: 'Display floor-wise evacuation plan; multi-language (English + local language); Braille if special needs students',
    owner: 'Branch Admin',
  },
  {
    ruleId: 'R-CMP-016',
    domain: 'CMP',
    domainName: 'Compliance',
    subDomain: 'Consent, PII, POSH, Fire, FSSAI',
    title: 'RTE Non-Discrimination',
    trigger: 'EWS student enrolled under RTE §12',
    action: 'System flags EWS students for non-discrimination monitoring; anonymous audit quarterly',
    owner: 'Principal + Compliance',
  },
  {
    ruleId: 'R-CMP-017',
    domain: 'CMP',
    domainName: 'Compliance',
    subDomain: 'Consent, PII, POSH, Fire, FSSAI',
    title: 'FSSAI Kitchen License',
    trigger: 'Annual FSSAI license renewal',
    action: 'Renew license before expiry; display license in kitchen; monthly self-audit per FSSAI checklist',
    owner: 'Kitchen In-charge + Compliance',
  },
  {
    ruleId: 'R-CMP-018',
    domain: 'CMP',
    domainName: 'Compliance',
    subDomain: 'Consent, PII, POSH, Fire, FSSAI',
    title: 'Food Handler Medical Certificate',
    trigger: 'Kitchen staff onboarding + annual renewal',
    action: 'Annual medical checkup; stool/urine test; certificate on file; non-completion blocks duty',
    owner: 'HR + Kitchen In-charge',
  },
  {
    ruleId: 'R-APR-001',
    domain: 'APR',
    domainName: 'Approvals',
    subDomain: 'Approval Matrices & Escalations',
    title: 'Discount Approval by Amount',
    trigger: 'Discount applied to invoice',
    action: 'Auto-route to approver; multi-level workflow if escalation; locked after approval',
    owner: 'Accounts Team + Multi-level Approvers',
  },
  {
    ruleId: 'R-APR-002',
    domain: 'APR',
    domainName: 'Approvals',
    subDomain: 'Approval Matrices & Escalations',
    title: 'Refund Approval Matrix',
    trigger: 'Refund request submitted',
    action: 'Multi-level workflow; finance verification; bank account validation; payment within 14 days',
    owner: 'Accounts Team + Multi-level Approvers',
  },
  {
    ruleId: 'R-APR-003',
    domain: 'APR',
    domainName: 'Approvals',
    subDomain: 'Approval Matrices & Escalations',
    title: 'Leave Approval Matrix',
    trigger: 'Leave application submitted',
    action: 'Auto-route; ensure substitute arrangement for teachers; lock on approval',
    owner: 'Reporting Manager + Multi-level Approvers',
  },
  {
    ruleId: 'R-APR-004',
    domain: 'APR',
    domainName: 'Approvals',
    subDomain: 'Approval Matrices & Escalations',
    title: 'Expense Approval by Amount',
    trigger: 'Expense claim submitted',
    action: 'Multi-level workflow; receipt verification; GST compliance check; payment scheduling',
    owner: 'Accounts Team + Multi-level Approvers',
  },
  {
    ruleId: 'R-APR-005',
    domain: 'APR',
    domainName: 'Approvals',
    subDomain: 'Approval Matrices & Escalations',
    title: 'Vendor Onboarding Approval',
    trigger: 'New vendor registration',
    action: 'Verify GSTIN, PAN, bank account, references; signed contract; system access grant',
    owner: 'Inventory Manager + Multi-level Approvers',
  },
  {
    ruleId: 'R-APR-006',
    domain: 'APR',
    domainName: 'Approvals',
    subDomain: 'Approval Matrices & Escalations',
    title: 'Admission Final Approval',
    trigger: 'Application Form + Documents + Fee submitted',
    action: 'Auto-approve if all criteria met; Branch Head approval if any exception applied; student record created',
    owner: 'Admission Counsellor + Branch Head',
  },
  {
    ruleId: 'R-APR-007',
    domain: 'APR',
    domainName: 'Approvals',
    subDomain: 'Approval Matrices & Escalations',
    title: 'Fee Waiver Approval',
    trigger: 'Fee waiver request submitted with documentation',
    action: 'Multi-level approval; documentation review; valid for current term only',
    owner: 'Multi-level Approvers',
  },
  {
    ruleId: 'R-APR-008',
    domain: 'APR',
    domainName: 'Approvals',
    subDomain: 'Approval Matrices & Escalations',
    title: 'Asset Disposal Approval',
    trigger: 'Asset disposal request',
    action: 'Disposal method (sale/scrap/donation); valuation; book adjustment; NOC for hazardous items',
    owner: 'Inventory Manager + Multi-level Approvers',
  },
  {
    ruleId: 'R-APR-009',
    domain: 'APR',
    domainName: 'Approvals',
    subDomain: 'Approval Matrices & Escalations',
    title: 'Action-Based Role Escalation',
    trigger: 'User attempts action outside role permissions',
    action: 'Auto-route to higher role; original requester notified; audit logged',
    owner: 'System (Automated) + Higher Role',
  },
  {
    ruleId: 'R-APR-010',
    domain: 'APR',
    domainName: 'Approvals',
    subDomain: 'Approval Matrices & Escalations',
    title: 'New Position Approval',
    trigger: 'New position requisition',
    action: 'Job description finalization; HR sourcing; interview panel; offer approval',
    owner: 'Branch Head + Director + HR',
  },
  {
    ruleId: 'R-APR-011',
    domain: 'APR',
    domainName: 'Approvals',
    subDomain: 'Approval Matrices & Escalations',
    title: 'Salary Revision Approval',
    trigger: 'Annual performance review outcome',
    action: 'Multi-level workflow; budget verification; HR record update; payroll adjustment next cycle',
    owner: 'Multi-level Approvers + HR',
  },
  {
    ruleId: 'R-APR-012',
    domain: 'APR',
    domainName: 'Approvals',
    subDomain: 'Approval Matrices & Escalations',
    title: 'School Policy Change Approval',
    trigger: 'Policy revision proposed',
    action: 'Impact analysis; stakeholder consultation; version control; parent communication if parent-facing',
    owner: 'Multi-level Approvers + Compliance',
  },
  {
    ruleId: 'R-APR-013',
    domain: 'APR',
    domainName: 'Approvals',
    subDomain: 'Approval Matrices & Escalations',
    title: 'Bulk Data Export Approval',
    trigger: 'User requests bulk data export (>50 records)',
    action: 'Approval workflow; purpose documentation; data encryption in transit; audit logged',
    owner: 'Compliance Officer + Director',
  },
  {
    ruleId: 'R-APR-014',
    domain: 'APR',
    domainName: 'Approvals',
    subDomain: 'Approval Matrices & Escalations',
    title: 'Vendor Payment Approval',
    trigger: 'Vendor invoice + GRN verified',
    action: 'Multi-level workflow; TDS deduction (R-FIN-017); GST input credit verification; NEFT/RTGS payment',
    owner: 'Accounts Team + Multi-level Approvers',
  },
  {
    ruleId: 'R-APR-015',
    domain: 'APR',
    domainName: 'Approvals',
    subDomain: 'Approval Matrices & Escalations',
    title: 'Curriculum Change Approval',
    trigger: 'Curriculum revision proposed',
    action: 'Review committee; pilot if needed; parent communication; phased rollout',
    owner: 'Principal + Academic Committee',
  },
  {
    ruleId: 'R-NOT-001',
    domain: 'NOT',
    domainName: 'Notifications',
    subDomain: 'Reminder & Alert Cadence',
    title: 'Fee Due Reminder Cadence',
    trigger: 'Invoice due date approaching / overdue',
    action: 'Multi-channel cascade; parent app + SMS + email + WhatsApp; auto-stop after parent acknowledges',
    owner: 'System (Automated) + Accounts Team',
  },
  {
    ruleId: 'R-NOT-002',
    domain: 'NOT',
    domainName: 'Notifications',
    subDomain: 'Reminder & Alert Cadence',
    title: 'Child Absence Alert',
    trigger: 'Child marked absent in attendance',
    action: 'Push + SMS to primary parent; if no ack within 30 min, call primary parent; if unreachable, secondary contact',
    owner: 'System (Automated) + Teacher',
  },
  {
    ruleId: 'R-NOT-003',
    domain: 'NOT',
    domainName: 'Notifications',
    subDomain: 'Reminder & Alert Cadence',
    title: 'Daily Report Push Time',
    trigger: 'Daily school end (pickup)',
    action: 'Auto-compile daily sheet (activities, meals, nap, observations, photos); push to parent app + email',
    owner: 'System (Automated)',
  },
  {
    ruleId: 'R-NOT-004',
    domain: 'NOT',
    domainName: 'Notifications',
    subDomain: 'Reminder & Alert Cadence',
    title: 'Birthday Greeting',
    trigger: 'Child birthday',
    action: 'Customizable template; school logo; photo if consented; small in-app celebration',
    owner: 'System (Automated)',
  },
  {
    ruleId: 'R-NOT-005',
    domain: 'NOT',
    domainName: 'Notifications',
    subDomain: 'Reminder & Alert Cadence',
    title: 'Festival Greeting',
    trigger: 'Public festival day',
    action: 'Multi-language greeting; cultural context; school closure reminder if applicable',
    owner: 'System (Automated) + Branch Admin',
  },
  {
    ruleId: 'R-NOT-006',
    domain: 'NOT',
    domainName: 'Notifications',
    subDomain: 'Reminder & Alert Cadence',
    title: 'Incident Notification',
    trigger: 'Incident reported (R-OPS-015)',
    action: 'Auto-notify based on severity; Branch Head involvement for HIGH; documentation shared via app',
    owner: 'Teacher + Branch Head',
  },
  {
    ruleId: 'R-NOT-007',
    domain: 'NOT',
    domainName: 'Notifications',
    subDomain: 'Reminder & Alert Cadence',
    title: 'Photo Share Alert',
    trigger: 'Teacher shares photo with parent',
    action: 'Push with thumbnail; parent taps to view full; like/comment options; teacher notified of parent engagement',
    owner: 'System (Automated)',
  },
  {
    ruleId: 'R-NOT-008',
    domain: 'NOT',
    domainName: 'Notifications',
    subDomain: 'Reminder & Alert Cadence',
    title: 'Event Schedule Announcement',
    trigger: 'School event scheduled (PTM, sports day, annual day)',
    action: 'Multi-channel: app push + email + SMS for major events; app-only for routine',
    owner: 'Coordinator + System (Automated)',
  },
  {
    ruleId: 'R-NOT-009',
    domain: 'NOT',
    domainName: 'Notifications',
    subDomain: 'Reminder & Alert Cadence',
    title: 'Holiday Alert',
    trigger: 'Public holiday / school-declared holiday',
    action: 'Push + SMS + email; update calendar; reschedule affected activities',
    owner: 'Branch Admin + System (Automated)',
  },
  {
    ruleId: 'R-NOT-010',
    domain: 'NOT',
    domainName: 'Notifications',
    subDomain: 'Reminder & Alert Cadence',
    title: 'Transport Delay Alert',
    trigger: 'Bus delayed > 10 minutes from scheduled time',
    action: 'Push notification with new ETA; live tracking link; auto-update every 5 min',
    owner: 'System (Automated) + Transport In-charge',
  },
  {
    ruleId: 'R-NOT-011',
    domain: 'NOT',
    domainName: 'Notifications',
    subDomain: 'Reminder & Alert Cadence',
    title: 'Salary Credit Notification',
    trigger: 'Payroll disbursement complete',
    action: 'Notification with salary slip attached; bank credit confirmation; tax breakdown',
    owner: 'System (Automated) + HR + Accounts',
  },
  {
    ruleId: 'R-NOT-012',
    domain: 'NOT',
    domainName: 'Notifications',
    subDomain: 'Reminder & Alert Cadence',
    title: 'System Maintenance Notification',
    trigger: 'Scheduled system downtime',
    action: 'Email + app banner; affected features list; expected restoration time; alternate contact (phone) for emergencies',
    owner: 'IT + System (Automated)',
  },
  {
    ruleId: 'R-DAT-001',
    domain: 'DAT',
    domainName: 'Data',
    subDomain: 'PII, Encryption, Retention, DSAR',
    title: 'PII Encryption at Rest',
    trigger: 'PII data stored in database',
    action: 'Field-level encryption; encryption keys in HSM (Hardware Security Module); key rotation quarterly',
    owner: 'IT + Compliance',
  },
  {
    ruleId: 'R-DAT-002',
    domain: 'DAT',
    domainName: 'Data',
    subDomain: 'PII, Encryption, Retention, DSAR',
    title: 'Data in Transit Encryption',
    trigger: 'Data transmission over network',
    action: 'All API calls over HTTPS; certificate pinning for mobile apps; HSTS enabled; mixed-content blocked',
    owner: 'IT',
  },
  {
    ruleId: 'R-DAT-003',
    domain: 'DAT',
    domainName: 'Data',
    subDomain: 'PII, Encryption, Retention, DSAR',
    title: 'PII Field Masking in UI',
    trigger: 'PII field displayed in user interface',
    action: 'Auto-mask in lists, exports, logs; full view only with explicit permission + audit log',
    owner: 'IT + System (Automated)',
  },
  {
    ruleId: 'R-DAT-004',
    domain: 'DAT',
    domainName: 'Data',
    subDomain: 'PII, Encryption, Retention, DSAR',
    title: 'Role-Based Field Visibility',
    trigger: 'User requests data access',
    action: 'Enforce at API layer; deny by default; allow only explicitly granted; audit logged',
    owner: 'IT + Compliance',
  },
  {
    ruleId: 'R-DAT-005',
    domain: 'DAT',
    domainName: 'Data',
    subDomain: 'PII, Encryption, Retention, DSAR',
    title: 'Audit Log Retention',
    trigger: 'User action on PII data',
    action: 'Immutable audit log; WORM (Write Once Read Many) storage; quarterly compliance review',
    owner: 'IT + Compliance',
  },
  {
    ruleId: 'R-DAT-006',
    domain: 'DAT',
    domainName: 'Data',
    subDomain: 'PII, Encryption, Retention, DSAR',
    title: 'Data Residency — India Only',
    trigger: 'Cloud infrastructure setup / data storage',
    action: 'All primary data in India regions; backups in India; DR site in different India region',
    owner: 'IT + Compliance',
  },
  {
    ruleId: 'R-DAT-007',
    domain: 'DAT',
    domainName: 'Data',
    subDomain: 'PII, Encryption, Retention, DSAR',
    title: 'Data Subject Access Request (DSAR)',
    trigger: 'Parent / staff requests their data via app / email',
    action: 'Compile data package; provide in machine-readable format (JSON/CSV); explain processing purposes',
    owner: 'Compliance Officer + IT',
  },
  {
    ruleId: 'R-DAT-008',
    domain: 'DAT',
    domainName: 'Data',
    subDomain: 'PII, Encryption, Retention, DSAR',
    title: 'Data Erasure Request',
    trigger: 'Parent requests erasure of child data post-exit',
    action: 'Soft-delete from primary store; hard-delete from backups within 90 days; erase from analytics; certificate of erasure',
    owner: 'Compliance Officer + IT',
  },
  {
    ruleId: 'R-DAT-009',
    domain: 'DAT',
    domainName: 'Data',
    subDomain: 'PII, Encryption, Retention, DSAR',
    title: 'Backup Retention Policy',
    trigger: 'Daily backup cycle',
    action: 'Automated backups; encrypted; geographically separated (India region); quarterly restore drills',
    owner: 'IT',
  },
  {
    ruleId: 'R-DAT-010',
    domain: 'DAT',
    domainName: 'Data',
    subDomain: 'PII, Encryption, Retention, DSAR',
    title: 'Breach Detection & Response',
    trigger: 'Anomaly detection / unauthorized access alert',
    action: 'Incident response team activation; forensic capture; containment; eradication; recovery; post-mortem',
    owner: 'IT + Compliance + Director',
  },
  {
    ruleId: 'R-DAT-011',
    domain: 'DAT',
    domainName: 'Data',
    subDomain: 'PII, Encryption, Retention, DSAR',
    title: 'Soft Delete Policy',
    trigger: 'User requests data deletion',
    action: 'Soft-delete immediate; data not visible in UI; restorable within 90 days; auto hard-delete after',
    owner: 'System (Automated) + Compliance',
  },
  {
    ruleId: 'R-DAT-012',
    domain: 'DAT',
    domainName: 'Data',
    subDomain: 'PII, Encryption, Retention, DSAR',
    title: 'Anonymized Analytics Data',
    trigger: 'Data aggregated for analytics / ML training',
    action: 'Anonymization pipeline; statistical disclosure control; re-identification risk assessment',
    owner: 'IT + Data Science + Compliance',
  },
  {
    ruleId: 'R-PLT-001',
    domain: 'PLT',
    domainName: 'Platform',
    subDomain: 'Tenant, Subscription, License, Onboarding',
    title: 'Tenant Data Isolation',
    trigger: 'Every data access query',
    action: 'Enforce at ORM layer (Prisma row-level security); audit log all cross-tenant denial attempts',
    owner: 'IT + Platform Admin',
  },
  {
    ruleId: 'R-PLT-002',
    domain: 'PLT',
    domainName: 'Platform',
    subDomain: 'Tenant, Subscription, License, Onboarding',
    title: 'Subscription Grace Period',
    trigger: 'Subscription renewal overdue',
    action: 'Notify Director + Branch Head + Accounts; restrict features progressively; data archived (read-only) for 90 days post-suspension',
    owner: 'Platform Admin + Accounts',
  },
  {
    ruleId: 'R-PLT-003',
    domain: 'PLT',
    domainName: 'Platform',
    subDomain: 'Tenant, Subscription, License, Onboarding',
    title: 'Tenant Suspension Process',
    trigger: 'Subscription breach / compliance violation / abuse',
    action: 'Notify tenant admin; provide export link; remediation plan; reactivation process documented',
    owner: 'Platform Admin + Director + Legal',
  },
  {
    ruleId: 'R-PLT-004',
    domain: 'PLT',
    domainName: 'Platform',
    subDomain: 'Tenant, Subscription, License, Onboarding',
    title: 'Feature Flag per Tier',
    trigger: 'Tenant onboarding / plan upgrade',
    action: 'Auto-enable features per tier; hide restricted features in UI; upgrade triggers feature unlock',
    owner: 'Platform Admin + Product',
  },
  {
    ruleId: 'R-PLT-005',
    domain: 'PLT',
    domainName: 'Platform',
    subDomain: 'Tenant, Subscription, License, Onboarding',
    title: 'License Seat Allocation',
    trigger: 'User added to tenant',
    action: 'Notify tenant admin; offer seat upgrade; pending user request queued',
    owner: 'Platform Admin + System (Automated)',
  },
  {
    ruleId: 'R-PLT-006',
    domain: 'PLT',
    domainName: 'Platform',
    subDomain: 'Tenant, Subscription, License, Onboarding',
    title: 'Branch-Level Data Partition',
    trigger: 'Multi-branch tenant data access',
    action: 'Enforce branch_id in queries; cross-branch data only for Director role; audit logged',
    owner: 'IT + Compliance',
  },
  {
    ruleId: 'R-PLT-007',
    domain: 'PLT',
    domainName: 'Platform',
    subDomain: 'Tenant, Subscription, License, Onboarding',
    title: 'Platform Admin Role Restrictions',
    trigger: 'Platform admin action',
    action: 'Approval workflow; access request with justification; auto-expire; quarterly compliance review of all admin accesses',
    owner: 'Platform Admin + Director + Compliance',
  },
  {
    ruleId: 'R-PLT-008',
    domain: 'PLT',
    domainName: 'Platform',
    subDomain: 'Tenant, Subscription, License, Onboarding',
    title: 'Cross-Tenant Data Block',
    trigger: 'Any cross-tenant data reference in code',
    action: 'Code-level enforcement (Prisma middleware); deny by default; explicit allowlist for legitimate cross-tenant operations (platform-wide analytics with anonymization)',
    owner: 'IT + Platform Admin',
  },
  {
    ruleId: 'R-PLT-009',
    domain: 'PLT',
    domainName: 'Platform',
    subDomain: 'Tenant, Subscription, License, Onboarding',
    title: 'Tenant Onboarding Validation',
    trigger: 'New tenant registration',
    action: 'KYC verification; GSTIN validation; authorized signatory OTP; initial subscription payment',
    owner: 'Platform Admin + Sales',
  },
  {
    ruleId: 'R-PLT-010',
    domain: 'PLT',
    domainName: 'Platform',
    subDomain: 'Tenant, Subscription, License, Onboarding',
    title: 'Tenant Offboarding Process',
    trigger: 'Tenant cancellation request',
    action: 'Final invoice settlement; data export link (30-day validity); tenant deactivation; data archived 90 days; permanent deletion after',
    owner: 'Platform Admin + Accounts + Compliance',
  },
];

/** Lookup map: ruleId -> BrcRule. */
export const BRC_RULE_MAP: ReadonlyMap<string, BrcRule> = new Map(
  BRC_RULES.map((r) => [r.ruleId, r]),
);

/** Get a rule by ID (returns undefined if not found). */
export function getBrcRule(ruleId: string): BrcRule | undefined {
  return BRC_RULE_MAP.get(ruleId);
}

/** Returns true iff `ruleId` exists in the catalog. */
export function isValidBrcRuleId(ruleId: string): boolean {
  return BRC_RULE_MAP.has(ruleId);
}

/** All catalog rule IDs (sorted). */
export const BRC_RULE_IDS: readonly string[] = BRC_RULES.map((r) => r.ruleId);
