-- PreOne Wave 23.02 — Cross-cutting enums (replace Wave 13 placeholders)
-- =====================================================================
-- Migration ID: 20260717000002_wave_23_02_cross_cutting_enums
-- Wave: 23
-- Idempotent: YES (uses CREATE TYPE/TABLE IF NOT EXISTS, DROP IF EXISTS)
--
-- Replaces the 50 placeholder enums from the Wave 13 v3 completion migration
with real values extracted from packages/database/prisma/cross_cutting.prisma.

Each enum is DROP-then-CREATE (idempotent) so that the original 'PLACEHOLDER'
value is discarded. Replaced 50 of 50 enums
from the original Wave 13 stub. Missing: none.
--
-- Conventions (per ERD v3.0 §3 + BTD §16):
--   - Tables: snake_case plural
--   - Columns: snake_case
--   - PKs: UUID v7 (time-sortable)
--   - Timestamps: timestamptz
--   - Money: integer cents (amount_cents) — never float
--   - Soft delete: deleted_at timestamptz NULL
--   - Optimistic concurrency: version INTEGER DEFAULT 1
--   - Tenant isolation: school_id discriminator + RLS policy
--   - Audit columns: created_at, created_by, updated_at, updated_by,
--                    deleted_at, deleted_by
--
-- This migration is auto-generated by scripts/wave23_migrations_gen.py.
-- Do not edit by hand — re-run the script instead.

-- Replaces 50 PLACEHOLDER enums from Wave 13 v3 completion migration
-- (20260716000006_wave_13_database_v3_completion/migration.sql).
-- Each enum is DROP-then-CREATE to ensure real values replace PLACEHOLDER.
-- Real values are sourced from packages/database/prisma/cross_cutting.prisma.


-- Enum: ActivityType (10 values)
DROP TYPE IF EXISTS "ActivityType";
CREATE TYPE "ActivityType" AS ENUM ('INDOOR', 'OUTDOOR', 'GROUP', 'INDIVIDUAL', 'WATER_PLAY', 'ART', 'MUSIC', 'STORY', 'FREE_PLAY', 'STRUCTURED');
COMMENT ON TYPE "ActivityType" IS 'Wave 23 — activity_type enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: BackupStatus (5 values)
DROP TYPE IF EXISTS "BackupStatus";
CREATE TYPE "BackupStatus" AS ENUM ('STARTED', 'COMPLETED', 'FAILED', 'VERIFIED', 'EXPIRED');
COMMENT ON TYPE "BackupStatus" IS 'Wave 23 — backup_status enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: BroadcastType (7 values)
DROP TYPE IF EXISTS "BroadcastType";
CREATE TYPE "BroadcastType" AS ENUM ('ANNOUNCEMENT', 'ALERT', 'EVENT', 'NEWSLETTER', 'HOLIDAY', 'EMERGENCY', 'REMINDER');
COMMENT ON TYPE "BroadcastType" IS 'Wave 23 — broadcast_type enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: ChatMessageType (8 values)
DROP TYPE IF EXISTS "ChatMessageType";
CREATE TYPE "ChatMessageType" AS ENUM ('TEXT', 'IMAGE', 'FILE', 'AUDIO', 'VIDEO', 'LOCATION', 'CONTACT', 'SYSTEM');
COMMENT ON TYPE "ChatMessageType" IS 'Wave 23 — chat_message_type enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: ChatRoomType (6 values)
DROP TYPE IF EXISTS "ChatRoomType";
CREATE TYPE "ChatRoomType" AS ENUM ('DIRECT', 'GROUP', 'BROADCAST', 'SUPPORT', 'CLASS_GROUP', 'TEACHER_PARENT');
COMMENT ON TYPE "ChatRoomType" IS 'Wave 23 — chat_room_type enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: ChequeStatus (6 values)
DROP TYPE IF EXISTS "ChequeStatus";
CREATE TYPE "ChequeStatus" AS ENUM ('ISSUED', 'DEPOSITED', 'CLEARED', 'BOUNCED', 'CANCELLED', 'RE_ISSUED');
COMMENT ON TYPE "ChequeStatus" IS 'Wave 23 — cheque_status enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: ComplianceType (12 values)
DROP TYPE IF EXISTS "ComplianceType";
CREATE TYPE "ComplianceType" AS ENUM ('FIRE_NOC', 'FIRE_EXTINGUISHER', 'FIRE_DRILL', 'FSSAI_LICENSE', 'CCTV_RETENTION', 'POSH_TRAINING', 'FOOD_HANDLER_MEDICAL', 'ICC_CONSTITUTION', 'STAFF_BG_VERIFICATION', 'BUILDING_SAFETY', 'ELECTRICAL_INSPECTION', 'OTHER');
COMMENT ON TYPE "ComplianceType" IS 'Wave 23 — compliance_type enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: ConsentType (6 values)
DROP TYPE IF EXISTS "ConsentType";
CREATE TYPE "ConsentType" AS ENUM ('EXPLICIT', 'IMPLICIT', 'OPT_IN', 'OPT_OUT', 'PARENTAL', 'GUARDIAN');
COMMENT ON TYPE "ConsentType" IS 'Wave 23 — consent_type enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: DamagedItemAction (6 values)
DROP TYPE IF EXISTS "DamagedItemAction";
CREATE TYPE "DamagedItemAction" AS ENUM ('REPAIR', 'DISPOSE', 'WRITE_OFF', 'RETURN_TO_VENDOR', 'REPLACE', 'DONATE');
COMMENT ON TYPE "DamagedItemAction" IS 'Wave 23 — damaged_item_action enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: DiscountType (9 values)
DROP TYPE IF EXISTS "DiscountType";
CREATE TYPE "DiscountType" AS ENUM ('PERCENTAGE', 'FIXED_AMOUNT', 'SIBLING', 'EARLY_BIRD', 'SCHOLARSHIP', 'STAFF_WARD', 'ALUMNI', 'MERIT', 'NEED_BASED');
COMMENT ON TYPE "DiscountType" IS 'Wave 23 — discount_type enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: EmailStatus (9 values)
DROP TYPE IF EXISTS "EmailStatus";
CREATE TYPE "EmailStatus" AS ENUM ('QUEUED', 'SENT', 'FAILED', 'BOUNCED', 'DEFERRED', 'CANCELLED', 'DELIVERED', 'OPENED', 'CLICKED');
COMMENT ON TYPE "EmailStatus" IS 'Wave 23 — email_status enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: EmergencyType (8 values)
DROP TYPE IF EXISTS "EmergencyType";
CREATE TYPE "EmergencyType" AS ENUM ('FIRE', 'EARTHQUAKE', 'LOCKDOWN', 'MEDICAL', 'INTRUDER', 'WEATHER', 'EVACUATION', 'OTHER');
COMMENT ON TYPE "EmergencyType" IS 'Wave 23 — emergency_type enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: EventStatus (6 values)
DROP TYPE IF EXISTS "EventStatus";
CREATE TYPE "EventStatus" AS ENUM ('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'POSTPONED', 'DRAFT');
COMMENT ON TYPE "EventStatus" IS 'Wave 23 — event_status enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: EventType (10 values)
DROP TYPE IF EXISTS "EventType";
CREATE TYPE "EventType" AS ENUM ('HOLIDAY', 'EXAM', 'PTM', 'SPORTS_DAY', 'CULTURAL', 'FIELD_TRIP', 'PROFESSIONAL_DAY', 'WORKSHOP', 'ASSEMBLY', 'OTHER');
COMMENT ON TYPE "EventType" IS 'Wave 23 — event_type enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: ExitType (6 values)
DROP TYPE IF EXISTS "ExitType";
CREATE TYPE "ExitType" AS ENUM ('GRADUATION', 'TRANSFER', 'WITHDRAWAL', 'EXPULSION', 'RELOCATION', 'DEATH');
COMMENT ON TYPE "ExitType" IS 'Wave 23 — exit_type enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: ExpenseStatus (6 values)
DROP TYPE IF EXISTS "ExpenseStatus";
CREATE TYPE "ExpenseStatus" AS ENUM ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'PAID', 'CANCELLED');
COMMENT ON TYPE "ExpenseStatus" IS 'Wave 23 — expense_status enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: FeeHeadFrequency (6 values)
DROP TYPE IF EXISTS "FeeHeadFrequency";
CREATE TYPE "FeeHeadFrequency" AS ENUM ('ONE_TIME', 'MONTHLY', 'QUARTERLY', 'HALF_YEARLY', 'ANNUAL', 'TERM_WISE');
COMMENT ON TYPE "FeeHeadFrequency" IS 'Wave 23 — fee_head_frequency enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: FeeHeadType (10 values)
DROP TYPE IF EXISTS "FeeHeadType";
CREATE TYPE "FeeHeadType" AS ENUM ('TUITION', 'TRANSPORT', 'HOSTEL', 'LIBRARY', 'LAB', 'EXAMINATION', 'SPORTS', 'CULTURAL', 'LATE_FEE', 'MISCELLANEOUS');
COMMENT ON TYPE "FeeHeadType" IS 'Wave 23 — fee_head_type enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: FinancialReportType (9 values)
DROP TYPE IF EXISTS "FinancialReportType";
CREATE TYPE "FinancialReportType" AS ENUM ('BALANCE_SHEET', 'P_AND_L', 'CASH_FLOW', 'FEE_COLLECTION', 'EXPENSE_SUMMARY', 'GST_RETURN', 'TDS_RETURN', 'BANK_RECONCILIATION', 'TRIAL_BALANCE');
COMMENT ON TYPE "FinancialReportType" IS 'Wave 23 — financial_report_type enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: GRNStatus (7 values)
DROP TYPE IF EXISTS "GRNStatus";
CREATE TYPE "GRNStatus" AS ENUM ('DRAFT', 'PENDING_INSPECTION', 'INSPECTED', 'ACCEPTED', 'PARTIALLY_ACCEPTED', 'REJECTED', 'CANCELLED');
COMMENT ON TYPE "GRNStatus" IS 'Wave 23 — g_r_n_status enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: IncomeStatus (6 values)
DROP TYPE IF EXISTS "IncomeStatus";
CREATE TYPE "IncomeStatus" AS ENUM ('DRAFT', 'PENDING', 'RECEIVED', 'PARTIALLY_RECEIVED', 'CANCELLED', 'WRITTEN_OFF');
COMMENT ON TYPE "IncomeStatus" IS 'Wave 23 — income_status enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: IntegrationStatus (6 values)
DROP TYPE IF EXISTS "IntegrationStatus";
CREATE TYPE "IntegrationStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'ERROR', 'SUSPENDED', 'PENDING_AUTH', 'EXPIRED');
COMMENT ON TYPE "IntegrationStatus" IS 'Wave 23 — integration_status enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: InventoryCategoryName (11 values)
DROP TYPE IF EXISTS "InventoryCategoryName";
CREATE TYPE "InventoryCategoryName" AS ENUM ('STATIONERY', 'BOOKS', 'FURNITURE', 'ELECTRONICS', 'KITCHEN_SUPPLIES', 'CLEANING_SUPPLIES', 'SPORTS_EQUIPMENT', 'ART_SUPPLIES', 'MEDICAL_SUPPLIES', 'OFFICE_SUPPLIES', 'OTHER');
COMMENT ON TYPE "InventoryCategoryName" IS 'Wave 23 — inventory_category_name enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: ItemCondition (6 values)
DROP TYPE IF EXISTS "ItemCondition";
CREATE TYPE "ItemCondition" AS ENUM ('EXCELLENT', 'GOOD', 'FAIR', 'POOR', 'BROKEN', 'DAMAGED');
COMMENT ON TYPE "ItemCondition" IS 'Wave 23 — item_condition enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: JobApplicationStatus (10 values)
DROP TYPE IF EXISTS "JobApplicationStatus";
CREATE TYPE "JobApplicationStatus" AS ENUM ('DRAFT', 'SUBMITTED', 'SCREENING', 'INTERVIEW_SCHEDULED', 'INTERVIEWED', 'OFFERED', 'HIRED', 'REJECTED', 'WITHDRAWN', 'ON_HOLD');
COMMENT ON TYPE "JobApplicationStatus" IS 'Wave 23 — job_application_status enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: JobStatus (6 values)
DROP TYPE IF EXISTS "JobStatus";
CREATE TYPE "JobStatus" AS ENUM ('OPEN', 'ON_HOLD', 'CLOSED', 'CANCELLED', 'FILLED', 'DRAFT');
COMMENT ON TYPE "JobStatus" IS 'Wave 23 — job_status enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: LeadScoreTier (4 values)
DROP TYPE IF EXISTS "LeadScoreTier";
CREATE TYPE "LeadScoreTier" AS ENUM ('HOT', 'WARM', 'COLD', 'UNQUALIFIED');
COMMENT ON TYPE "LeadScoreTier" IS 'Wave 23 — lead_score_tier enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: LowStockAlertType (4 values)
DROP TYPE IF EXISTS "LowStockAlertType";
CREATE TYPE "LowStockAlertType" AS ENUM ('BELOW_REORDER', 'OUT_OF_STOCK', 'BELOW_SAFETY_STOCK', 'EXPIRING_SOON');
COMMENT ON TYPE "LowStockAlertType" IS 'Wave 23 — low_stock_alert_type enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: MealAmountEaten (6 values)
DROP TYPE IF EXISTS "MealAmountEaten";
CREATE TYPE "MealAmountEaten" AS ENUM ('NONE', 'QUARTER', 'HALF', 'THREE_QUARTER', 'FULL', 'REFUSED');
COMMENT ON TYPE "MealAmountEaten" IS 'Wave 23 — meal_amount_eaten enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: Mood (9 values)
DROP TYPE IF EXISTS "Mood";
CREATE TYPE "Mood" AS ENUM ('HAPPY', 'CALM', 'EXCITED', 'NEUTRAL', 'TIRED', 'SAD', 'ANGRY', 'ANXIOUS', 'ILL');
COMMENT ON TYPE "Mood" IS 'Wave 23 — mood enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: PaymentMode (10 values)
DROP TYPE IF EXISTS "PaymentMode";
CREATE TYPE "PaymentMode" AS ENUM ('CASH', 'CHEQUE', 'DEMAND_DRAFT', 'BANK_TRANSFER', 'CREDIT_CARD', 'DEBIT_CARD', 'UPI', 'WALLET', 'CARD_SWIPE', 'NET_BANKING');
COMMENT ON TYPE "PaymentMode" IS 'Wave 23 — payment_mode enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: PenaltyType (5 values)
DROP TYPE IF EXISTS "PenaltyType";
CREATE TYPE "PenaltyType" AS ENUM ('LATE_FEE', 'BOUNCE_CHARGE', 'NSF_CHARGE', 'PENALTY_INTEREST', 'OTHER');
COMMENT ON TYPE "PenaltyType" IS 'Wave 23 — penalty_type enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: PromotionStatus (6 values)
DROP TYPE IF EXISTS "PromotionStatus";
CREATE TYPE "PromotionStatus" AS ENUM ('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED');
COMMENT ON TYPE "PromotionStatus" IS 'Wave 23 — promotion_status enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: RSVPResponse (4 values)
DROP TYPE IF EXISTS "RSVPResponse";
CREATE TYPE "RSVPResponse" AS ENUM ('YES', 'NO', 'MAYBE', 'NO_RESPONSE');
COMMENT ON TYPE "RSVPResponse" IS 'Wave 23 — r_s_v_p_response enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: ReferralStatus (5 values)
DROP TYPE IF EXISTS "ReferralStatus";
CREATE TYPE "ReferralStatus" AS ENUM ('PENDING', 'CONTACTED', 'CONVERTED', 'REJECTED', 'EXPIRED');
COMMENT ON TYPE "ReferralStatus" IS 'Wave 23 — referral_status enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: ReportSchedule (6 values)
DROP TYPE IF EXISTS "ReportSchedule";
CREATE TYPE "ReportSchedule" AS ENUM ('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', 'CUSTOM');
COMMENT ON TYPE "ReportSchedule" IS 'Wave 23 — report_schedule enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: ReviewPeriod (6 values)
DROP TYPE IF EXISTS "ReviewPeriod";
CREATE TYPE "ReviewPeriod" AS ENUM ('WEEKLY', 'MONTHLY', 'QUARTERLY', 'HALF_YEARLY', 'ANNUAL', 'BI_ANNUAL');
COMMENT ON TYPE "ReviewPeriod" IS 'Wave 23 — review_period enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: RoomType (10 values)
DROP TYPE IF EXISTS "RoomType";
CREATE TYPE "RoomType" AS ENUM ('CLASSROOM', 'LAB', 'LIBRARY', 'PLAY_AREA', 'STAFF_ROOM', 'OFFICE', 'STORAGE', 'KITCHEN', 'WASHROOM', 'OTHER');
COMMENT ON TYPE "RoomType" IS 'Wave 23 — room_type enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: SMSStatus (6 values)
DROP TYPE IF EXISTS "SMSStatus";
CREATE TYPE "SMSStatus" AS ENUM ('QUEUED', 'SENT', 'FAILED', 'DELIVERED', 'UNDELIVERED', 'CANCELLED');
COMMENT ON TYPE "SMSStatus" IS 'Wave 23 — s_m_s_status enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: StaffDepartment (10 values)
DROP TYPE IF EXISTS "StaffDepartment";
CREATE TYPE "StaffDepartment" AS ENUM ('TEACHING', 'NON_TEACHING', 'ADMINISTRATION', 'TRANSPORT', 'HOUSEKEEPING', 'KITCHEN', 'SECURITY', 'ACCOUNTS', 'IT', 'HR');
COMMENT ON TYPE "StaffDepartment" IS 'Wave 23 — staff_department enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: StaffDesignation (13 values)
DROP TYPE IF EXISTS "StaffDesignation";
CREATE TYPE "StaffDesignation" AS ENUM ('PRINCIPAL', 'VICE_PRINCIPAL', 'COORDINATOR', 'TEACHER', 'ASSISTANT_TEACHER', 'COUNSELOR', 'ADMIN_OFFICER', 'ACCOUNTANT', 'DRIVER', 'ATTENDER', 'HOUSEKEEPING_STAFF', 'SECURITY_GUARD', 'OTHER');
COMMENT ON TYPE "StaffDesignation" IS 'Wave 23 — staff_designation enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: StaffStatus (8 values)
DROP TYPE IF EXISTS "StaffStatus";
CREATE TYPE "StaffStatus" AS ENUM ('ACTIVE', 'ON_LEAVE', 'SUSPENDED', 'TERMINATED', 'RESIGNED', 'RETIRED', 'PROBATION', 'CONTRACT_ENDED');
COMMENT ON TYPE "StaffStatus" IS 'Wave 23 — staff_status enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: StockIssueStatus (7 values)
DROP TYPE IF EXISTS "StockIssueStatus";
CREATE TYPE "StockIssueStatus" AS ENUM ('DRAFT', 'PENDING', 'APPROVED', 'ISSUED', 'PARTIALLY_ISSUED', 'REJECTED', 'CANCELLED');
COMMENT ON TYPE "StockIssueStatus" IS 'Wave 23 — stock_issue_status enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: StockReturnType (7 values)
DROP TYPE IF EXISTS "StockReturnType";
CREATE TYPE "StockReturnType" AS ENUM ('DAMAGED', 'EXPIRED', 'WRONG_ITEM', 'QUALITY_ISSUE', 'EXCESS_QUANTITY', 'RECALL', 'OTHER');
COMMENT ON TYPE "StockReturnType" IS 'Wave 23 — stock_return_type enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: ToiletType (5 values)
DROP TYPE IF EXISTS "ToiletType";
CREATE TYPE "ToiletType" AS ENUM ('WET', 'DRY', 'BOTH', 'SOILED', 'NONE');
COMMENT ON TYPE "ToiletType" IS 'Wave 23 — toilet_type enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: TransferReason (8 values)
DROP TYPE IF EXISTS "TransferReason";
CREATE TYPE "TransferReason" AS ENUM ('RELOCATION', 'PARENT_REQUEST', 'ACADEMIC', 'DISCIPLINARY', 'FEE_DEFAULT', 'MEDICAL', 'GRADUATION', 'OTHER');
COMMENT ON TYPE "TransferReason" IS 'Wave 23 — transfer_reason enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: TriggerEvent (7 values)
DROP TYPE IF EXISTS "TriggerEvent";
CREATE TYPE "TriggerEvent" AS ENUM ('MANUAL', 'SCHEDULED', 'ON_CREATE', 'ON_UPDATE', 'ON_DELETE', 'THRESHOLD_BREACH', 'EXTERNAL_WEBHOOK');
COMMENT ON TYPE "TriggerEvent" IS 'Wave 23 — trigger_event enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: VisitorPurpose (7 values)
DROP TYPE IF EXISTS "VisitorPurpose";
CREATE TYPE "VisitorPurpose" AS ENUM ('PARENT_VISIT', 'VENDOR_DELIVERY', 'OFFICIAL', 'INTERVIEW', 'MAINTENANCE', 'INSPECTION', 'OTHER');
COMMENT ON TYPE "VisitorPurpose" IS 'Wave 23 — visitor_purpose enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: WhatsAppStatus (6 values)
DROP TYPE IF EXISTS "WhatsAppStatus";
CREATE TYPE "WhatsAppStatus" AS ENUM ('QUEUED', 'SENT', 'FAILED', 'DELIVERED', 'READ', 'CANCELLED');
COMMENT ON TYPE "WhatsAppStatus" IS 'Wave 23 — whats_app_status enum (replaces Wave 13 PLACEHOLDER).';

-- Enum: WriteOffReason (6 values)
DROP TYPE IF EXISTS "WriteOffReason";
CREATE TYPE "WriteOffReason" AS ENUM ('DAMAGED_BEYOND_REPAIR', 'OBSOLETE', 'LOST', 'STOLEN', 'EXPIRED', 'OTHER');
COMMENT ON TYPE "WriteOffReason" IS 'Wave 23 — write_off_reason enum (replaces Wave 13 PLACEHOLDER).';

