-- PreOne Wave 23.01 — Cross-cutting shared tables
-- =====================================================================
-- Migration ID: 20260717000001_wave_23_01_cross_cutting_tables
-- Wave: 23
-- Idempotent: YES (uses CREATE TYPE/TABLE IF NOT EXISTS, DROP IF EXISTS)
--
-- Creates 15 cross-cutting tables that are referenced by every domain:
  event_store, file_storage, file_upload, job_queue, lock,
  sequence_counter, snapshot, system_health_check, webhook_outbox,
  email_queue, sms_queue, whatsapp_queue, food_sample_retention,
  cctv_coverage, compliance_item.

Each table follows PreOne conventions: UUID v7 PK, school_id discriminator,
audit columns, version column for optimistic concurrency, RLS policy,
and an updated_at trigger (for mutable tables).
--
-- Conventions (per ERD v3.0 §3 + BTD §16):
--   - Tables: snake_case plural
--   - Columns: snake_case
--   - PKs: UUID v7 (time-sortable)
--   - Timestamps: timestamptz
--   - Money: integer cents (amount_cents) — never float
--   - Soft delete: deleted_at timestamptz NULL
--   - Optimistic concurrency: version INTEGER DEFAULT 1
--   - Tenant isolation: school_id discriminator + RLS policy
--   - Audit columns: created_at, created_by, updated_at, updated_by,
--                    deleted_at, deleted_by
--
-- This migration is auto-generated by scripts/wave23_migrations_gen.py.
-- Do not edit by hand — re-run the script instead.

-- ───────────────────────────────────────────────────────────────────────
-- 1. event_store — append-only event log for event-sourced aggregates
--    (BTD §17.2 — Event Store pattern for audit + replay)
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS event_store (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE RESTRICT,
    branch_id       UUID REFERENCES branches(id) ON DELETE CASCADE,
    aggregate_type  VARCHAR(64) NOT NULL,
    aggregate_id    UUID NOT NULL,
    event_type      VARCHAR(96) NOT NULL,
    event_version   INTEGER NOT NULL,
    payload         JSONB NOT NULL,
    metadata        JSONB,
    causation_id    UUID,
    correlation_id  UUID,
    occurred_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    recorded_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS event_store_school_agg_idx
    ON event_store(school_id, aggregate_type, aggregate_id, event_version);
CREATE INDEX IF NOT EXISTS event_store_correlation_idx
    ON event_store(correlation_id) WHERE correlation_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS event_store_event_type_idx
    ON event_store(event_type);

-- ───────────────────────────────────────────────────────────────────────
-- 2. file_storage — metadata for stored files (Wave 19)
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS file_storage (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE RESTRICT,
    branch_id       UUID REFERENCES branches(id) ON DELETE CASCADE,
    bucket          VARCHAR(64) NOT NULL,
    object_key      VARCHAR(512) NOT NULL,
    original_name   VARCHAR(512) NOT NULL,
    mime_type       VARCHAR(128) NOT NULL,
    size_bytes      BIGINT NOT NULL CHECK (size_bytes > 0),
    checksum_sha256 VARCHAR(64) NOT NULL,
    storage_class   VARCHAR(20) NOT NULL DEFAULT 'STANDARD',
    is_encrypted    BOOLEAN NOT NULL DEFAULT FALSE,
    metadata        JSONB,
    expires_at      TIMESTAMPTZ,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    deleted_at      TIMESTAMPTZ,
    deleted_by      UUID REFERENCES users(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS file_storage_object_key_uq
    ON file_storage(bucket, object_key);
CREATE INDEX IF NOT EXISTS file_storage_school_idx
    ON file_storage(school_id, deleted_at);
CREATE INDEX IF NOT EXISTS file_storage_checksum_idx
    ON file_storage(checksum_sha256);

-- ───────────────────────────────────────────────────────────────────────
-- 3. file_upload — upload session tracking (multipart, resumable)
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS file_upload (
    id                  UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id           UUID NOT NULL REFERENCES schools(id) ON DELETE RESTRICT,
    branch_id           UUID REFERENCES branches(id) ON DELETE CASCADE,
    file_storage_id     UUID REFERENCES file_storage(id) ON DELETE SET NULL,
    upload_state        VARCHAR(20) NOT NULL DEFAULT 'INITIATED'
                        CHECK (upload_state IN ('INITIATED','IN_PROGRESS','COMPLETED','ABORTED','FAILED')),
    total_size_bytes    BIGINT NOT NULL DEFAULT 0,
    uploaded_bytes      BIGINT NOT NULL DEFAULT 0,
    chunk_count         INTEGER NOT NULL DEFAULT 0,
    chunks_received     INTEGER NOT NULL DEFAULT 0,
    mime_type           VARCHAR(128),
    original_name       VARCHAR(512),
    scan_state          VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                        CHECK (scan_state IN ('PENDING','CLEAN','INFECTED','ERROR')),
    scan_completed_at   TIMESTAMPTZ,
    scan_signature      VARCHAR(128),
    version             INTEGER NOT NULL DEFAULT 1,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by          UUID REFERENCES users(id) ON DELETE SET NULL,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by          UUID REFERENCES users(id) ON DELETE SET NULL,
    deleted_at          TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS file_upload_school_state_idx
    ON file_upload(school_id, upload_state, deleted_at);

-- ───────────────────────────────────────────────────────────────────────
-- 4. job_queue — durable background jobs (BTD §17.3)
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS job_queue (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID REFERENCES schools(id) ON DELETE CASCADE,
    job_type        VARCHAR(64) NOT NULL,
    payload         JSONB NOT NULL,
    priority        SMALLINT NOT NULL DEFAULT 100,
    status          VARCHAR(20) NOT NULL DEFAULT 'QUEUED'
                    CHECK (status IN ('QUEUED','RUNNING','COMPLETED','FAILED','CANCELLED','DEAD_LETTER')),
    attempts        INTEGER NOT NULL DEFAULT 0,
    max_attempts    SMALLINT NOT NULL DEFAULT 5,
    available_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    locked_by       VARCHAR(120),
    locked_at       TIMESTAMPTZ,
    last_error      TEXT,
    completed_at    TIMESTAMPTZ,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS job_queue_poll_idx
    ON job_queue(status, available_at, priority);

-- ───────────────────────────────────────────────────────────────────────
-- 5. lock — distributed advisory locks (DB-backed, BTD §17.4)
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lock (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    lock_key        VARCHAR(128) NOT NULL,
    holder          VARCHAR(120) NOT NULL,
    acquired_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at      TIMESTAMPTZ NOT NULL,
    metadata        JSONB
);
CREATE UNIQUE INDEX IF NOT EXISTS lock_key_uq ON lock(lock_key);

-- ───────────────────────────────────────────────────────────────────────
-- 6. sequence_counter — per-school per-key monotonic counter
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sequence_counter (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    counter_key     VARCHAR(64) NOT NULL,
    current_value   BIGINT NOT NULL DEFAULT 0,
    version         INTEGER NOT NULL DEFAULT 1,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (school_id, counter_key)
);

-- ───────────────────────────────────────────────────────────────────────
-- 7. snapshot — aggregate state snapshots (BTD §17.2 — snapshot optimization)
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS snapshot (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    aggregate_type  VARCHAR(64) NOT NULL,
    aggregate_id    UUID NOT NULL,
    aggregate_version INTEGER NOT NULL,
    state           JSONB NOT NULL,
    taken_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (aggregate_type, aggregate_id, aggregate_version)
);
CREATE INDEX IF NOT EXISTS snapshot_lookup_idx
    ON snapshot(aggregate_type, aggregate_id, aggregate_version DESC);

-- ───────────────────────────────────────────────────────────────────────
-- 8. system_health_check — heartbeat / probe results
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS system_health_check (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    component       VARCHAR(64) NOT NULL,
    probe           VARCHAR(64) NOT NULL,
    status          VARCHAR(20) NOT NULL
                    CHECK (status IN ('HEALTHY','DEGRADED','UNHEALTHY','UNKNOWN')),
    latency_ms      INTEGER,
    message         TEXT,
    metadata        JSONB,
    checked_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS system_health_check_comp_time_idx
    ON system_health_check(component, checked_at DESC);

-- ───────────────────────────────────────────────────────────────────────
-- 9. webhook_outbox — outbound webhook delivery queue (Wave 20)
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS webhook_outbox (
    id                  UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id           UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    webhook_endpoint_id UUID,
    event_type          VARCHAR(96) NOT NULL,
    payload             JSONB NOT NULL,
    attempt_count       INTEGER NOT NULL DEFAULT 0,
    max_attempts        SMALLINT NOT NULL DEFAULT 5,
    next_attempt_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_attempt_at     TIMESTAMPTZ,
    last_status_code    INTEGER,
    last_error          TEXT,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                        CHECK (status IN ('PENDING','DELIVERED','FAILED','DEAD_LETTER')),
    delivered_at        TIMESTAMPTZ,
    version             INTEGER NOT NULL DEFAULT 1,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS webhook_outbox_poll_idx
    ON webhook_outbox(status, next_attempt_at) WHERE status = 'PENDING';

-- ───────────────────────────────────────────────────────────────────────
-- 10. email_queue — outbound email queue (Wave 17 — SendGrid adapter)
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS email_queue (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID REFERENCES branches(id) ON DELETE CASCADE,
    template_key    VARCHAR(96),
    from_address    VARCHAR(255) NOT NULL,
    to_addresses    TEXT NOT NULL,
    cc_addresses    TEXT,
    bcc_addresses   TEXT,
    subject         VARCHAR(255) NOT NULL,
    body_html       TEXT,
    body_text       TEXT,
    attachments     JSONB,
    status          VARCHAR(20) NOT NULL DEFAULT 'QUEUED'
                    CHECK (status IN ('QUEUED','SENT','FAILED','BOUNCED','DEFERRED','CANCELLED')),
    provider        VARCHAR(32) NOT NULL DEFAULT 'SENDGRID',
    provider_id     VARCHAR(255),
    attempts        INTEGER NOT NULL DEFAULT 0,
    last_error      TEXT,
    sent_at         TIMESTAMPTZ,
    scheduled_for   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS email_queue_poll_idx
    ON email_queue(status, scheduled_for) WHERE status = 'QUEUED';

-- ───────────────────────────────────────────────────────────────────────
-- 11. sms_queue — outbound SMS queue (Wave 17 — Twilio adapter)
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sms_queue (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID REFERENCES branches(id) ON DELETE CASCADE,
    template_key    VARCHAR(96),
    to_number       VARCHAR(20) NOT NULL,
    from_number     VARCHAR(20),
    body            TEXT NOT NULL,
    dlt_template_id VARCHAR(64),
    dlt_entity_id   VARCHAR(64),
    status          VARCHAR(20) NOT NULL DEFAULT 'QUEUED'
                    CHECK (status IN ('QUEUED','SENT','FAILED','DELIVERED','UNDELIVERED','CANCELLED')),
    provider        VARCHAR(32) NOT NULL DEFAULT 'TWILIO',
    provider_id     VARCHAR(255),
    attempts        INTEGER NOT NULL DEFAULT 0,
    last_error      TEXT,
    sent_at         TIMESTAMPTZ,
    scheduled_for   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS sms_queue_poll_idx
    ON sms_queue(status, scheduled_for) WHERE status = 'QUEUED';

-- ───────────────────────────────────────────────────────────────────────
-- 12. whatsapp_queue — outbound WhatsApp queue
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS whatsapp_queue (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID REFERENCES branches(id) ON DELETE CASCADE,
    template_key    VARCHAR(96),
    to_number       VARCHAR(20) NOT NULL,
    template_name   VARCHAR(96),
    template_language VARCHAR(8) DEFAULT 'en',
    parameters      JSONB,
    status          VARCHAR(20) NOT NULL DEFAULT 'QUEUED'
                    CHECK (status IN ('QUEUED','SENT','FAILED','DELIVERED','READ','CANCELLED')),
    provider        VARCHAR(32) NOT NULL DEFAULT 'WHATSAPP_CLOUD',
    provider_id     VARCHAR(255),
    attempts        INTEGER NOT NULL DEFAULT 0,
    last_error      TEXT,
    sent_at         TIMESTAMPTZ,
    scheduled_for   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS whatsapp_queue_poll_idx
    ON whatsapp_queue(status, scheduled_for) WHERE status = 'QUEUED';

-- ───────────────────────────────────────────────────────────────────────
-- 13. food_sample_retention — FSSAI §15 sample logs (R-CMP-018)
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS food_sample_retention (
    id                  UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id           UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id           UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    meal_date           DATE NOT NULL,
    meal_type           VARCHAR(20) NOT NULL CHECK (meal_type IN ('BREAKFAST','LUNCH','SNACK','DINNER')),
    sample_image_url    VARCHAR(512),
    retained_until      DATE NOT NULL,
    destroyed_at        TIMESTAMPTZ,
    destroyed_by        UUID REFERENCES users(id) ON DELETE SET NULL,
    notes               TEXT,
    version             INTEGER NOT NULL DEFAULT 1,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by          UUID REFERENCES users(id) ON DELETE SET NULL,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by          UUID REFERENCES users(id) ON DELETE SET NULL,
    deleted_at          TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS food_sample_retention_school_date_idx
    ON food_sample_retention(school_id, meal_date);

-- ───────────────────────────────────────────────────────────────────────
-- 14. cctv_coverage — CCTV camera coverage map (R-CMP-005)
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS cctv_coverage (
    id                  UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id           UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id           UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    camera_id           VARCHAR(64) NOT NULL,
    location            VARCHAR(120) NOT NULL,
    coverage_zones      JSONB,
    retention_days      INTEGER NOT NULL DEFAULT 30 CHECK (retention_days >= 7),
    is_operational      BOOLEAN NOT NULL DEFAULT TRUE,
    last_health_check   TIMESTAMPTZ,
    notes               TEXT,
    version             INTEGER NOT NULL DEFAULT 1,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by          UUID REFERENCES users(id) ON DELETE SET NULL,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by          UUID REFERENCES users(id) ON DELETE SET NULL,
    deleted_at          TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS cctv_coverage_school_branch_idx
    ON cctv_coverage(school_id, branch_id, deleted_at);

-- ───────────────────────────────────────────────────────────────────────
-- 15. compliance_item — compliance tracker (R-CMP-007/013/014/017/018)
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS compliance_item (
    id                  UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id           UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id           UUID REFERENCES branches(id) ON DELETE CASCADE,
    category            VARCHAR(40) NOT NULL CHECK (category IN (
                        'FIRE_NOC','FIRE_EXTINGUISHER','FIRE_DRILL','FSSAI_LICENSE',
                        'CCTV_RETENTION','POSH_TRAINING','FOOD_HANDLER_MEDICAL',
                        'ICC_CONSTITUTION','STAFF_BG_VERIFICATION')),
    title               VARCHAR(255) NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                        CHECK (status IN ('PENDING','ACTIVE','EXPIRING_SOON','EXPIRED','OVERDUE','WAIVED')),
    issued_at           DATE,
    expires_at          DATE,
    issuing_authority   VARCHAR(120),
    document_url        VARCHAR(512),
    notes               TEXT,
    version             INTEGER NOT NULL DEFAULT 1,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by          UUID REFERENCES users(id) ON DELETE SET NULL,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by          UUID REFERENCES users(id) ON DELETE SET NULL,
    deleted_at          TIMESTAMPTZ,
    deleted_by          UUID REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS compliance_item_school_status_idx
    ON compliance_item(school_id, status, expires_at);

-- ───────────────────────────────────────────────────────────────────────
-- RLS policies (BTD §16 — tenant isolation)
-- ───────────────────────────────────────────────────────────────────────
ALTER TABLE event_store           ENABLE ROW LEVEL SECURITY;
ALTER TABLE file_storage          ENABLE ROW LEVEL SECURITY;
ALTER TABLE file_upload           ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_queue             ENABLE ROW LEVEL SECURITY;
ALTER TABLE snapshot              ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_outbox        ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_queue           ENABLE ROW LEVEL SECURITY;
ALTER TABLE sms_queue             ENABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp_queue        ENABLE ROW LEVEL SECURITY;
ALTER TABLE food_sample_retention ENABLE ROW LEVEL SECURITY;
ALTER TABLE cctv_coverage         ENABLE ROW LEVEL SECURITY;
ALTER TABLE compliance_item       ENABLE ROW LEVEL SECURITY;

-- lock / sequence_counter / system_health_check are not tenant-scoped
-- (system-level tables; protected by separate admin role grants).

CREATE POLICY event_store_tenant           ON event_store           USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY file_storage_tenant          ON file_storage          USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY file_upload_tenant           ON file_upload           USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY job_queue_tenant             ON job_queue             USING (school_id IS NULL OR school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY snapshot_tenant              ON snapshot              USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY webhook_outbox_tenant        ON webhook_outbox        USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY email_queue_tenant           ON email_queue           USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY sms_queue_tenant             ON sms_queue             USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY whatsapp_queue_tenant        ON whatsapp_queue        USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY food_sample_retention_tenant ON food_sample_retention USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY cctv_coverage_tenant         ON cctv_coverage         USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY compliance_item_tenant       ON compliance_item       USING (school_id = current_setting('app.current_school_id', true)::uuid);

-- ───────────────────────────────────────────────────────────────────────
-- updated_at triggers
-- ───────────────────────────────────────────────────────────────────────
DO $$
DECLARE t TEXT;
BEGIN
    FOR t IN SELECT unnest(ARRAY[
        'file_storage','file_upload','job_queue','webhook_outbox',
        'email_queue','sms_queue','whatsapp_queue','food_sample_retention',
        'cctv_coverage','compliance_item','sequence_counter','snapshot'
    ])
    LOOP
        EXECUTE format(
            'DROP TRIGGER IF EXISTS trg_%I_updated_at ON %I; '
            'CREATE TRIGGER trg_%I_updated_at BEFORE UPDATE ON %I '
            'FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();',
            t, t, t, t
        );
    END LOOP;
END $$;

