/**
 * Student Command Handlers — CQRS write side (BTD §12.2).
 *
 * Each handler:
 *   1. Loads aggregate(s) via repository
 *   2. Mutates aggregate (pure business logic in the aggregate)
 *   3. Saves aggregate via repository
 *   4. Returns minimal result (ID only — never read models)
 *   5. Domain events dispatched after commit
 */
import { Inject, Injectable, Logger } from '@nestjs/common';

import {
  CommandBus, CommandHandler,
} from '@shared/cqrs';
import {
  ConflictException, ValidationException,
} from '@common/errors/exceptions';

import {
  AddGuardianCommand, CreateStudentCommand, EnrollStudentCommand,
  GraduateStudentCommand, PromoteStudentCommand, SetPrimaryGuardianCommand,
  TransferStudentCommand, UpdateStudentCommand, WithdrawStudentCommand,
} from '../../application/commands/student.commands';
import { StudentService } from '../services/student.service';

// ─────────────────────────────────────────────
// CreateStudentCommandHandler
// ─────────────────────────────────────────────

@Injectable()
export class CreateStudentCommandHandler implements CommandHandler<CreateStudentCommand> {
  private readonly logger = new Logger(CreateStudentCommandHandler.name);
  private static readonly TYPE = 'Student.CreateStudent';

  constructor(
    private readonly bus: CommandBus,
    private readonly students: StudentService,
  ) {
    bus.register(CreateStudentCommandHandler.TYPE, this);
  }

  async handle(command: CreateStudentCommand): Promise<{ id: string }> {
    const { payload, metadata } = command;
    const student = await this.students.createStudent(
      payload as any,
      metadata.tenantId,
      metadata.actorId,
    );
    return { id: student.id };
  }
}

// ─────────────────────────────────────────────
// UpdateStudentCommandHandler
// ─────────────────────────────────────────────

@Injectable()
export class UpdateStudentCommandHandler implements CommandHandler<UpdateStudentCommand> {
  private static readonly TYPE = 'Student.UpdateStudent';

  constructor(
    private readonly bus: CommandBus,
    private readonly students: StudentService,
  ) {
    bus.register(UpdateStudentCommandHandler.TYPE, this);
  }

  async handle(command: UpdateStudentCommand): Promise<{ id: string }> {
    const { payload, metadata } = command;
    await this.students.updateStudent(payload.studentId, payload as any, metadata.tenantId);
    return { id: payload.studentId };
  }
}

// ─────────────────────────────────────────────
// EnrollStudentCommandHandler
// ─────────────────────────────────────────────

@Injectable()
export class EnrollStudentCommandHandler implements CommandHandler<EnrollStudentCommand> {
  private static readonly TYPE = 'Student.Enroll';

  constructor(
    private readonly bus: CommandBus,
    private readonly students: StudentService,
  ) {
    bus.register(EnrollStudentCommandHandler.TYPE, this);
  }

  async handle(command: EnrollStudentCommand): Promise<{ id: string; enrollmentId: string }> {
    const { payload, metadata } = command;
    await this.students.enrollStudent(
      payload.studentId,
      { sectionId: payload.sectionId, gradeLevel: payload.gradeLevel, enrolledAt: payload.enrolledAt },
      metadata.tenantId,
      metadata.actorId,
    );
    // enrollmentId is generated by the academics module when an Enrollment row
    // is created. For Wave 3 v1, the student service sets currentSectionId on
    // the student; the academics module creates the Enrollment row in a
    // separate step (admission approval saga — Wave 3.4).
    return { id: payload.studentId, enrollmentId: '' };
  }
}

@Injectable()
export class PromoteStudentCommandHandler implements CommandHandler<PromoteStudentCommand> {
  private static readonly TYPE = 'Student.Promote';
  constructor(
    private readonly bus: CommandBus,
    private readonly students: StudentService,
  ) { bus.register(PromoteStudentCommandHandler.TYPE, this); }
  async handle(command: PromoteStudentCommand): Promise<{ id: string }> {
    const { payload, metadata } = command;
    await this.students.promoteStudent(payload.studentId, payload, metadata.tenantId, metadata.actorId);
    return { id: payload.studentId };
  }
}

@Injectable()
export class TransferStudentCommandHandler implements CommandHandler<TransferStudentCommand> {
  private static readonly TYPE = 'Student.Transfer';
  constructor(
    private readonly bus: CommandBus,
    private readonly students: StudentService,
  ) { bus.register(TransferStudentCommandHandler.TYPE, this); }
  async handle(command: TransferStudentCommand): Promise<{ id: string }> {
    const { payload, metadata } = command;
    await this.students.transferStudent(payload.studentId, payload, metadata.tenantId, metadata.actorId);
    return { id: payload.studentId };
  }
}

@Injectable()
export class WithdrawStudentCommandHandler implements CommandHandler<WithdrawStudentCommand> {
  private static readonly TYPE = 'Student.Withdraw';
  constructor(
    private readonly bus: CommandBus,
    private readonly students: StudentService,
  ) { bus.register(WithdrawStudentCommandHandler.TYPE, this); }
  async handle(command: WithdrawStudentCommand): Promise<{ id: string }> {
    const { payload, metadata } = command;
    await this.students.withdrawStudent(payload.studentId, payload, metadata.tenantId, metadata.actorId);
    return { id: payload.studentId };
  }
}

@Injectable()
export class GraduateStudentCommandHandler implements CommandHandler<GraduateStudentCommand> {
  private static readonly TYPE = 'Student.Graduate';
  constructor(
    private readonly bus: CommandBus,
    private readonly students: StudentService,
  ) { bus.register(GraduateStudentCommandHandler.TYPE, this); }
  async handle(command: GraduateStudentCommand): Promise<{ id: string }> {
    const { payload, metadata } = command;
    await this.students.graduateStudent(payload.studentId, metadata.tenantId, metadata.actorId);
    return { id: payload.studentId };
  }
}

@Injectable()
export class AddGuardianCommandHandler implements CommandHandler<AddGuardianCommand> {
  private static readonly TYPE = 'Student.AddGuardian';
  constructor(
    private readonly bus: CommandBus,
    private readonly students: StudentService,
  ) { bus.register(AddGuardianCommandHandler.TYPE, this); }
  async handle(command: AddGuardianCommand): Promise<{ id: string; guardianId: string }> {
    const { payload, metadata } = command;
    await this.students.addGuardian(payload.studentId, payload.guardian as any, metadata.tenantId, metadata.actorId);
    return { id: payload.studentId, guardianId: '' };
  }
}

@Injectable()
export class SetPrimaryGuardianCommandHandler implements CommandHandler<SetPrimaryGuardianCommand> {
  private static readonly TYPE = 'Student.SetPrimaryGuardian';
  constructor(
    private readonly bus: CommandBus,
    private readonly students: StudentService,
  ) { bus.register(SetPrimaryGuardianCommandHandler.TYPE, this); }
  async handle(command: SetPrimaryGuardianCommand): Promise<{ id: string }> {
    const { payload, metadata } = command;
    await this.students.setPrimaryGuardian(payload.studentId, payload.guardianId, metadata.tenantId, metadata.actorId);
    return { id: payload.studentId };
  }
}
