-- PreOne Wave 23.06 — Administration tables
-- =====================================================================
-- Migration ID: 20260717000006_wave_23_06_administration_tables
-- Wave: 23
-- Idempotent: YES (uses CREATE TYPE/TABLE IF NOT EXISTS, DROP IF EXISTS)
--
-- Creates 20 administration tables:
  asset, asset_category, asset_maintenance, visitor, cctv_camera,
  cctv_alert, gate_pass, security_incident, emergency_contact,
  emergency_drill, emergency_alert, contact_directory,
  maintenance_request, vendor_visit, document_vault, document_share,
  insurance_policy, license_permit, audit_finding, audit_action.
--
-- Conventions (per ERD v3.0 §3 + BTD §16):
--   - Tables: snake_case plural
--   - Columns: snake_case
--   - PKs: UUID v7 (time-sortable)
--   - Timestamps: timestamptz
--   - Money: integer cents (amount_cents) — never float
--   - Soft delete: deleted_at timestamptz NULL
--   - Optimistic concurrency: version INTEGER DEFAULT 1
--   - Tenant isolation: school_id discriminator + RLS policy
--   - Audit columns: created_at, created_by, updated_at, updated_by,
--                    deleted_at, deleted_by
--
-- This migration is auto-generated by scripts/wave23_migrations_gen.py.
-- Do not edit by hand — re-run the script instead.

-- ───────────────────────────────────────────────────────────────────────
-- 1. asset — physical assets (computers, furniture, etc.)
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS asset (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    asset_code      VARCHAR(64) NOT NULL,
    name            VARCHAR(255) NOT NULL,
    category_id     UUID,
    asset_type      VARCHAR(64),
    serial_number   VARCHAR(120),
    purchase_date   DATE,
    purchase_cost_cents BIGINT CHECK (purchase_cost_cents >= 0),
    current_value_cents BIGINT CHECK (current_value_cents >= 0),
    salvage_value_cents BIGINT DEFAULT 0,
    useful_life_years SMALLINT,
    depreciation_method VARCHAR(20) DEFAULT 'STRAIGHT_LINE',
    condition       VARCHAR(20) DEFAULT 'GOOD'
                    CHECK (condition IN ('EXCELLENT','GOOD','FAIR','POOR','BROKEN')),
    assigned_to_id  UUID REFERENCES users(id) ON DELETE SET NULL,
    location        VARCHAR(255),
    status          VARCHAR(20) NOT NULL DEFAULT 'IN_USE'
                    CHECK (status IN ('IN_USE','IN_STORAGE','UNDER_REPAIR','DISPOSED','WRITTEN_OFF','LOST')),
    metadata        JSONB,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    deleted_at      TIMESTAMPTZ,
    deleted_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    UNIQUE (branch_id, asset_code)
);
CREATE INDEX IF NOT EXISTS asset_school_status_idx
    ON asset(school_id, status, deleted_at);

-- ───────────────────────────────────────────────────────────────────────
-- 2. asset_category — asset classification
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS asset_category (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    name            VARCHAR(120) NOT NULL,
    parent_id       UUID REFERENCES asset_category(id) ON DELETE SET NULL,
    depreciation_method VARCHAR(20) DEFAULT 'STRAIGHT_LINE',
    default_life_years SMALLINT,
    metadata        JSONB,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ,
    UNIQUE (school_id, name)
);

-- ───────────────────────────────────────────────────────────────────────
-- 3. asset_maintenance — asset maintenance records
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS asset_maintenance (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    asset_id        UUID NOT NULL REFERENCES asset(id) ON DELETE CASCADE,
    maintenance_type VARCHAR(32) NOT NULL CHECK (maintenance_type IN (
                    'PREVENTIVE','CORRECTIVE','INSPECTION','CALIBRATION','CLEANING')),
    status          VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED'
                    CHECK (status IN ('SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED')),
    scheduled_date  DATE,
    completed_date  DATE,
    vendor          VARCHAR(120),
    cost_cents      BIGINT DEFAULT 0,
    notes           TEXT,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    deleted_at      TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS asset_maintenance_asset_idx
    ON asset_maintenance(asset_id, scheduled_date);

-- ───────────────────────────────────────────────────────────────────────
-- 4. visitor — visitor check-in/out records
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS visitor (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    full_name       VARCHAR(255) NOT NULL,
    phone           VARCHAR(20),
    email           VARCHAR(255),
    purpose         VARCHAR(40) CHECK (purpose IN (
                    'PARENT_VISIT','VENDOR_DELIVERY','OFFICIAL','INTERVIEW',
                    'MAINTENANCE','INSPECTION','OTHER')),
    host_user_id    UUID REFERENCES users(id) ON DELETE SET NULL,
    check_in_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    check_out_at    TIMESTAMPTZ,
    visitor_pass    VARCHAR(32),
    photo_url       VARCHAR(512),
    id_proof_type   VARCHAR(40),
    id_proof_number VARCHAR(120),
    notes           TEXT,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS visitor_school_checkin_idx
    ON visitor(school_id, check_in_at DESC);

-- ───────────────────────────────────────────────────────────────────────
-- 5-8: cctv_camera, cctv_alert, gate_pass, security_incident
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS cctv_camera (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    camera_id       VARCHAR(64) NOT NULL,
    name            VARCHAR(120) NOT NULL,
    location        VARCHAR(255) NOT NULL,
    stream_url      VARCHAR(512),
    is_online       BOOLEAN NOT NULL DEFAULT FALSE,
    last_heartbeat  TIMESTAMPTZ,
    retention_days  INTEGER NOT NULL DEFAULT 30,
    metadata        JSONB,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ,
    UNIQUE (branch_id, camera_id)
);

CREATE TABLE IF NOT EXISTS cctv_alert (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    cctv_camera_id  UUID NOT NULL REFERENCES cctv_camera(id) ON DELETE CASCADE,
    alert_type      VARCHAR(40) NOT NULL,
    severity        VARCHAR(10) NOT NULL CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    triggered_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at     TIMESTAMPTZ,
    resolved_by     UUID REFERENCES users(id) ON DELETE SET NULL,
    metadata        JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS gate_pass (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    pass_code       VARCHAR(32) NOT NULL,
    pass_type       VARCHAR(20) NOT NULL CHECK (pass_type IN ('STUDENT','VISITOR','STAFF','VENDOR')),
    reference_id    UUID,
    issued_by       UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    issued_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at      TIMESTAMPTZ,
    used_at         TIMESTAMPTZ,
    notes           TEXT,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (branch_id, pass_code)
);

CREATE TABLE IF NOT EXISTS security_incident (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    incident_type   VARCHAR(40) NOT NULL,
    severity        VARCHAR(10) NOT NULL CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    occurred_at     TIMESTAMPTZ NOT NULL,
    reported_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reported_by     UUID REFERENCES users(id) ON DELETE SET NULL,
    description     TEXT NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'OPEN'
                    CHECK (status IN ('OPEN','INVESTIGATING','RESOLVED','CLOSED')),
    resolution      TEXT,
    resolved_at     TIMESTAMPTZ,
    resolved_by     UUID REFERENCES users(id) ON DELETE SET NULL,
    metadata        JSONB,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ───────────────────────────────────────────────────────────────────────
-- 9-12: emergency_contact, emergency_drill, emergency_alert, contact_directory
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS emergency_contact (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID REFERENCES branches(id) ON DELETE CASCADE,
    contact_type    VARCHAR(40) NOT NULL,
    name            VARCHAR(255) NOT NULL,
    role            VARCHAR(120),
    phone           VARCHAR(20) NOT NULL,
    email           VARCHAR(255),
    is_primary      BOOLEAN NOT NULL DEFAULT FALSE,
    priority_order  SMALLINT DEFAULT 0,
    metadata        JSONB,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS emergency_drill (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    drill_type      VARCHAR(40) NOT NULL CHECK (drill_type IN ('FIRE','EARTHQUAKE','LOCKDOWN','EVACUATION')),
    scheduled_at    TIMESTAMPTZ NOT NULL,
    completed_at    TIMESTAMPTZ,
    participants_count INTEGER,
    observations    TEXT,
    status          VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED'
                    CHECK (status IN ('SCHEDULED','COMPLETED','CANCELLED','FAILED')),
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS emergency_alert (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID REFERENCES branches(id) ON DELETE CASCADE,
    alert_type      VARCHAR(40) NOT NULL,
    severity        VARCHAR(10) NOT NULL CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    message         TEXT NOT NULL,
    triggered_by    UUID REFERENCES users(id) ON DELETE SET NULL,
    triggered_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    channels        TEXT[] NOT NULL DEFAULT ARRAY['SMS','EMAIL'],
    recipients_count INTEGER,
    status          VARCHAR(20) NOT NULL DEFAULT 'SENT'
                    CHECK (status IN ('DRAFT','SENT','FAILED','CANCELLED')),
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS contact_directory (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID REFERENCES branches(id) ON DELETE CASCADE,
    category        VARCHAR(40) NOT NULL,
    name            VARCHAR(255) NOT NULL,
    designation     VARCHAR(120),
    organisation    VARCHAR(255),
    phone           VARCHAR(20),
    email           VARCHAR(255),
    address         TEXT,
    is_verified     BOOLEAN NOT NULL DEFAULT FALSE,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ
);

-- ───────────────────────────────────────────────────────────────────────
-- 13-16: maintenance_request, vendor_visit, document_vault, document_share
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS maintenance_request (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    title           VARCHAR(255) NOT NULL,
    description     TEXT,
    category        VARCHAR(40) NOT NULL,
    priority        VARCHAR(10) NOT NULL DEFAULT 'MEDIUM'
                    CHECK (priority IN ('LOW','MEDIUM','HIGH','URGENT')),
    status          VARCHAR(20) NOT NULL DEFAULT 'OPEN'
                    CHECK (status IN ('OPEN','ASSIGNED','IN_PROGRESS','COMPLETED','CANCELLED')),
    asset_id        UUID REFERENCES asset(id) ON DELETE SET NULL,
    requested_by    UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    assigned_to     UUID,
    completed_at    TIMESTAMPTZ,
    cost_cents      BIGINT DEFAULT 0,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS vendor_visit (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    vendor_name     VARCHAR(255) NOT NULL,
    purpose         VARCHAR(255) NOT NULL,
    contact_person  VARCHAR(120),
    phone           VARCHAR(20),
    check_in_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    check_out_at    TIMESTAMPTZ,
    host_user_id    UUID REFERENCES users(id) ON DELETE SET NULL,
    notes           TEXT,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS document_vault (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID REFERENCES branches(id) ON DELETE CASCADE,
    title           VARCHAR(255) NOT NULL,
    document_type   VARCHAR(40) NOT NULL,
    file_storage_id UUID REFERENCES file_storage(id) ON DELETE RESTRICT,
    description     TEXT,
    tags            TEXT[],
    is_confidential BOOLEAN NOT NULL DEFAULT FALSE,
    retention_until DATE,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    deleted_at      TIMESTAMPTZ,
    deleted_by      UUID REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS document_share (
    id                  UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id           UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    document_vault_id   UUID NOT NULL REFERENCES document_vault(id) ON DELETE CASCADE,
    shared_by           UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    shared_with_user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    shared_with_role_id UUID,
    permissions         TEXT[] NOT NULL DEFAULT ARRAY['VIEW'],
    expires_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (shared_with_user_id IS NOT NULL OR shared_with_role_id IS NOT NULL)
);

-- ───────────────────────────────────────────────────────────────────────
-- 17-20: insurance_policy, license_permit, audit_finding, audit_action
-- ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS insurance_policy (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID REFERENCES branches(id) ON DELETE CASCADE,
    policy_type     VARCHAR(40) NOT NULL,
    policy_number   VARCHAR(120) NOT NULL,
    provider        VARCHAR(255) NOT NULL,
    coverage_cents  BIGINT NOT NULL CHECK (coverage_cents >= 0),
    premium_cents   BIGINT CHECK (premium_cents >= 0),
    start_date      DATE NOT NULL,
    end_date        DATE NOT NULL,
    beneficiaries   TEXT,
    document_url    VARCHAR(512),
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS license_permit (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID REFERENCES branches(id) ON DELETE CASCADE,
    permit_type     VARCHAR(80) NOT NULL,
    license_number  VARCHAR(120) NOT NULL,
    issuing_authority VARCHAR(255) NOT NULL,
    issue_date      DATE NOT NULL,
    expiry_date     DATE NOT NULL,
    renewal_date    DATE,
    document_url    VARCHAR(512),
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
                    CHECK (status IN ('ACTIVE','EXPIRED','PENDING_RENEWAL','SUSPENDED','CANCELLED')),
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS audit_finding (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    school_id       UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    branch_id       UUID REFERENCES branches(id) ON DELETE CASCADE,
    audit_id        UUID,
    finding_type    VARCHAR(40) NOT NULL,
    severity        VARCHAR(10) NOT NULL CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    title           VARCHAR(255) NOT NULL,
    description     TEXT NOT NULL,
    identified_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status          VARCHAR(20) NOT NULL DEFAULT 'OPEN'
                    CHECK (status IN ('OPEN','REMEDIATION','RESOLVED','ACCEPTED_RISK')),
    resolved_at     TIMESTAMPTZ,
    version         INTEGER NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS audit_action (
    id              UUID PRIMARY KEY DEFAULT uuid_v7(),
    audit_finding_id UUID NOT NULL REFERENCES audit_finding(id) ON DELETE CASCADE,
    action_text     TEXT NOT NULL,
    action_owner    UUID REFERENCES users(id) ON DELETE SET NULL,
    due_date        DATE,
    completed_at    TIMESTAMPTZ,
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                    CHECK (status IN ('PENDING','IN_PROGRESS','COMPLETED','CANCELLED')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ───────────────────────────────────────────────────────────────────────
-- RLS + triggers (selected tenant-scoped tables)
-- ───────────────────────────────────────────────────────────────────────
ALTER TABLE asset                    ENABLE ROW LEVEL SECURITY;
ALTER TABLE asset_category           ENABLE ROW LEVEL SECURITY;
ALTER TABLE asset_maintenance        ENABLE ROW LEVEL SECURITY;
ALTER TABLE visitor                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE cctv_camera              ENABLE ROW LEVEL SECURITY;
ALTER TABLE cctv_alert               ENABLE ROW LEVEL SECURITY;
ALTER TABLE gate_pass                ENABLE ROW LEVEL SECURITY;
ALTER TABLE security_incident        ENABLE ROW LEVEL SECURITY;
ALTER TABLE emergency_contact        ENABLE ROW LEVEL SECURITY;
ALTER TABLE emergency_drill          ENABLE ROW LEVEL SECURITY;
ALTER TABLE emergency_alert          ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_directory        ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_request      ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendor_visit             ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_vault           ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_share           ENABLE ROW LEVEL SECURITY;
ALTER TABLE insurance_policy         ENABLE ROW LEVEL SECURITY;
ALTER TABLE license_permit           ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_finding            ENABLE ROW LEVEL SECURITY;

CREATE POLICY asset_tenant             ON asset             USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY asset_category_tenant    ON asset_category    USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY asset_maintenance_tenant ON asset_maintenance USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY visitor_tenant           ON visitor           USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY cctv_camera_tenant       ON cctv_camera       USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY cctv_alert_tenant        ON cctv_alert        USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY gate_pass_tenant         ON gate_pass         USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY security_incident_tenant ON security_incident USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY emergency_contact_tenant ON emergency_contact USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY emergency_drill_tenant   ON emergency_drill   USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY emergency_alert_tenant   ON emergency_alert   USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY contact_directory_tenant ON contact_directory USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY maintenance_request_tenant ON maintenance_request USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY vendor_visit_tenant      ON vendor_visit      USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY document_vault_tenant    ON document_vault    USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY document_share_tenant    ON document_share    USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY insurance_policy_tenant  ON insurance_policy  USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY license_permit_tenant    ON license_permit    USING (school_id = current_setting('app.current_school_id', true)::uuid);
CREATE POLICY audit_finding_tenant     ON audit_finding     USING (school_id = current_setting('app.current_school_id', true)::uuid);

DO $$
DECLARE t TEXT;
BEGIN
    FOR t IN SELECT unnest(ARRAY[
        'asset','asset_category','asset_maintenance','visitor','cctv_camera',
        'cctv_alert','gate_pass','security_incident','emergency_contact',
        'emergency_drill','emergency_alert','contact_directory',
        'maintenance_request','vendor_visit','document_vault','document_share',
        'insurance_policy','license_permit','audit_finding','audit_action'
    ])
    LOOP
        EXECUTE format(
            'DROP TRIGGER IF EXISTS trg_%I_updated_at ON %I; '
            'CREATE TRIGGER trg_%I_updated_at BEFORE UPDATE ON %I '
            'FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();',
            t, t, t, t
        );
    END LOOP;
END $$;

