/**
 * DI tokens for Administration repositories.
 */
export const ASSET_REPOSITORY = Symbol('ASSET_REPOSITORY');
export const MAINTENANCE_REQUEST_REPOSITORY = Symbol('MAINTENANCE_REQUEST_REPOSITORY');
export const VISITOR_LOG_REPOSITORY = Symbol('VISITOR_LOG_REPOSITORY');
export const FACILITY_REPOSITORY = Symbol('FACILITY_REPOSITORY');
export const FACILITY_INSPECTION_REPOSITORY = Symbol('FACILITY_INSPECTION_REPOSITORY');
